name: zfgbb

services:
  postgresql:
    build:
      context: .
      dockerfile: Dockerfile
      target: database

    env_file:
      - .env.local
      - .env.docker

    environment:
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    volumes:
      - data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d
            ${ZFGBB_DATABASE:-zfgc_dev}",
        ]
      interval: 1s
      timeout: 3s
      retries: 30
      start_period: 2s

    restart: unless-stopped

    networks:
      - zfgbb

    extra_hosts:
      - "host.docker.internal:host-gateway"

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy

    env_file:
      - .env.local
      - .env.docker

    ports:
      - "${ZFGBB_BACKEND_PORT:-8080}:8080"

    volumes:
      - content:/usr/local/tomcat/webapps/content

    depends_on:
      postgresql:
        condition: service_healthy

    restart: unless-stopped

    networks:
      - zfgbb

    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  data:
  content:

networks:
  zfgbb:
    driver: bridge
