FROM php:5.6-apache

RUN set -eux; \
    printf 'Acquire::Check-Valid-Until "false";\n' > /etc/apt/apt.conf.d/99no-check-valid; \
    sed -i \
      -e 's|http://deb.debian.org/debian|http://archive.debian.org/debian|g' \
      -e 's|http://security.debian.org/debian-security|http://archive.debian.org/debian-security|g' \
      -e 's|http://security.debian.org|http://archive.debian.org|g' \
      -e '/stretch-updates/d' \
      /etc/apt/sources.list

RUN apt-get -o Acquire::AllowInsecureRepositories=true update \
    && apt-get install -y --allow-unauthenticated \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    libzip-dev \
    unzip \
    && docker-php-ext-configure gd --with-freetype-dir=/usr --with-jpeg-dir=/usr \
    && docker-php-ext-install -j"$(nproc)" mysqli gd zip \
    && rm -rf /var/lib/apt/lists/*

RUN { \
    echo "post_max_size = 32M"; \
    echo "upload_max_filesize = 32M"; \
    echo "memory_limit = 256M"; \
    } > /usr/local/etc/php/conf.d/smf.ini

RUN sed -ri 's/Listen 80$/Listen 8080/' /etc/apache2/ports.conf \
    && sed -ri 's!<VirtualHost \*:80>!<VirtualHost *:8080>!' /etc/apache2/sites-available/000-default.conf
EXPOSE 8080

COPY app/src/test/resources/smf-fixtures/2.0.15/smf_2-0-15_fixture.zip /tmp/smf.zip
RUN cd /var/www/html \
    && rm -rf ./* \
    && unzip -q /tmp/smf.zip \
    && rm /tmp/smf.zip \
    && chown -R www-data:www-data /var/www/html \
    && find /var/www/html -type d -exec chmod 755 {} \; \
    && find /var/www/html -type f -exec chmod 644 {} \; \
    && chmod -R 777 \
    /var/www/html/attachments \
    /var/www/html/avatars \
    /var/www/html/cache \
    /var/www/html/Packages \
    /var/www/html/Smileys \
    /var/www/html/Themes \
    && chmod 666 \
    /var/www/html/agreement.txt \
    /var/www/html/Settings.php \
    /var/www/html/Settings_bak.php
