services:
  pgadmin:
    container_name: zfgbb_pgadmin
    image: dpage/pgadmin4:9.2.0
    environment:
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT:-5050}
      PGADMIN_DEFAULT_EMAIL: admin@zfgc.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-local-pgadmin-password}
      PGADMIN_CONFIG_PASSWORD_STORE: "True"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      # Whitelist allowed IP addresses
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_ALLOWED_HOSTS: "${PGADMIN_ALLOWED_HOSTS:-['localhost', '127.0.0.1', 'host.docker.internal']}"
      # PGADMIN_CONFIG_PASSFILE: '"/var/lib/pgadmin/.pgpass"'
    ports:
      - "${PGADMIN_PORT:-5050}:${PGADMIN_PORT:-5050}"
    networks:
      - zfgbb
    volumes:
      - pgadmin:/var/lib/pgadmin

    depends_on:
      - postgresql
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pgadmin:
