package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.LatestMessageInThreadViewDbo;
import com.zfgc.zfgbb.dbo.LatestMessageInThreadViewDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LatestMessageInThreadViewDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.latest_message_in_thread_view
	 * @mbg.generated  Sun Feb 23 19:24:29 EST 2025
	 */
	long countByExample(LatestMessageInThreadViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.latest_message_in_thread_view
	 * @mbg.generated  Sun Feb 23 19:24:29 EST 2025
	 */
	int deleteByExample(LatestMessageInThreadViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.latest_message_in_thread_view
	 * @mbg.generated  Sun Feb 23 19:24:29 EST 2025
	 */
	int insert(LatestMessageInThreadViewDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.latest_message_in_thread_view
	 * @mbg.generated  Sun Feb 23 19:24:29 EST 2025
	 */
	int insertSelective(LatestMessageInThreadViewDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.latest_message_in_thread_view
	 * @mbg.generated  Sun Feb 23 19:24:29 EST 2025
	 */
	List<LatestMessageInThreadViewDbo> selectByExample(LatestMessageInThreadViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.latest_message_in_thread_view
	 * @mbg.generated  Sun Feb 23 19:24:29 EST 2025
	 */
	int updateByExampleSelective(@Param("row") LatestMessageInThreadViewDbo row,
			@Param("example") LatestMessageInThreadViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.latest_message_in_thread_view
	 * @mbg.generated  Sun Feb 23 19:24:29 EST 2025
	 */
	int updateByExample(@Param("row") LatestMessageInThreadViewDbo row,
			@Param("example") LatestMessageInThreadViewDboExample example);
	
	List<LatestMessageInThreadViewDbo> selectByExampleWithLimits(LatestMessageInThreadViewDboExample example);
}