package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.ThreadDbo;
import com.zfgc.zfgbb.dbo.ThreadDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ThreadDboMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	long countByExample(ThreadDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	int deleteByExample(ThreadDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	int deleteByPrimaryKey(Integer threadId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	int insert(ThreadDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	int insertSelective(ThreadDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	List<ThreadDbo> selectByExample(ThreadDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	ThreadDbo selectByPrimaryKey(Integer threadId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	int updateByExampleSelective(@Param("record") ThreadDbo record, @Param("example") ThreadDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	int updateByExample(@Param("record") ThreadDbo record, @Param("example") ThreadDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	int updateByPrimaryKeySelective(ThreadDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	int updateByPrimaryKey(ThreadDbo record);

	List<ThreadDbo> selectByExampleWithRange(ThreadDboExample example);
}