package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.EmailAddressDbo;
import com.zfgc.zfgbb.dbo.EmailAddressDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmailAddressDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated  Sun Sep 07 15:29:08 EDT 2025
	 */
	long countByExample(EmailAddressDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated  Sun Sep 07 15:29:08 EDT 2025
	 */
	int deleteByExample(EmailAddressDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated  Sun Sep 07 15:29:08 EDT 2025
	 */
	int deleteByPrimaryKey(Integer emailAddressId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated  Sun Sep 07 15:29:08 EDT 2025
	 */
	int insert(EmailAddressDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated  Sun Sep 07 15:29:08 EDT 2025
	 */
	int insertSelective(EmailAddressDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated  Sun Sep 07 15:29:08 EDT 2025
	 */
	List<EmailAddressDbo> selectByExample(EmailAddressDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated  Sun Sep 07 15:29:08 EDT 2025
	 */
	EmailAddressDbo selectByPrimaryKey(Integer emailAddressId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated  Sun Sep 07 15:29:08 EDT 2025
	 */
	int updateByExampleSelective(@Param("row") EmailAddressDbo row, @Param("example") EmailAddressDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated  Sun Sep 07 15:29:08 EDT 2025
	 */
	int updateByExample(@Param("row") EmailAddressDbo row, @Param("example") EmailAddressDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated  Sun Sep 07 15:29:08 EDT 2025
	 */
	int updateByPrimaryKeySelective(EmailAddressDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated  Sun Sep 07 15:29:08 EDT 2025
	 */
	int updateByPrimaryKey(EmailAddressDbo row);
}