package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.KarmaDbo;
import com.zfgc.zfgbb.dbo.KarmaDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KarmaDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.karma
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	long countByExample(KarmaDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.karma
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	int deleteByExample(KarmaDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.karma
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	int deleteByPrimaryKey(Integer karmaId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.karma
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	int insert(KarmaDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.karma
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	int insertSelective(KarmaDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.karma
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	List<KarmaDbo> selectByExample(KarmaDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.karma
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	KarmaDbo selectByPrimaryKey(Integer karmaId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.karma
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	int updateByExampleSelective(@Param("row") KarmaDbo row, @Param("example") KarmaDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.karma
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	int updateByExample(@Param("row") KarmaDbo row, @Param("example") KarmaDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.karma
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	int updateByPrimaryKeySelective(KarmaDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.karma
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	int updateByPrimaryKey(KarmaDbo row);
}