package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.PollChoiceDbo;
import com.zfgc.zfgbb.dbo.PollChoiceDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PollChoiceDboMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_choice
     *
     * @mbg.generated Mon Oct 20 23:18:49 EDT 2025
     */
    long countByExample(PollChoiceDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_choice
     *
     * @mbg.generated Mon Oct 20 23:18:49 EDT 2025
     */
    int deleteByExample(PollChoiceDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_choice
     *
     * @mbg.generated Mon Oct 20 23:18:49 EDT 2025
     */
    int deleteByPrimaryKey(Integer pollChoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_choice
     *
     * @mbg.generated Mon Oct 20 23:18:49 EDT 2025
     */
    int insert(PollChoiceDbo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_choice
     *
     * @mbg.generated Mon Oct 20 23:18:49 EDT 2025
     */
    int insertSelective(PollChoiceDbo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_choice
     *
     * @mbg.generated Mon Oct 20 23:18:49 EDT 2025
     */
    List<PollChoiceDbo> selectByExample(PollChoiceDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_choice
     *
     * @mbg.generated Mon Oct 20 23:18:49 EDT 2025
     */
    PollChoiceDbo selectByPrimaryKey(Integer pollChoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_choice
     *
     * @mbg.generated Mon Oct 20 23:18:49 EDT 2025
     */
    int updateByExampleSelective(@Param("row") PollChoiceDbo row, @Param("example") PollChoiceDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_choice
     *
     * @mbg.generated Mon Oct 20 23:18:49 EDT 2025
     */
    int updateByExample(@Param("row") PollChoiceDbo row, @Param("example") PollChoiceDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_choice
     *
     * @mbg.generated Mon Oct 20 23:18:49 EDT 2025
     */
    int updateByPrimaryKeySelective(PollChoiceDbo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_choice
     *
     * @mbg.generated Mon Oct 20 23:18:49 EDT 2025
     */
    int updateByPrimaryKey(PollChoiceDbo row);
}