package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.UserKarmaViewDbo;
import com.zfgc.zfgbb.dbo.UserKarmaViewDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserKarmaViewDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_karma_view
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	long countByExample(UserKarmaViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_karma_view
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	int deleteByExample(UserKarmaViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_karma_view
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	int insert(UserKarmaViewDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_karma_view
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	int insertSelective(UserKarmaViewDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_karma_view
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	List<UserKarmaViewDbo> selectByExample(UserKarmaViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_karma_view
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	int updateByExampleSelective(@Param("row") UserKarmaViewDbo row, @Param("example") UserKarmaViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_karma_view
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	int updateByExample(@Param("row") UserKarmaViewDbo row, @Param("example") UserKarmaViewDboExample example);
}