create index if not exists idx_thread_board_id on zfgbb.thread(board_id);
create index if not exists idx_message_thread_id on zfgbb.message(thread_id);
create index if not exists idx_message_thread_id_created_ts on zfgbb.message(thread_id, created_ts desc);
create index if not exists idx_message_owner_id on zfgbb.message(owner_id);
create index if not exists idx_message_created_ts on zfgbb.message(created_ts desc);
create index if not exists idx_message_history_message_id on zfgbb.message_history(message_id);
create index if not exists idx_message_history_ip_address_id on zfgbb.message_history(ip_address_id);
create index if not exists idx_file_attachments_message_id on zfgbb.file_attachments(message_id);
create index if not exists idx_poll_choice_poll_id on zfgbb.poll_choice(poll_id);
create index if not exists idx_board_category_id on zfgbb.board(category_id);
create index if not exists idx_board_parent_board_id on zfgbb.board(parent_board_id);
