package com.zfgc.zfgbb.dbo;

import java.time.LocalDateTime;

public class PollQuestionDbo extends AbstractDbo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.poll_question.poll_question_id
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    private Integer pollQuestionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.poll_question.answer_text
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    private String answerText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.poll_question.poll_id
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    private Integer pollId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.poll_question.votes
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    private Integer votes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.poll_question.created_ts
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    private LocalDateTime createdTs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.poll_question.updated_ts
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    private LocalDateTime updatedTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.poll_question.poll_question_id
     *
     * @return the value of zfgbb.poll_question.poll_question_id
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public Integer getPollQuestionId() {
        return pollQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.poll_question.poll_question_id
     *
     * @param pollQuestionId the value for zfgbb.poll_question.poll_question_id
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public void setPollQuestionId(Integer pollQuestionId) {
        this.pollQuestionId = pollQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.poll_question.answer_text
     *
     * @return the value of zfgbb.poll_question.answer_text
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public String getAnswerText() {
        return answerText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.poll_question.answer_text
     *
     * @param answerText the value for zfgbb.poll_question.answer_text
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public void setAnswerText(String answerText) {
        this.answerText = answerText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.poll_question.poll_id
     *
     * @return the value of zfgbb.poll_question.poll_id
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public Integer getPollId() {
        return pollId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.poll_question.poll_id
     *
     * @param pollId the value for zfgbb.poll_question.poll_id
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public void setPollId(Integer pollId) {
        this.pollId = pollId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.poll_question.votes
     *
     * @return the value of zfgbb.poll_question.votes
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public Integer getVotes() {
        return votes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.poll_question.votes
     *
     * @param votes the value for zfgbb.poll_question.votes
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public void setVotes(Integer votes) {
        this.votes = votes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.poll_question.created_ts
     *
     * @return the value of zfgbb.poll_question.created_ts
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public LocalDateTime getCreatedTs() {
        return createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.poll_question.created_ts
     *
     * @param createdTs the value for zfgbb.poll_question.created_ts
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public void setCreatedTs(LocalDateTime createdTs) {
        this.createdTs = createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.poll_question.updated_ts
     *
     * @return the value of zfgbb.poll_question.updated_ts
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public LocalDateTime getUpdatedTs() {
        return updatedTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.poll_question.updated_ts
     *
     * @param updatedTs the value for zfgbb.poll_question.updated_ts
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public void setUpdatedTs(LocalDateTime updatedTs) {
        this.updatedTs = updatedTs;
    }

    // Hand-written: the poll_question table was dropped in V20251019.1; this DBO
    // exists only because dead code in ThreadDataProvider still references it.
    // Cleanup of the dead references is tracked separately.
    @Override
    public Integer getPkId() {
        return pollQuestionId;
    }

    @Override
    public LocalDateTime getCreatedTime() {
        return createdTs;
    }

    @Override
    public LocalDateTime getUpdatedTime() {
        return updatedTs;
    }
}
