package com.zfgc.zfgbb.dbo;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class PollQuestionDboExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public PollQuestionDboExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPollQuestionIdIsNull() {
            addCriterion("poll_question_id is null");
            return (Criteria) this;
        }

        public Criteria andPollQuestionIdIsNotNull() {
            addCriterion("poll_question_id is not null");
            return (Criteria) this;
        }

        public Criteria andPollQuestionIdEqualTo(Integer value) {
            addCriterion("poll_question_id =", value, "pollQuestionId");
            return (Criteria) this;
        }

        public Criteria andPollQuestionIdNotEqualTo(Integer value) {
            addCriterion("poll_question_id <>", value, "pollQuestionId");
            return (Criteria) this;
        }

        public Criteria andPollQuestionIdGreaterThan(Integer value) {
            addCriterion("poll_question_id >", value, "pollQuestionId");
            return (Criteria) this;
        }

        public Criteria andPollQuestionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("poll_question_id >=", value, "pollQuestionId");
            return (Criteria) this;
        }

        public Criteria andPollQuestionIdLessThan(Integer value) {
            addCriterion("poll_question_id <", value, "pollQuestionId");
            return (Criteria) this;
        }

        public Criteria andPollQuestionIdLessThanOrEqualTo(Integer value) {
            addCriterion("poll_question_id <=", value, "pollQuestionId");
            return (Criteria) this;
        }

        public Criteria andPollQuestionIdIn(List<Integer> values) {
            addCriterion("poll_question_id in", values, "pollQuestionId");
            return (Criteria) this;
        }

        public Criteria andPollQuestionIdNotIn(List<Integer> values) {
            addCriterion("poll_question_id not in", values, "pollQuestionId");
            return (Criteria) this;
        }

        public Criteria andPollQuestionIdBetween(Integer value1, Integer value2) {
            addCriterion("poll_question_id between", value1, value2, "pollQuestionId");
            return (Criteria) this;
        }

        public Criteria andPollQuestionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("poll_question_id not between", value1, value2, "pollQuestionId");
            return (Criteria) this;
        }

        public Criteria andAnswerTextIsNull() {
            addCriterion("answer_text is null");
            return (Criteria) this;
        }

        public Criteria andAnswerTextIsNotNull() {
            addCriterion("answer_text is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerTextEqualTo(String value) {
            addCriterion("answer_text =", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextNotEqualTo(String value) {
            addCriterion("answer_text <>", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextGreaterThan(String value) {
            addCriterion("answer_text >", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextGreaterThanOrEqualTo(String value) {
            addCriterion("answer_text >=", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextLessThan(String value) {
            addCriterion("answer_text <", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextLessThanOrEqualTo(String value) {
            addCriterion("answer_text <=", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextLike(String value) {
            addCriterion("answer_text like", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextNotLike(String value) {
            addCriterion("answer_text not like", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextIn(List<String> values) {
            addCriterion("answer_text in", values, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextNotIn(List<String> values) {
            addCriterion("answer_text not in", values, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextBetween(String value1, String value2) {
            addCriterion("answer_text between", value1, value2, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextNotBetween(String value1, String value2) {
            addCriterion("answer_text not between", value1, value2, "answerText");
            return (Criteria) this;
        }

        public Criteria andPollIdIsNull() {
            addCriterion("poll_id is null");
            return (Criteria) this;
        }

        public Criteria andPollIdIsNotNull() {
            addCriterion("poll_id is not null");
            return (Criteria) this;
        }

        public Criteria andPollIdEqualTo(Integer value) {
            addCriterion("poll_id =", value, "pollId");
            return (Criteria) this;
        }

        public Criteria andPollIdNotEqualTo(Integer value) {
            addCriterion("poll_id <>", value, "pollId");
            return (Criteria) this;
        }

        public Criteria andPollIdGreaterThan(Integer value) {
            addCriterion("poll_id >", value, "pollId");
            return (Criteria) this;
        }

        public Criteria andPollIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("poll_id >=", value, "pollId");
            return (Criteria) this;
        }

        public Criteria andPollIdLessThan(Integer value) {
            addCriterion("poll_id <", value, "pollId");
            return (Criteria) this;
        }

        public Criteria andPollIdLessThanOrEqualTo(Integer value) {
            addCriterion("poll_id <=", value, "pollId");
            return (Criteria) this;
        }

        public Criteria andPollIdIn(List<Integer> values) {
            addCriterion("poll_id in", values, "pollId");
            return (Criteria) this;
        }

        public Criteria andPollIdNotIn(List<Integer> values) {
            addCriterion("poll_id not in", values, "pollId");
            return (Criteria) this;
        }

        public Criteria andPollIdBetween(Integer value1, Integer value2) {
            addCriterion("poll_id between", value1, value2, "pollId");
            return (Criteria) this;
        }

        public Criteria andPollIdNotBetween(Integer value1, Integer value2) {
            addCriterion("poll_id not between", value1, value2, "pollId");
            return (Criteria) this;
        }

        public Criteria andVotesIsNull() {
            addCriterion("votes is null");
            return (Criteria) this;
        }

        public Criteria andVotesIsNotNull() {
            addCriterion("votes is not null");
            return (Criteria) this;
        }

        public Criteria andVotesEqualTo(Integer value) {
            addCriterion("votes =", value, "votes");
            return (Criteria) this;
        }

        public Criteria andVotesNotEqualTo(Integer value) {
            addCriterion("votes <>", value, "votes");
            return (Criteria) this;
        }

        public Criteria andVotesGreaterThan(Integer value) {
            addCriterion("votes >", value, "votes");
            return (Criteria) this;
        }

        public Criteria andVotesGreaterThanOrEqualTo(Integer value) {
            addCriterion("votes >=", value, "votes");
            return (Criteria) this;
        }

        public Criteria andVotesLessThan(Integer value) {
            addCriterion("votes <", value, "votes");
            return (Criteria) this;
        }

        public Criteria andVotesLessThanOrEqualTo(Integer value) {
            addCriterion("votes <=", value, "votes");
            return (Criteria) this;
        }

        public Criteria andVotesIn(List<Integer> values) {
            addCriterion("votes in", values, "votes");
            return (Criteria) this;
        }

        public Criteria andVotesNotIn(List<Integer> values) {
            addCriterion("votes not in", values, "votes");
            return (Criteria) this;
        }

        public Criteria andVotesBetween(Integer value1, Integer value2) {
            addCriterion("votes between", value1, value2, "votes");
            return (Criteria) this;
        }

        public Criteria andVotesNotBetween(Integer value1, Integer value2) {
            addCriterion("votes not between", value1, value2, "votes");
            return (Criteria) this;
        }

        public Criteria andCreatedTsIsNull() {
            addCriterion("created_ts is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTsIsNotNull() {
            addCriterion("created_ts is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTsEqualTo(LocalDateTime value) {
            addCriterion("created_ts =", value, "createdTs");
            return (Criteria) this;
        }

        public Criteria andCreatedTsNotEqualTo(LocalDateTime value) {
            addCriterion("created_ts <>", value, "createdTs");
            return (Criteria) this;
        }

        public Criteria andCreatedTsGreaterThan(LocalDateTime value) {
            addCriterion("created_ts >", value, "createdTs");
            return (Criteria) this;
        }

        public Criteria andCreatedTsGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_ts >=", value, "createdTs");
            return (Criteria) this;
        }

        public Criteria andCreatedTsLessThan(LocalDateTime value) {
            addCriterion("created_ts <", value, "createdTs");
            return (Criteria) this;
        }

        public Criteria andCreatedTsLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_ts <=", value, "createdTs");
            return (Criteria) this;
        }

        public Criteria andCreatedTsIn(List<LocalDateTime> values) {
            addCriterion("created_ts in", values, "createdTs");
            return (Criteria) this;
        }

        public Criteria andCreatedTsNotIn(List<LocalDateTime> values) {
            addCriterion("created_ts not in", values, "createdTs");
            return (Criteria) this;
        }

        public Criteria andCreatedTsBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_ts between", value1, value2, "createdTs");
            return (Criteria) this;
        }

        public Criteria andCreatedTsNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_ts not between", value1, value2, "createdTs");
            return (Criteria) this;
        }

        public Criteria andUpdatedTsIsNull() {
            addCriterion("updated_ts is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTsIsNotNull() {
            addCriterion("updated_ts is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTsEqualTo(LocalDateTime value) {
            addCriterion("updated_ts =", value, "updatedTs");
            return (Criteria) this;
        }

        public Criteria andUpdatedTsNotEqualTo(LocalDateTime value) {
            addCriterion("updated_ts <>", value, "updatedTs");
            return (Criteria) this;
        }

        public Criteria andUpdatedTsGreaterThan(LocalDateTime value) {
            addCriterion("updated_ts >", value, "updatedTs");
            return (Criteria) this;
        }

        public Criteria andUpdatedTsGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("updated_ts >=", value, "updatedTs");
            return (Criteria) this;
        }

        public Criteria andUpdatedTsLessThan(LocalDateTime value) {
            addCriterion("updated_ts <", value, "updatedTs");
            return (Criteria) this;
        }

        public Criteria andUpdatedTsLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("updated_ts <=", value, "updatedTs");
            return (Criteria) this;
        }

        public Criteria andUpdatedTsIn(List<LocalDateTime> values) {
            addCriterion("updated_ts in", values, "updatedTs");
            return (Criteria) this;
        }

        public Criteria andUpdatedTsNotIn(List<LocalDateTime> values) {
            addCriterion("updated_ts not in", values, "updatedTs");
            return (Criteria) this;
        }

        public Criteria andUpdatedTsBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("updated_ts between", value1, value2, "updatedTs");
            return (Criteria) this;
        }

        public Criteria andUpdatedTsNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("updated_ts not between", value1, value2, "updatedTs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated do_not_delete_during_merge Sun Sep 01 00:50:50 EDT 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}