package com.zfgc.zfgbb.dbo;

import java.util.ArrayList;
import java.util.List;
import java.time.LocalDate;
import java.time.LocalDateTime;

public class ThreadDboExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	public ThreadDboExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andThreadIdIsNull() {
			addCriterion("thread_id is null");
			return (Criteria) this;
		}

		public Criteria andThreadIdIsNotNull() {
			addCriterion("thread_id is not null");
			return (Criteria) this;
		}

		public Criteria andThreadIdEqualTo(Integer value) {
			addCriterion("thread_id =", value, "threadId");
			return (Criteria) this;
		}

		public Criteria andThreadIdNotEqualTo(Integer value) {
			addCriterion("thread_id <>", value, "threadId");
			return (Criteria) this;
		}

		public Criteria andThreadIdGreaterThan(Integer value) {
			addCriterion("thread_id >", value, "threadId");
			return (Criteria) this;
		}

		public Criteria andThreadIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("thread_id >=", value, "threadId");
			return (Criteria) this;
		}

		public Criteria andThreadIdLessThan(Integer value) {
			addCriterion("thread_id <", value, "threadId");
			return (Criteria) this;
		}

		public Criteria andThreadIdLessThanOrEqualTo(Integer value) {
			addCriterion("thread_id <=", value, "threadId");
			return (Criteria) this;
		}

		public Criteria andThreadIdIn(List<Integer> values) {
			addCriterion("thread_id in", values, "threadId");
			return (Criteria) this;
		}

		public Criteria andThreadIdNotIn(List<Integer> values) {
			addCriterion("thread_id not in", values, "threadId");
			return (Criteria) this;
		}

		public Criteria andThreadIdBetween(Integer value1, Integer value2) {
			addCriterion("thread_id between", value1, value2, "threadId");
			return (Criteria) this;
		}

		public Criteria andThreadIdNotBetween(Integer value1, Integer value2) {
			addCriterion("thread_id not between", value1, value2, "threadId");
			return (Criteria) this;
		}

		public Criteria andThreadNameIsNull() {
			addCriterion("thread_name is null");
			return (Criteria) this;
		}

		public Criteria andThreadNameIsNotNull() {
			addCriterion("thread_name is not null");
			return (Criteria) this;
		}

		public Criteria andThreadNameEqualTo(String value) {
			addCriterion("thread_name =", value, "threadName");
			return (Criteria) this;
		}

		public Criteria andThreadNameNotEqualTo(String value) {
			addCriterion("thread_name <>", value, "threadName");
			return (Criteria) this;
		}

		public Criteria andThreadNameGreaterThan(String value) {
			addCriterion("thread_name >", value, "threadName");
			return (Criteria) this;
		}

		public Criteria andThreadNameGreaterThanOrEqualTo(String value) {
			addCriterion("thread_name >=", value, "threadName");
			return (Criteria) this;
		}

		public Criteria andThreadNameLessThan(String value) {
			addCriterion("thread_name <", value, "threadName");
			return (Criteria) this;
		}

		public Criteria andThreadNameLessThanOrEqualTo(String value) {
			addCriterion("thread_name <=", value, "threadName");
			return (Criteria) this;
		}

		public Criteria andThreadNameLike(String value) {
			addCriterion("thread_name like", value, "threadName");
			return (Criteria) this;
		}

		public Criteria andThreadNameNotLike(String value) {
			addCriterion("thread_name not like", value, "threadName");
			return (Criteria) this;
		}

		public Criteria andThreadNameIn(List<String> values) {
			addCriterion("thread_name in", values, "threadName");
			return (Criteria) this;
		}

		public Criteria andThreadNameNotIn(List<String> values) {
			addCriterion("thread_name not in", values, "threadName");
			return (Criteria) this;
		}

		public Criteria andThreadNameBetween(String value1, String value2) {
			addCriterion("thread_name between", value1, value2, "threadName");
			return (Criteria) this;
		}

		public Criteria andThreadNameNotBetween(String value1, String value2) {
			addCriterion("thread_name not between", value1, value2, "threadName");
			return (Criteria) this;
		}

		public Criteria andLockedFlagIsNull() {
			addCriterion("locked_flag is null");
			return (Criteria) this;
		}

		public Criteria andLockedFlagIsNotNull() {
			addCriterion("locked_flag is not null");
			return (Criteria) this;
		}

		public Criteria andLockedFlagEqualTo(Boolean value) {
			addCriterion("locked_flag =", value, "lockedFlag");
			return (Criteria) this;
		}

		public Criteria andLockedFlagNotEqualTo(Boolean value) {
			addCriterion("locked_flag <>", value, "lockedFlag");
			return (Criteria) this;
		}

		public Criteria andLockedFlagGreaterThan(Boolean value) {
			addCriterion("locked_flag >", value, "lockedFlag");
			return (Criteria) this;
		}

		public Criteria andLockedFlagGreaterThanOrEqualTo(Boolean value) {
			addCriterion("locked_flag >=", value, "lockedFlag");
			return (Criteria) this;
		}

		public Criteria andLockedFlagLessThan(Boolean value) {
			addCriterion("locked_flag <", value, "lockedFlag");
			return (Criteria) this;
		}

		public Criteria andLockedFlagLessThanOrEqualTo(Boolean value) {
			addCriterion("locked_flag <=", value, "lockedFlag");
			return (Criteria) this;
		}

		public Criteria andLockedFlagIn(List<Boolean> values) {
			addCriterion("locked_flag in", values, "lockedFlag");
			return (Criteria) this;
		}

		public Criteria andLockedFlagNotIn(List<Boolean> values) {
			addCriterion("locked_flag not in", values, "lockedFlag");
			return (Criteria) this;
		}

		public Criteria andLockedFlagBetween(Boolean value1, Boolean value2) {
			addCriterion("locked_flag between", value1, value2, "lockedFlag");
			return (Criteria) this;
		}

		public Criteria andLockedFlagNotBetween(Boolean value1, Boolean value2) {
			addCriterion("locked_flag not between", value1, value2, "lockedFlag");
			return (Criteria) this;
		}

		public Criteria andPinnedFlagIsNull() {
			addCriterion("pinned_flag is null");
			return (Criteria) this;
		}

		public Criteria andPinnedFlagIsNotNull() {
			addCriterion("pinned_flag is not null");
			return (Criteria) this;
		}

		public Criteria andPinnedFlagEqualTo(Boolean value) {
			addCriterion("pinned_flag =", value, "pinnedFlag");
			return (Criteria) this;
		}

		public Criteria andPinnedFlagNotEqualTo(Boolean value) {
			addCriterion("pinned_flag <>", value, "pinnedFlag");
			return (Criteria) this;
		}

		public Criteria andPinnedFlagGreaterThan(Boolean value) {
			addCriterion("pinned_flag >", value, "pinnedFlag");
			return (Criteria) this;
		}

		public Criteria andPinnedFlagGreaterThanOrEqualTo(Boolean value) {
			addCriterion("pinned_flag >=", value, "pinnedFlag");
			return (Criteria) this;
		}

		public Criteria andPinnedFlagLessThan(Boolean value) {
			addCriterion("pinned_flag <", value, "pinnedFlag");
			return (Criteria) this;
		}

		public Criteria andPinnedFlagLessThanOrEqualTo(Boolean value) {
			addCriterion("pinned_flag <=", value, "pinnedFlag");
			return (Criteria) this;
		}

		public Criteria andPinnedFlagIn(List<Boolean> values) {
			addCriterion("pinned_flag in", values, "pinnedFlag");
			return (Criteria) this;
		}

		public Criteria andPinnedFlagNotIn(List<Boolean> values) {
			addCriterion("pinned_flag not in", values, "pinnedFlag");
			return (Criteria) this;
		}

		public Criteria andPinnedFlagBetween(Boolean value1, Boolean value2) {
			addCriterion("pinned_flag between", value1, value2, "pinnedFlag");
			return (Criteria) this;
		}

		public Criteria andPinnedFlagNotBetween(Boolean value1, Boolean value2) {
			addCriterion("pinned_flag not between", value1, value2, "pinnedFlag");
			return (Criteria) this;
		}

		public Criteria andCreatedTsIsNull() {
			addCriterion("created_ts is null");
			return (Criteria) this;
		}

		public Criteria andCreatedTsIsNotNull() {
			addCriterion("created_ts is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedTsEqualTo(LocalDateTime value) {
			addCriterion("created_ts =", value, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsNotEqualTo(LocalDateTime value) {
			addCriterion("created_ts <>", value, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsGreaterThan(LocalDateTime value) {
			addCriterion("created_ts >", value, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsGreaterThanOrEqualTo(LocalDateTime value) {
			addCriterion("created_ts >=", value, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsLessThan(LocalDateTime value) {
			addCriterion("created_ts <", value, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsLessThanOrEqualTo(LocalDateTime value) {
			addCriterion("created_ts <=", value, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsIn(List<LocalDateTime> values) {
			addCriterion("created_ts in", values, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsNotIn(List<LocalDateTime> values) {
			addCriterion("created_ts not in", values, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("created_ts between", value1, value2, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsNotBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("created_ts not between", value1, value2, "createdTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsIsNull() {
			addCriterion("updated_ts is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsIsNotNull() {
			addCriterion("updated_ts is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsEqualTo(LocalDateTime value) {
			addCriterion("updated_ts =", value, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsNotEqualTo(LocalDateTime value) {
			addCriterion("updated_ts <>", value, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsGreaterThan(LocalDateTime value) {
			addCriterion("updated_ts >", value, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsGreaterThanOrEqualTo(LocalDateTime value) {
			addCriterion("updated_ts >=", value, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsLessThan(LocalDateTime value) {
			addCriterion("updated_ts <", value, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsLessThanOrEqualTo(LocalDateTime value) {
			addCriterion("updated_ts <=", value, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsIn(List<LocalDateTime> values) {
			addCriterion("updated_ts in", values, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsNotIn(List<LocalDateTime> values) {
			addCriterion("updated_ts not in", values, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("updated_ts between", value1, value2, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsNotBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("updated_ts not between", value1, value2, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andBoardIdIsNull() {
			addCriterion("board_id is null");
			return (Criteria) this;
		}

		public Criteria andBoardIdIsNotNull() {
			addCriterion("board_id is not null");
			return (Criteria) this;
		}

		public Criteria andBoardIdEqualTo(Integer value) {
			addCriterion("board_id =", value, "boardId");
			return (Criteria) this;
		}

		public Criteria andBoardIdNotEqualTo(Integer value) {
			addCriterion("board_id <>", value, "boardId");
			return (Criteria) this;
		}

		public Criteria andBoardIdGreaterThan(Integer value) {
			addCriterion("board_id >", value, "boardId");
			return (Criteria) this;
		}

		public Criteria andBoardIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("board_id >=", value, "boardId");
			return (Criteria) this;
		}

		public Criteria andBoardIdLessThan(Integer value) {
			addCriterion("board_id <", value, "boardId");
			return (Criteria) this;
		}

		public Criteria andBoardIdLessThanOrEqualTo(Integer value) {
			addCriterion("board_id <=", value, "boardId");
			return (Criteria) this;
		}

		public Criteria andBoardIdIn(List<Integer> values) {
			addCriterion("board_id in", values, "boardId");
			return (Criteria) this;
		}

		public Criteria andBoardIdNotIn(List<Integer> values) {
			addCriterion("board_id not in", values, "boardId");
			return (Criteria) this;
		}

		public Criteria andBoardIdBetween(Integer value1, Integer value2) {
			addCriterion("board_id between", value1, value2, "boardId");
			return (Criteria) this;
		}

		public Criteria andBoardIdNotBetween(Integer value1, Integer value2) {
			addCriterion("board_id not between", value1, value2, "boardId");
			return (Criteria) this;
		}

		public Criteria andCreatedUserIdIsNull() {
			addCriterion("created_user_id is null");
			return (Criteria) this;
		}

		public Criteria andCreatedUserIdIsNotNull() {
			addCriterion("created_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedUserIdEqualTo(Integer value) {
			addCriterion("created_user_id =", value, "createdUserId");
			return (Criteria) this;
		}

		public Criteria andCreatedUserIdNotEqualTo(Integer value) {
			addCriterion("created_user_id <>", value, "createdUserId");
			return (Criteria) this;
		}

		public Criteria andCreatedUserIdGreaterThan(Integer value) {
			addCriterion("created_user_id >", value, "createdUserId");
			return (Criteria) this;
		}

		public Criteria andCreatedUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("created_user_id >=", value, "createdUserId");
			return (Criteria) this;
		}

		public Criteria andCreatedUserIdLessThan(Integer value) {
			addCriterion("created_user_id <", value, "createdUserId");
			return (Criteria) this;
		}

		public Criteria andCreatedUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("created_user_id <=", value, "createdUserId");
			return (Criteria) this;
		}

		public Criteria andCreatedUserIdIn(List<Integer> values) {
			addCriterion("created_user_id in", values, "createdUserId");
			return (Criteria) this;
		}

		public Criteria andCreatedUserIdNotIn(List<Integer> values) {
			addCriterion("created_user_id not in", values, "createdUserId");
			return (Criteria) this;
		}

		public Criteria andCreatedUserIdBetween(Integer value1, Integer value2) {
			addCriterion("created_user_id between", value1, value2, "createdUserId");
			return (Criteria) this;
		}

		public Criteria andCreatedUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("created_user_id not between", value1, value2, "createdUserId");
			return (Criteria) this;
		}

		public Criteria andViewCountIsNull() {
			addCriterion("view_count is null");
			return (Criteria) this;
		}

		public Criteria andViewCountIsNotNull() {
			addCriterion("view_count is not null");
			return (Criteria) this;
		}

		public Criteria andViewCountEqualTo(Integer value) {
			addCriterion("view_count =", value, "viewCount");
			return (Criteria) this;
		}

		public Criteria andViewCountNotEqualTo(Integer value) {
			addCriterion("view_count <>", value, "viewCount");
			return (Criteria) this;
		}

		public Criteria andViewCountGreaterThan(Integer value) {
			addCriterion("view_count >", value, "viewCount");
			return (Criteria) this;
		}

		public Criteria andViewCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("view_count >=", value, "viewCount");
			return (Criteria) this;
		}

		public Criteria andViewCountLessThan(Integer value) {
			addCriterion("view_count <", value, "viewCount");
			return (Criteria) this;
		}

		public Criteria andViewCountLessThanOrEqualTo(Integer value) {
			addCriterion("view_count <=", value, "viewCount");
			return (Criteria) this;
		}

		public Criteria andViewCountIn(List<Integer> values) {
			addCriterion("view_count in", values, "viewCount");
			return (Criteria) this;
		}

		public Criteria andViewCountNotIn(List<Integer> values) {
			addCriterion("view_count not in", values, "viewCount");
			return (Criteria) this;
		}

		public Criteria andViewCountBetween(Integer value1, Integer value2) {
			addCriterion("view_count between", value1, value2, "viewCount");
			return (Criteria) this;
		}

		public Criteria andViewCountNotBetween(Integer value1, Integer value2) {
			addCriterion("view_count not between", value1, value2, "viewCount");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table zfgbb.thread
	 * @mbg.generated  Sun Sep 29 01:06:50 EDT 2024
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zfgbb.thread
     *
     * @mbg.generated do_not_delete_during_merge Wed Feb 23 22:19:44 EST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
    
    protected Integer offset;
    protected Integer limit;

	public Integer getLimit() {
		return limit;
	}

	public void setLimit(Integer limit) {
		this.limit = limit;
	}

	public Integer getOffset() {
		return offset;
	}

	public void setOffset(Integer offset) {
		this.offset = offset;
	}
}