package com.zfgc.zfgbb.dbo;

import java.time.LocalDateTime;

public class KarmaDbo extends AbstractDbo {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.karma.karma_id
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	private Integer karmaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.karma.commenting_user_id
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	private Integer commentingUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.karma.is_positive
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	private Boolean isPositive;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.karma.message_id
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	private Integer messageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.karma.created_ts
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.karma.updated_ts
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	private LocalDateTime updatedTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.karma.migration_id
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	private String migrationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.karma.description
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.karma.karma_id
	 * @return  the value of zfgbb.karma.karma_id
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	public Integer getKarmaId() {
		return karmaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.karma.karma_id
	 * @param karmaId  the value for zfgbb.karma.karma_id
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	public void setKarmaId(Integer karmaId) {
		this.karmaId = karmaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.karma.commenting_user_id
	 * @return  the value of zfgbb.karma.commenting_user_id
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	public Integer getCommentingUserId() {
		return commentingUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.karma.commenting_user_id
	 * @param commentingUserId  the value for zfgbb.karma.commenting_user_id
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	public void setCommentingUserId(Integer commentingUserId) {
		this.commentingUserId = commentingUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.karma.is_positive
	 * @return  the value of zfgbb.karma.is_positive
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	public Boolean getIsPositive() {
		return isPositive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.karma.is_positive
	 * @param isPositive  the value for zfgbb.karma.is_positive
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	public void setIsPositive(Boolean isPositive) {
		this.isPositive = isPositive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.karma.message_id
	 * @return  the value of zfgbb.karma.message_id
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	public Integer getMessageId() {
		return messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.karma.message_id
	 * @param messageId  the value for zfgbb.karma.message_id
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.karma.created_ts
	 * @return  the value of zfgbb.karma.created_ts
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.karma.created_ts
	 * @param createdTs  the value for zfgbb.karma.created_ts
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.karma.updated_ts
	 * @return  the value of zfgbb.karma.updated_ts
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.karma.updated_ts
	 * @param updatedTs  the value for zfgbb.karma.updated_ts
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.karma.migration_id
	 * @return  the value of zfgbb.karma.migration_id
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	public String getMigrationId() {
		return migrationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.karma.migration_id
	 * @param migrationId  the value for zfgbb.karma.migration_id
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	public void setMigrationId(String migrationId) {
		this.migrationId = migrationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.karma.description
	 * @return  the value of zfgbb.karma.description
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.karma.description
	 * @param description  the value for zfgbb.karma.description
	 * @mbg.generated  Sun Mar 29 15:47:10 EDT 2026
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	@Override
	public Integer getPkId() {
		return this.getKarmaId();
	}

	@Override
	public LocalDateTime getUpdatedTime() {
		return this.getUpdatedTs();
	}

	@Override
	public LocalDateTime getCreatedTime() {
		return this.getCreatedTs();
	}
}