package com.zfgc.zfgbb.dbo;

import java.time.LocalDate;
import java.time.LocalDateTime;

public class MessageDbo extends AbstractDbo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.message.message_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	private Integer messageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.message.owner_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	private Integer ownerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.message.thread_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	private Integer threadId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.message.created_ts
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	private Integer postInThread;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.message.message_id
	 * @return  the value of zfgbb.message.message_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public Integer getMessageId() {
		return messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.message.message_id
	 * @param messageId  the value for zfgbb.message.message_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.message.owner_id
	 * @return  the value of zfgbb.message.owner_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public Integer getOwnerId() {
		return ownerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.message.owner_id
	 * @param ownerId  the value for zfgbb.message.owner_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.message.thread_id
	 * @return  the value of zfgbb.message.thread_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public Integer getThreadId() {
		return threadId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.message.thread_id
	 * @param threadId  the value for zfgbb.message.thread_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public void setThreadId(Integer threadId) {
		this.threadId = threadId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.message.post_in_thread
	 * @return  the value of zfgbb.message.post_in_thread
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public Integer getPostInThread() {
		return postInThread;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.message.post_in_thread
	 * @param postInThread  the value for zfgbb.message.post_in_thread
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public void setPostInThread(Integer postInThread) {
		this.postInThread = postInThread;
	}

	@Override
	public Integer getPkId() {
		return messageId;
	}

	@Override
	public LocalDateTime getUpdatedTime() {
		return super.getUpdatedTs();
	}

	@Override
	public LocalDateTime getCreatedTime() {
		return super.getCreatedTs();
	}
}