package com.zfgc.zfgbb.dbo;

import java.time.LocalDateTime;

public class UserKarmaViewDbo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_karma_view.karma_id
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	private Integer karmaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_karma_view.receiving_user_id
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	private Integer receivingUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_karma_view.message_id
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	private Integer messageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_karma_view.description
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_karma_view.is_positive
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	private Boolean isPositive;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_karma_view.karma_given_ts
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	private LocalDateTime karmaGivenTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_karma_view.commenting_user_id
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	private Integer commentingUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_karma_view.thread_id
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	private Integer threadId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_karma_view.commenting_user
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	private String commentingUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_karma_view.karma_id
	 * @return  the value of zfgbb.user_karma_view.karma_id
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	public Integer getKarmaId() {
		return karmaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_karma_view.karma_id
	 * @param karmaId  the value for zfgbb.user_karma_view.karma_id
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	public void setKarmaId(Integer karmaId) {
		this.karmaId = karmaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_karma_view.receiving_user_id
	 * @return  the value of zfgbb.user_karma_view.receiving_user_id
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	public Integer getReceivingUserId() {
		return receivingUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_karma_view.receiving_user_id
	 * @param receivingUserId  the value for zfgbb.user_karma_view.receiving_user_id
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	public void setReceivingUserId(Integer receivingUserId) {
		this.receivingUserId = receivingUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_karma_view.message_id
	 * @return  the value of zfgbb.user_karma_view.message_id
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	public Integer getMessageId() {
		return messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_karma_view.message_id
	 * @param messageId  the value for zfgbb.user_karma_view.message_id
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_karma_view.description
	 * @return  the value of zfgbb.user_karma_view.description
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_karma_view.description
	 * @param description  the value for zfgbb.user_karma_view.description
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_karma_view.is_positive
	 * @return  the value of zfgbb.user_karma_view.is_positive
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	public Boolean getIsPositive() {
		return isPositive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_karma_view.is_positive
	 * @param isPositive  the value for zfgbb.user_karma_view.is_positive
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	public void setIsPositive(Boolean isPositive) {
		this.isPositive = isPositive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_karma_view.karma_given_ts
	 * @return  the value of zfgbb.user_karma_view.karma_given_ts
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	public LocalDateTime getKarmaGivenTs() {
		return karmaGivenTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_karma_view.karma_given_ts
	 * @param karmaGivenTs  the value for zfgbb.user_karma_view.karma_given_ts
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	public void setKarmaGivenTs(LocalDateTime karmaGivenTs) {
		this.karmaGivenTs = karmaGivenTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_karma_view.commenting_user_id
	 * @return  the value of zfgbb.user_karma_view.commenting_user_id
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	public Integer getCommentingUserId() {
		return commentingUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_karma_view.commenting_user_id
	 * @param commentingUserId  the value for zfgbb.user_karma_view.commenting_user_id
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	public void setCommentingUserId(Integer commentingUserId) {
		this.commentingUserId = commentingUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_karma_view.thread_id
	 * @return  the value of zfgbb.user_karma_view.thread_id
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	public Integer getThreadId() {
		return threadId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_karma_view.thread_id
	 * @param threadId  the value for zfgbb.user_karma_view.thread_id
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	public void setThreadId(Integer threadId) {
		this.threadId = threadId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_karma_view.commenting_user
	 * @return  the value of zfgbb.user_karma_view.commenting_user
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	public String getCommentingUser() {
		return commentingUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_karma_view.commenting_user
	 * @param commentingUser  the value for zfgbb.user_karma_view.commenting_user
	 * @mbg.generated  Fri Apr 03 19:37:44 EDT 2026
	 */
	public void setCommentingUser(String commentingUser) {
		this.commentingUser = commentingUser;
	}
}