create table poll (
	poll_id integer not null generated by default as identity primary key,
	poll_question text not null,
	thread_id integer not null references thread,
	created_ts timestamp not null default current_timestamp,
	updated_ts timestamp not null default current_timestamp
);

create table poll_question (
	poll_question_id integer not null generated by default as identity primary key,
	answer_text text not null,
	poll_id integer not null references poll,
	votes integer not null default 0,
	created_ts timestamp not null default current_timestamp,
	updated_ts timestamp not null default current_timestamp
);