ALTER TABLE ZFGBB.MESSAGE ADD COLUMN IF NOT EXISTS BOARD_ID INTEGER;

DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1 FROM pg_constraint
		WHERE conname = 'fk_message_board_id'
		  AND conrelid = 'zfgbb.message'::regclass
	) THEN
		ALTER TABLE ZFGBB.MESSAGE
			ADD CONSTRAINT FK_MESSAGE_BOARD_ID FOREIGN KEY (BOARD_ID) REFERENCES ZFGBB.BOARD (BOARD_ID) NOT VALID;
	END IF;
END $$;

UPDATE ZFGBB.MESSAGE
SET BOARD_ID = THREAD.BOARD_ID
FROM ZFGBB.THREAD
WHERE THREAD.THREAD_ID = MESSAGE.THREAD_ID
  AND MESSAGE.BOARD_ID IS NULL;

CREATE INDEX IF NOT EXISTS IDX_MESSAGE_BOARD_ID_CREATED_TS ON ZFGBB.MESSAGE (BOARD_ID, CREATED_TS DESC);
