alter table zfgbb.avatar alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.avatar alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.bb_code_attribute alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.bb_code_attribute alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.bb_code_attribute_mode alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.bb_code_attribute_mode alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.bb_code_config alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.bb_code_config alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.board alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.board alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.category alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.category alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.contact_types_lookup alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.contact_types_lookup alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.content_resource alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.content_resource alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.content_resource_type alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.content_resource_type alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.email_address alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.email_address alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.file_attachments alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.file_attachments alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.gender_lkup alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.gender_lkup alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.ip_address alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.ip_address alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.message alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.message alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.message_history alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.message_history alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.migrator_attachment_ref_rewrites alter column rewritten_ts type timestamptz using rewritten_ts at time zone 'UTC';
alter table zfgbb.migrator_id_map alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.permission alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.permission alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.permission_group alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.permission_group alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.permission_group_assoc alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.permission_group_assoc alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.poll alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.poll alter column expire_time type timestamptz using expire_time at time zone 'UTC';
alter table zfgbb.poll alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.poll_choice alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.poll_choice alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.system_config alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.system_config alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.thread alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.thread alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.user alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.user alter column locked_until_ts type timestamptz using locked_until_ts at time zone 'UTC';
alter table zfgbb.user alter column password_changed_ts type timestamptz using password_changed_ts at time zone 'UTC';
alter table zfgbb.user alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.user_bio_info alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.user_bio_info alter column date_registered type timestamptz using date_registered at time zone 'UTC';
alter table zfgbb.user_bio_info alter column last_login type timestamptz using last_login at time zone 'UTC';
alter table zfgbb.user_bio_info alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.user_contact_info alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.user_contact_info alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.user_contact_types alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.user_contact_types alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.user_permission_group_assoc alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.user_permission_group_assoc alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.user_poll_choice alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.user_poll_choice alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';
alter table zfgbb.user_refresh_token alter column created_ts type timestamptz using created_ts at time zone 'UTC';
alter table zfgbb.user_refresh_token alter column expires_ts type timestamptz using expires_ts at time zone 'UTC';
alter table zfgbb.user_refresh_token alter column issued_ts type timestamptz using issued_ts at time zone 'UTC';
alter table zfgbb.user_refresh_token alter column updated_ts type timestamptz using updated_ts at time zone 'UTC';

alter table zfgbb.br_user_permission drop constraint fk_br_user_permission_id_user_id;
alter table zfgbb.br_user_permission add constraint fk_br_user_permission_id_user_id FOREIGN KEY (user_id) REFERENCES zfgbb."user"(user_id) MATCH FULL ON DELETE CASCADE;
alter table zfgbb.permission_group_assoc drop constraint permission_group_assoc_permission_group_id_fkey;
alter table zfgbb.permission_group_assoc add constraint permission_group_assoc_permission_group_id_fkey FOREIGN KEY (permission_group_id) REFERENCES zfgbb.permission_group(permission_group_id) ON DELETE CASCADE;
alter table zfgbb.permission_group_assoc drop constraint permission_group_assoc_permission_id_fkey;
alter table zfgbb.permission_group_assoc add constraint permission_group_assoc_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES zfgbb.permission(permission_id) ON DELETE CASCADE;
alter table zfgbb.user_bio_info drop constraint user_bio_info_user_id_fkey;
alter table zfgbb.user_bio_info add constraint user_bio_info_user_id_fkey FOREIGN KEY (user_id) REFERENCES zfgbb."user"(user_id) ON DELETE CASCADE;
alter table zfgbb.user_contact_info drop constraint user_contact_info_user_id_fkey;
alter table zfgbb.user_contact_info add constraint user_contact_info_user_id_fkey FOREIGN KEY (user_id) REFERENCES zfgbb."user"(user_id) ON DELETE CASCADE;
alter table zfgbb.user_contact_types drop constraint user_contact_types_user_id_fkey;
alter table zfgbb.user_contact_types add constraint user_contact_types_user_id_fkey FOREIGN KEY (user_id) REFERENCES zfgbb."user"(user_id) ON DELETE CASCADE;
alter table zfgbb.user_permission_group_assoc drop constraint user_permission_group_assoc_permission_group_id_fkey;
alter table zfgbb.user_permission_group_assoc add constraint user_permission_group_assoc_permission_group_id_fkey FOREIGN KEY (permission_group_id) REFERENCES zfgbb.permission_group(permission_group_id) ON DELETE CASCADE;
alter table zfgbb.user_permission_group_assoc drop constraint user_permission_group_assoc_user_id_fkey;
alter table zfgbb.user_permission_group_assoc add constraint user_permission_group_assoc_user_id_fkey FOREIGN KEY (user_id) REFERENCES zfgbb."user"(user_id) ON DELETE CASCADE;
alter table zfgbb.user_poll_choice drop constraint user_poll_choice_user_id_fkey;
alter table zfgbb.user_poll_choice add constraint user_poll_choice_user_id_fkey FOREIGN KEY (user_id) REFERENCES zfgbb."user"(user_id) ON DELETE CASCADE;
alter table zfgbb.user_refresh_token drop constraint user_refresh_token_user_id_fkey;
alter table zfgbb.user_refresh_token add constraint user_refresh_token_user_id_fkey FOREIGN KEY (user_id) REFERENCES zfgbb."user"(user_id) ON DELETE CASCADE;

alter table zfgbb.permission_group_assoc add column if not exists migration_hash text;
drop index if exists zfgbb.contact_types_lookup_upper_idx;
drop index if exists zfgbb.content_resource_type_upper_idx;

create index if not exists idx_board_category_id ON zfgbb.board USING btree (category_id);
create index if not exists idx_board_parent_board_id ON zfgbb.board USING btree (parent_board_id);
create index if not exists idx_br_user_permission_user_id ON zfgbb.br_user_permission USING btree (user_id);
create index if not exists idx_content_resource_uploaded_user ON zfgbb.content_resource USING btree (uploaded_user_id);
create index if not exists idx_file_attachments_message_id ON zfgbb.file_attachments USING btree (message_id);
create index if not exists idx_message_history_ip_address_id ON zfgbb.message_history USING btree (ip_address_id);
create index if not exists idx_message_history_message_id ON zfgbb.message_history USING btree (message_id);
create index if not exists idx_permission_group_assoc_permission ON zfgbb.permission_group_assoc USING btree (permission_id);
create index if not exists idx_poll_choice_poll_id ON zfgbb.poll_choice USING btree (poll_id);
create index if not exists idx_user_permission_group_assoc_user ON zfgbb.user_permission_group_assoc USING btree (user_id);
create unique index if not exists ux_contact_types_lookup_code ON zfgbb.contact_types_lookup USING btree (upper(contact_type_code));
create unique index if not exists ux_content_resource_type_code ON zfgbb.content_resource_type USING btree (upper(content_code));
create unique index if not exists ux_email_address ON zfgbb.email_address USING btree (email_address);

alter table zfgbb.permission_group_assoc add constraint permission_group_assoc_permission_group_id_permission_id_key unique (permission_group_id, permission_id);
alter table zfgbb.user_permission_group_assoc add constraint user_permission_group_assoc_permission_group_id_user_id_key unique (permission_group_id, user_id);
