create table zfgbb.content_resource_type (
	content_resource_type_id integer not null generated by default as identity primary key,
	content_code text not null,
	description text not null,
	created_ts timestamp not null default current_timestamp,
	updated_ts timestamp not null default current_timestamp
);

create table zfgbb.content_resource (
	content_resource_id integer not null generated by default as identity primary key,
	content_type_id integer not null references zfgbb.content_resource_type,
	uploaded_user_id integer not null references zfgbb.user,
	filename text not null,
	checksum text not null,
	file_ext text not null,
	mime_type text not null,
	created_ts timestamp not null default current_timestamp,
	updated_ts timestamp not null default current_timestamp
);

alter table zfgbb.file_attachments
drop column filename,
drop column checksum,
drop column file_ext,
drop column mime_type,
add column content_resource_id integer not null references zfgbb.content_resource;

alter table zfgbb.permission_group
drop column star_image,
add column star_image integer references zfgbb.content_resource;