create table if not exists zfgbb.quote_strip_run (
	run_id uuid primary key,
	status varchar(16) not null,
	candidate_rows integer not null default 0,
	planned_rows integer not null default 0,
	planned_quotes bigint not null default 0,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	constraint ck_quote_strip_run_status check
		(status in ('PLANNING', 'PLANNED', 'APPLYING', 'APPLIED', 'REVERTING', 'REVERTED',
			'APPLY_PARTIAL', 'REVERT_PARTIAL', 'FAILED'))
);

create table if not exists zfgbb.quote_strip_audit (
	quote_strip_audit_id integer primary key generated by default as identity,
	run_id uuid not null references zfgbb.quote_strip_run(run_id) on delete cascade,
	message_history_id integer references zfgbb.message_history(message_history_id) on delete set null,
	message_id integer,
	before_text text,
	after_text text,
	status varchar(16) not null,
	planned_ts timestamptz,
	applied_ts timestamptz
);

create unique index if not exists un_quote_strip_audit_run_history
	on zfgbb.quote_strip_audit (run_id, message_history_id);

create index if not exists idx_quote_strip_audit_run_status
	on zfgbb.quote_strip_audit (run_id, status);
