package com.zfgc.zfgbb.migrator.smf.mappers;

import com.zfgc.zfgbb.migrator.smf.dbo.SMFAttachmentsDb;
import com.zfgc.zfgbb.migrator.smf.dbo.SMFAttachmentsDbExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SMFAttachmentsDbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    long countByExample(SMFAttachmentsDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    int deleteByExample(SMFAttachmentsDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    int deleteByPrimaryKey(Integer idAttach);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    int insert(SMFAttachmentsDb row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    int insertSelective(SMFAttachmentsDb row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    List<SMFAttachmentsDb> selectByExample(SMFAttachmentsDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    SMFAttachmentsDb selectByPrimaryKey(Integer idAttach);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    int updateByExampleSelective(@Param("row") SMFAttachmentsDb row, @Param("example") SMFAttachmentsDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    int updateByExample(@Param("row") SMFAttachmentsDb row, @Param("example") SMFAttachmentsDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    int updateByPrimaryKeySelective(SMFAttachmentsDb row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    int updateByPrimaryKey(SMFAttachmentsDb row);
}