package com.zfgc.zfgbb.migrator.smf.mappers;

import com.zfgc.zfgbb.migrator.smf.dbo.SMFBoardDb;
import com.zfgc.zfgbb.migrator.smf.dbo.SMFBoardDbExample;
import com.zfgc.zfgbb.migrator.smf.dbo.SMFBoardDbWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SMFBoardDbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1boards
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    long countByExample(SMFBoardDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1boards
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    int deleteByExample(SMFBoardDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1boards
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    int deleteByPrimaryKey(Integer idBoard);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1boards
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    int insert(SMFBoardDbWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1boards
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    int insertSelective(SMFBoardDbWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1boards
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    List<SMFBoardDbWithBLOBs> selectByExampleWithBLOBs(SMFBoardDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1boards
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    List<SMFBoardDb> selectByExample(SMFBoardDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1boards
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    SMFBoardDbWithBLOBs selectByPrimaryKey(Integer idBoard);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1boards
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    int updateByExampleSelective(@Param("row") SMFBoardDbWithBLOBs row, @Param("example") SMFBoardDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1boards
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    int updateByExampleWithBLOBs(@Param("row") SMFBoardDbWithBLOBs row, @Param("example") SMFBoardDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1boards
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    int updateByExample(@Param("row") SMFBoardDb row, @Param("example") SMFBoardDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1boards
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    int updateByPrimaryKeySelective(SMFBoardDbWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1boards
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    int updateByPrimaryKeyWithBLOBs(SMFBoardDbWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1boards
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    int updateByPrimaryKey(SMFBoardDb row);
}