package com.zfgc.zfgbb.migrator.smf.mappers;

import com.zfgc.zfgbb.migrator.smf.dbo.SMFLogKarmaDb;
import com.zfgc.zfgbb.migrator.smf.dbo.SMFLogKarmaDbExample;
import com.zfgc.zfgbb.migrator.smf.dbo.SMFLogKarmaDbWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SMFLogKarmaDbMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	long countByExample(SMFLogKarmaDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	int deleteByExample(SMFLogKarmaDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	int insert(SMFLogKarmaDbWithBLOBs row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	int insertSelective(SMFLogKarmaDbWithBLOBs row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	List<SMFLogKarmaDbWithBLOBs> selectByExampleWithBLOBs(SMFLogKarmaDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	List<SMFLogKarmaDb> selectByExample(SMFLogKarmaDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	int updateByExampleSelective(@Param("row") SMFLogKarmaDbWithBLOBs row,
			@Param("example") SMFLogKarmaDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	int updateByExampleWithBLOBs(@Param("row") SMFLogKarmaDbWithBLOBs row,
			@Param("example") SMFLogKarmaDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	int updateByExample(@Param("row") SMFLogKarmaDb row, @Param("example") SMFLogKarmaDbExample example);
}