package com.zfgc.zfgbb.migrator.smf.mappers;

import com.zfgc.zfgbb.migrator.smf.dbo.SMFMessageDb;
import com.zfgc.zfgbb.migrator.smf.dbo.SMFMessageDbExample;
import com.zfgc.zfgbb.migrator.smf.dbo.SMFMessageDbWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SMFMessageDbMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	long countByExample(SMFMessageDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	int deleteByExample(SMFMessageDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	int deleteByPrimaryKey(Integer idMsg);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	int insert(SMFMessageDbWithBLOBs row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	int insertSelective(SMFMessageDbWithBLOBs row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	List<SMFMessageDbWithBLOBs> selectByExampleWithBLOBs(SMFMessageDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	List<SMFMessageDb> selectByExample(SMFMessageDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	SMFMessageDbWithBLOBs selectByPrimaryKey(Integer idMsg);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	int updateByExampleSelective(@Param("row") SMFMessageDbWithBLOBs row,
			@Param("example") SMFMessageDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	int updateByExampleWithBLOBs(@Param("row") SMFMessageDbWithBLOBs row,
			@Param("example") SMFMessageDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	int updateByExample(@Param("row") SMFMessageDb row, @Param("example") SMFMessageDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	int updateByPrimaryKeySelective(SMFMessageDbWithBLOBs row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	int updateByPrimaryKeyWithBLOBs(SMFMessageDbWithBLOBs row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	int updateByPrimaryKey(SMFMessageDb row);
}