package com.zfgc.zfgbb.migrator.smf.mappers;

import com.zfgc.zfgbb.migrator.smf.dbo.SMFMessageHistoryDb;
import com.zfgc.zfgbb.migrator.smf.dbo.SMFMessageHistoryDbExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SMFMessageHistoryDbMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	long countByExample(SMFMessageHistoryDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	int deleteByExample(SMFMessageHistoryDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	int deleteByPrimaryKey(Integer idEdit);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	int insert(SMFMessageHistoryDb row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	int insertSelective(SMFMessageHistoryDb row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	List<SMFMessageHistoryDb> selectByExampleWithBLOBs(SMFMessageHistoryDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	List<SMFMessageHistoryDb> selectByExample(SMFMessageHistoryDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	SMFMessageHistoryDb selectByPrimaryKey(Integer idEdit);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	int updateByExampleSelective(@Param("row") SMFMessageHistoryDb row,
			@Param("example") SMFMessageHistoryDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	int updateByExampleWithBLOBs(@Param("row") SMFMessageHistoryDb row,
			@Param("example") SMFMessageHistoryDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	int updateByExample(@Param("row") SMFMessageHistoryDb row, @Param("example") SMFMessageHistoryDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	int updateByPrimaryKeySelective(SMFMessageHistoryDb row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	int updateByPrimaryKeyWithBLOBs(SMFMessageHistoryDb row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	int updateByPrimaryKey(SMFMessageHistoryDb row);
}