#!/bin/bash
# Regenerates app/src/main/resources/db/seed/V1__core_dev_data.sql by
# clearing the local zfgbb schema, running the full SMF_INSTALLATION
# migration pipeline against the live SMF docker instance, and dumping
# the resulting tables.
#
# Prerequisites:
#   - docker compose --profile live is up (zfgbb-postgresql-1, zfgbb-smf_mysql-1)
#   - Backend is running on http://localhost:8080
#   - You have site-admin credentials (env: SEED_USER / SEED_PASS, default gm112/derpderp)
#
# Usage:
#   scripts/regenerate-seed.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SEED_FILE="$REPO_ROOT/app/src/main/resources/db/seed/V1__core_dev_data.sql"
DUMP_FILE="$(mktemp)"
trap 'rm -f "$DUMP_FILE"' EXIT

USER="${SEED_USER:-gm112}"
PASS="${SEED_PASS:-derpderp}"
API="${API_BASE_URL:-http://localhost:8080/zfgbb}"
SMF_HOST="${SMF_HOST:-localhost}"
SMF_PORT="${SMF_PORT:-3308}"
SMF_DB="${SMF_DB:-smf}"
SMF_USER="${SMF_USER:-smf}"
SMF_PASS="${SMF_PASS:-smfpw}"
SMF_PREFIX="${SMF_PREFIX:-smf_1}"
SMF_LEGACY_HOST="${SMF_LEGACY_HOST:-localhost:8090}"
APP_BASE_URL="${APP_BASE_URL:-http://localhost:5173}"
PG_CONTAINER="${PG_CONTAINER:-zfgbb-postgresql-1}"
PG_USER="${PG_USER:-zfgbb_user}"
PG_DB="${PG_DB:-zfgc_dev}"

echo "==> Truncating migrator-touched tables (preserving install admin user_id=1)"
docker exec -i "$PG_CONTAINER" psql -U "$PG_USER" -d "$PG_DB" >/dev/null <<'SQL'
truncate zfgbb.content_resource cascade;
truncate
  zfgbb.message_history,
  zfgbb.message,
  zfgbb.thread,
  zfgbb.file_attachments,
  zfgbb.user_poll_choice,
  zfgbb.poll_choice,
  zfgbb.poll,
  zfgbb.karma,
  zfgbb.user_contact_info,
  zfgbb.user_bio_info,
  zfgbb.email_address,
  zfgbb.br_board_permission,
  zfgbb.br_user_permission,
  zfgbb.board,
  zfgbb.category,
  zfgbb.ip_address,
  zfgbb.migrator_id_map,
  zfgbb.migrator_attachment_ref_rewrites
restart identity cascade;
delete from zfgbb."user" where user_id <> 1;
insert into zfgbb.br_user_permission (user_id, user_permission_id) values (1, 1), (1, 10) on conflict do nothing;
SQL

echo "==> Logging in as $USER"
TOKEN=$(curl -fsS -X POST "$API/users/auth/login" \
  -H "Content-Type: application/json" \
  -d "{\"username\":\"$USER\",\"password\":\"$PASS\",\"useTokens\":true}" \
  | grep -oP '"accessToken":"[^"]+' | cut -d'"' -f4)

echo "==> Submitting MIGRATE_SMF_INSTALLATION"
SUBMIT=$(curl -fsS -X POST "$API/system/migrate/jobs" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $TOKEN" \
  -d "{
    \"type\":\"MIGRATE_SMF_INSTALLATION\",
    \"smfHost\":\"$SMF_HOST\", \"smfPort\":$SMF_PORT,
    \"smfDatabase\":\"$SMF_DB\", \"smfUser\":\"$SMF_USER\", \"smfPassword\":\"$SMF_PASS\",
    \"smfTablePrefix\":\"$SMF_PREFIX\",
    \"smfLegacyHost\":\"$SMF_LEGACY_HOST\",
    \"appBaseUrl\":\"$APP_BASE_URL\",
    \"force\":true
  }")
LAST_JID=$(echo "$SUBMIT" | grep -oP '"id":"[^"]+' | tail -1 | cut -d'"' -f4)

echo "==> Polling pipeline (last job id: $LAST_JID)"
for i in $(seq 1 60); do
  sleep 2
  STATE=$(curl -fsS "$API/system/migrate/jobs/$LAST_JID" -H "Authorization: Bearer $TOKEN" \
    | grep -oP '"state":"[^"]+' | cut -d'"' -f4)
  echo "  [$i] $LAST_JID → $STATE"
  case "$STATE" in
    COMPLETED) break ;;
    FAILED|CANCELLED) echo "Pipeline did not complete cleanly"; exit 1 ;;
  esac
done

echo "==> Dumping zfgbb data"
docker exec "$PG_CONTAINER" pg_dump -U "$PG_USER" -d "$PG_DB" -n zfgbb \
  --data-only --column-inserts --no-owner \
  --table=zfgbb.category \
  --table=zfgbb.board \
  --table=zfgbb.br_board_permission \
  --table='zfgbb."user"' \
  --table=zfgbb.email_address \
  --table=zfgbb.user_contact_info \
  --table=zfgbb.user_bio_info \
  --table=zfgbb.br_user_permission \
  --table=zfgbb.ip_address \
  --table=zfgbb.thread \
  --table=zfgbb.message \
  --table=zfgbb.message_history \
  --table=zfgbb.file_attachments \
  --table=zfgbb.poll \
  --table=zfgbb.poll_choice \
  --table=zfgbb.user_poll_choice \
  --table=zfgbb.karma \
  > "$DUMP_FILE" 2>/dev/null

echo "==> Writing $SEED_FILE"
{
  echo "-- Auto-generated by scripts/regenerate-seed.sh"
  echo "-- Source: SMF 2.0.15 fixture migrated via MIGRATE_SMF_INSTALLATION."
  echo "-- Edit the SMF fixture and re-run that script instead of editing this file by hand."
  echo

  grep "^INSERT INTO zfgbb\." "$DUMP_FILE" \
    | grep -v 'INTO zfgbb."user".*VALUES (1,' \
    | grep -v 'INTO zfgbb.br_user_permission.*VALUES ([0-9]\+, [0-9]\+, 1)'

  echo
  echo "-- ===== sequence resets ====="
  cat <<'SQL'
select setval(pg_get_serial_sequence('zfgbb.category', 'category_id'), coalesce((select max(category_id) from zfgbb.category), 0) + 1, false);
select setval(pg_get_serial_sequence('zfgbb.board', 'board_id'), coalesce((select max(board_id) from zfgbb.board), 0) + 1, false);
select setval(pg_get_serial_sequence('zfgbb.thread', 'thread_id'), coalesce((select max(thread_id) from zfgbb.thread), 0) + 1, false);
select setval(pg_get_serial_sequence('zfgbb.message', 'message_id'), coalesce((select max(message_id) from zfgbb.message), 0) + 1, false);
select setval(pg_get_serial_sequence('zfgbb.message_history', 'message_history_id'), coalesce((select max(message_history_id) from zfgbb.message_history), 0) + 1, false);
select setval(pg_get_serial_sequence('zfgbb."user"', 'user_id'), coalesce((select max(user_id) from zfgbb."user"), 0) + 1, false);
select setval(pg_get_serial_sequence('zfgbb.email_address', 'email_address_id'), coalesce((select max(email_address_id) from zfgbb.email_address), 0) + 1, false);
select setval(pg_get_serial_sequence('zfgbb.ip_address', 'ip_address_id'), coalesce((select max(ip_address_id) from zfgbb.ip_address), 0) + 1, false);
select setval(pg_get_serial_sequence('zfgbb.file_attachments', 'file_attachment_id'), coalesce((select max(file_attachment_id) from zfgbb.file_attachments), 0) + 1, false);
select setval(pg_get_serial_sequence('zfgbb.poll', 'poll_id'), coalesce((select max(poll_id) from zfgbb.poll), 0) + 1, false);
select setval(pg_get_serial_sequence('zfgbb.poll_choice', 'poll_choice_id'), coalesce((select max(poll_choice_id) from zfgbb.poll_choice), 0) + 1, false);
select setval(pg_get_serial_sequence('zfgbb.br_board_permission', 'br_board_permission_id'), coalesce((select max(br_board_permission_id) from zfgbb.br_board_permission), 0) + 1, false);
select setval(pg_get_serial_sequence('zfgbb.br_user_permission', 'br_user_permission_id'), coalesce((select max(br_user_permission_id) from zfgbb.br_user_permission), 0) + 1, false);
SQL
} > "$SEED_FILE"

echo "==> Done. $SEED_FILE written ($(wc -l < "$SEED_FILE") lines)"
