package com.zfgc.zfgbb.migrator.smf.dbo;

import java.util.ArrayList;
import java.util.List;

public class SMFAttachmentsDbExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public SMFAttachmentsDbExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdAttachIsNull() {
            addCriterion("id_attach is null");
            return (Criteria) this;
        }

        public Criteria andIdAttachIsNotNull() {
            addCriterion("id_attach is not null");
            return (Criteria) this;
        }

        public Criteria andIdAttachEqualTo(Integer value) {
            addCriterion("id_attach =", value, "idAttach");
            return (Criteria) this;
        }

        public Criteria andIdAttachNotEqualTo(Integer value) {
            addCriterion("id_attach <>", value, "idAttach");
            return (Criteria) this;
        }

        public Criteria andIdAttachGreaterThan(Integer value) {
            addCriterion("id_attach >", value, "idAttach");
            return (Criteria) this;
        }

        public Criteria andIdAttachGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_attach >=", value, "idAttach");
            return (Criteria) this;
        }

        public Criteria andIdAttachLessThan(Integer value) {
            addCriterion("id_attach <", value, "idAttach");
            return (Criteria) this;
        }

        public Criteria andIdAttachLessThanOrEqualTo(Integer value) {
            addCriterion("id_attach <=", value, "idAttach");
            return (Criteria) this;
        }

        public Criteria andIdAttachIn(List<Integer> values) {
            addCriterion("id_attach in", values, "idAttach");
            return (Criteria) this;
        }

        public Criteria andIdAttachNotIn(List<Integer> values) {
            addCriterion("id_attach not in", values, "idAttach");
            return (Criteria) this;
        }

        public Criteria andIdAttachBetween(Integer value1, Integer value2) {
            addCriterion("id_attach between", value1, value2, "idAttach");
            return (Criteria) this;
        }

        public Criteria andIdAttachNotBetween(Integer value1, Integer value2) {
            addCriterion("id_attach not between", value1, value2, "idAttach");
            return (Criteria) this;
        }

        public Criteria andIdThumbIsNull() {
            addCriterion("id_thumb is null");
            return (Criteria) this;
        }

        public Criteria andIdThumbIsNotNull() {
            addCriterion("id_thumb is not null");
            return (Criteria) this;
        }

        public Criteria andIdThumbEqualTo(Integer value) {
            addCriterion("id_thumb =", value, "idThumb");
            return (Criteria) this;
        }

        public Criteria andIdThumbNotEqualTo(Integer value) {
            addCriterion("id_thumb <>", value, "idThumb");
            return (Criteria) this;
        }

        public Criteria andIdThumbGreaterThan(Integer value) {
            addCriterion("id_thumb >", value, "idThumb");
            return (Criteria) this;
        }

        public Criteria andIdThumbGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_thumb >=", value, "idThumb");
            return (Criteria) this;
        }

        public Criteria andIdThumbLessThan(Integer value) {
            addCriterion("id_thumb <", value, "idThumb");
            return (Criteria) this;
        }

        public Criteria andIdThumbLessThanOrEqualTo(Integer value) {
            addCriterion("id_thumb <=", value, "idThumb");
            return (Criteria) this;
        }

        public Criteria andIdThumbIn(List<Integer> values) {
            addCriterion("id_thumb in", values, "idThumb");
            return (Criteria) this;
        }

        public Criteria andIdThumbNotIn(List<Integer> values) {
            addCriterion("id_thumb not in", values, "idThumb");
            return (Criteria) this;
        }

        public Criteria andIdThumbBetween(Integer value1, Integer value2) {
            addCriterion("id_thumb between", value1, value2, "idThumb");
            return (Criteria) this;
        }

        public Criteria andIdThumbNotBetween(Integer value1, Integer value2) {
            addCriterion("id_thumb not between", value1, value2, "idThumb");
            return (Criteria) this;
        }

        public Criteria andIdMsgIsNull() {
            addCriterion("id_msg is null");
            return (Criteria) this;
        }

        public Criteria andIdMsgIsNotNull() {
            addCriterion("id_msg is not null");
            return (Criteria) this;
        }

        public Criteria andIdMsgEqualTo(Integer value) {
            addCriterion("id_msg =", value, "idMsg");
            return (Criteria) this;
        }

        public Criteria andIdMsgNotEqualTo(Integer value) {
            addCriterion("id_msg <>", value, "idMsg");
            return (Criteria) this;
        }

        public Criteria andIdMsgGreaterThan(Integer value) {
            addCriterion("id_msg >", value, "idMsg");
            return (Criteria) this;
        }

        public Criteria andIdMsgGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_msg >=", value, "idMsg");
            return (Criteria) this;
        }

        public Criteria andIdMsgLessThan(Integer value) {
            addCriterion("id_msg <", value, "idMsg");
            return (Criteria) this;
        }

        public Criteria andIdMsgLessThanOrEqualTo(Integer value) {
            addCriterion("id_msg <=", value, "idMsg");
            return (Criteria) this;
        }

        public Criteria andIdMsgIn(List<Integer> values) {
            addCriterion("id_msg in", values, "idMsg");
            return (Criteria) this;
        }

        public Criteria andIdMsgNotIn(List<Integer> values) {
            addCriterion("id_msg not in", values, "idMsg");
            return (Criteria) this;
        }

        public Criteria andIdMsgBetween(Integer value1, Integer value2) {
            addCriterion("id_msg between", value1, value2, "idMsg");
            return (Criteria) this;
        }

        public Criteria andIdMsgNotBetween(Integer value1, Integer value2) {
            addCriterion("id_msg not between", value1, value2, "idMsg");
            return (Criteria) this;
        }

        public Criteria andIdMemberIsNull() {
            addCriterion("id_member is null");
            return (Criteria) this;
        }

        public Criteria andIdMemberIsNotNull() {
            addCriterion("id_member is not null");
            return (Criteria) this;
        }

        public Criteria andIdMemberEqualTo(Integer value) {
            addCriterion("id_member =", value, "idMember");
            return (Criteria) this;
        }

        public Criteria andIdMemberNotEqualTo(Integer value) {
            addCriterion("id_member <>", value, "idMember");
            return (Criteria) this;
        }

        public Criteria andIdMemberGreaterThan(Integer value) {
            addCriterion("id_member >", value, "idMember");
            return (Criteria) this;
        }

        public Criteria andIdMemberGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_member >=", value, "idMember");
            return (Criteria) this;
        }

        public Criteria andIdMemberLessThan(Integer value) {
            addCriterion("id_member <", value, "idMember");
            return (Criteria) this;
        }

        public Criteria andIdMemberLessThanOrEqualTo(Integer value) {
            addCriterion("id_member <=", value, "idMember");
            return (Criteria) this;
        }

        public Criteria andIdMemberIn(List<Integer> values) {
            addCriterion("id_member in", values, "idMember");
            return (Criteria) this;
        }

        public Criteria andIdMemberNotIn(List<Integer> values) {
            addCriterion("id_member not in", values, "idMember");
            return (Criteria) this;
        }

        public Criteria andIdMemberBetween(Integer value1, Integer value2) {
            addCriterion("id_member between", value1, value2, "idMember");
            return (Criteria) this;
        }

        public Criteria andIdMemberNotBetween(Integer value1, Integer value2) {
            addCriterion("id_member not between", value1, value2, "idMember");
            return (Criteria) this;
        }

        public Criteria andAttachmentTypeIsNull() {
            addCriterion("attachment_type is null");
            return (Criteria) this;
        }

        public Criteria andAttachmentTypeIsNotNull() {
            addCriterion("attachment_type is not null");
            return (Criteria) this;
        }

        public Criteria andAttachmentTypeEqualTo(Byte value) {
            addCriterion("attachment_type =", value, "attachmentType");
            return (Criteria) this;
        }

        public Criteria andAttachmentTypeNotEqualTo(Byte value) {
            addCriterion("attachment_type <>", value, "attachmentType");
            return (Criteria) this;
        }

        public Criteria andAttachmentTypeGreaterThan(Byte value) {
            addCriterion("attachment_type >", value, "attachmentType");
            return (Criteria) this;
        }

        public Criteria andAttachmentTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("attachment_type >=", value, "attachmentType");
            return (Criteria) this;
        }

        public Criteria andAttachmentTypeLessThan(Byte value) {
            addCriterion("attachment_type <", value, "attachmentType");
            return (Criteria) this;
        }

        public Criteria andAttachmentTypeLessThanOrEqualTo(Byte value) {
            addCriterion("attachment_type <=", value, "attachmentType");
            return (Criteria) this;
        }

        public Criteria andAttachmentTypeIn(List<Byte> values) {
            addCriterion("attachment_type in", values, "attachmentType");
            return (Criteria) this;
        }

        public Criteria andAttachmentTypeNotIn(List<Byte> values) {
            addCriterion("attachment_type not in", values, "attachmentType");
            return (Criteria) this;
        }

        public Criteria andAttachmentTypeBetween(Byte value1, Byte value2) {
            addCriterion("attachment_type between", value1, value2, "attachmentType");
            return (Criteria) this;
        }

        public Criteria andAttachmentTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("attachment_type not between", value1, value2, "attachmentType");
            return (Criteria) this;
        }

        public Criteria andFilenameIsNull() {
            addCriterion("filename is null");
            return (Criteria) this;
        }

        public Criteria andFilenameIsNotNull() {
            addCriterion("filename is not null");
            return (Criteria) this;
        }

        public Criteria andFilenameEqualTo(String value) {
            addCriterion("filename =", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotEqualTo(String value) {
            addCriterion("filename <>", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameGreaterThan(String value) {
            addCriterion("filename >", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameGreaterThanOrEqualTo(String value) {
            addCriterion("filename >=", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLessThan(String value) {
            addCriterion("filename <", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLessThanOrEqualTo(String value) {
            addCriterion("filename <=", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLike(String value) {
            addCriterion("filename like", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotLike(String value) {
            addCriterion("filename not like", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameIn(List<String> values) {
            addCriterion("filename in", values, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotIn(List<String> values) {
            addCriterion("filename not in", values, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameBetween(String value1, String value2) {
            addCriterion("filename between", value1, value2, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotBetween(String value1, String value2) {
            addCriterion("filename not between", value1, value2, "filename");
            return (Criteria) this;
        }

        public Criteria andSizeIsNull() {
            addCriterion("size is null");
            return (Criteria) this;
        }

        public Criteria andSizeIsNotNull() {
            addCriterion("size is not null");
            return (Criteria) this;
        }

        public Criteria andSizeEqualTo(Integer value) {
            addCriterion("size =", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotEqualTo(Integer value) {
            addCriterion("size <>", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThan(Integer value) {
            addCriterion("size >", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("size >=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThan(Integer value) {
            addCriterion("size <", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThanOrEqualTo(Integer value) {
            addCriterion("size <=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeIn(List<Integer> values) {
            addCriterion("size in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotIn(List<Integer> values) {
            addCriterion("size not in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeBetween(Integer value1, Integer value2) {
            addCriterion("size between", value1, value2, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotBetween(Integer value1, Integer value2) {
            addCriterion("size not between", value1, value2, "size");
            return (Criteria) this;
        }

        public Criteria andDownloadsIsNull() {
            addCriterion("downloads is null");
            return (Criteria) this;
        }

        public Criteria andDownloadsIsNotNull() {
            addCriterion("downloads is not null");
            return (Criteria) this;
        }

        public Criteria andDownloadsEqualTo(Integer value) {
            addCriterion("downloads =", value, "downloads");
            return (Criteria) this;
        }

        public Criteria andDownloadsNotEqualTo(Integer value) {
            addCriterion("downloads <>", value, "downloads");
            return (Criteria) this;
        }

        public Criteria andDownloadsGreaterThan(Integer value) {
            addCriterion("downloads >", value, "downloads");
            return (Criteria) this;
        }

        public Criteria andDownloadsGreaterThanOrEqualTo(Integer value) {
            addCriterion("downloads >=", value, "downloads");
            return (Criteria) this;
        }

        public Criteria andDownloadsLessThan(Integer value) {
            addCriterion("downloads <", value, "downloads");
            return (Criteria) this;
        }

        public Criteria andDownloadsLessThanOrEqualTo(Integer value) {
            addCriterion("downloads <=", value, "downloads");
            return (Criteria) this;
        }

        public Criteria andDownloadsIn(List<Integer> values) {
            addCriterion("downloads in", values, "downloads");
            return (Criteria) this;
        }

        public Criteria andDownloadsNotIn(List<Integer> values) {
            addCriterion("downloads not in", values, "downloads");
            return (Criteria) this;
        }

        public Criteria andDownloadsBetween(Integer value1, Integer value2) {
            addCriterion("downloads between", value1, value2, "downloads");
            return (Criteria) this;
        }

        public Criteria andDownloadsNotBetween(Integer value1, Integer value2) {
            addCriterion("downloads not between", value1, value2, "downloads");
            return (Criteria) this;
        }

        public Criteria andWidthIsNull() {
            addCriterion("width is null");
            return (Criteria) this;
        }

        public Criteria andWidthIsNotNull() {
            addCriterion("width is not null");
            return (Criteria) this;
        }

        public Criteria andWidthEqualTo(Integer value) {
            addCriterion("width =", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotEqualTo(Integer value) {
            addCriterion("width <>", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThan(Integer value) {
            addCriterion("width >", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThanOrEqualTo(Integer value) {
            addCriterion("width >=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThan(Integer value) {
            addCriterion("width <", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThanOrEqualTo(Integer value) {
            addCriterion("width <=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthIn(List<Integer> values) {
            addCriterion("width in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotIn(List<Integer> values) {
            addCriterion("width not in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthBetween(Integer value1, Integer value2) {
            addCriterion("width between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotBetween(Integer value1, Integer value2) {
            addCriterion("width not between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("height is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("height is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(Integer value) {
            addCriterion("height =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(Integer value) {
            addCriterion("height <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(Integer value) {
            addCriterion("height >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("height >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(Integer value) {
            addCriterion("height <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(Integer value) {
            addCriterion("height <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<Integer> values) {
            addCriterion("height in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<Integer> values) {
            addCriterion("height not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(Integer value1, Integer value2) {
            addCriterion("height between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(Integer value1, Integer value2) {
            addCriterion("height not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andFileHashIsNull() {
            addCriterion("file_hash is null");
            return (Criteria) this;
        }

        public Criteria andFileHashIsNotNull() {
            addCriterion("file_hash is not null");
            return (Criteria) this;
        }

        public Criteria andFileHashEqualTo(String value) {
            addCriterion("file_hash =", value, "fileHash");
            return (Criteria) this;
        }

        public Criteria andFileHashNotEqualTo(String value) {
            addCriterion("file_hash <>", value, "fileHash");
            return (Criteria) this;
        }

        public Criteria andFileHashGreaterThan(String value) {
            addCriterion("file_hash >", value, "fileHash");
            return (Criteria) this;
        }

        public Criteria andFileHashGreaterThanOrEqualTo(String value) {
            addCriterion("file_hash >=", value, "fileHash");
            return (Criteria) this;
        }

        public Criteria andFileHashLessThan(String value) {
            addCriterion("file_hash <", value, "fileHash");
            return (Criteria) this;
        }

        public Criteria andFileHashLessThanOrEqualTo(String value) {
            addCriterion("file_hash <=", value, "fileHash");
            return (Criteria) this;
        }

        public Criteria andFileHashLike(String value) {
            addCriterion("file_hash like", value, "fileHash");
            return (Criteria) this;
        }

        public Criteria andFileHashNotLike(String value) {
            addCriterion("file_hash not like", value, "fileHash");
            return (Criteria) this;
        }

        public Criteria andFileHashIn(List<String> values) {
            addCriterion("file_hash in", values, "fileHash");
            return (Criteria) this;
        }

        public Criteria andFileHashNotIn(List<String> values) {
            addCriterion("file_hash not in", values, "fileHash");
            return (Criteria) this;
        }

        public Criteria andFileHashBetween(String value1, String value2) {
            addCriterion("file_hash between", value1, value2, "fileHash");
            return (Criteria) this;
        }

        public Criteria andFileHashNotBetween(String value1, String value2) {
            addCriterion("file_hash not between", value1, value2, "fileHash");
            return (Criteria) this;
        }

        public Criteria andFileextIsNull() {
            addCriterion("fileext is null");
            return (Criteria) this;
        }

        public Criteria andFileextIsNotNull() {
            addCriterion("fileext is not null");
            return (Criteria) this;
        }

        public Criteria andFileextEqualTo(String value) {
            addCriterion("fileext =", value, "fileext");
            return (Criteria) this;
        }

        public Criteria andFileextNotEqualTo(String value) {
            addCriterion("fileext <>", value, "fileext");
            return (Criteria) this;
        }

        public Criteria andFileextGreaterThan(String value) {
            addCriterion("fileext >", value, "fileext");
            return (Criteria) this;
        }

        public Criteria andFileextGreaterThanOrEqualTo(String value) {
            addCriterion("fileext >=", value, "fileext");
            return (Criteria) this;
        }

        public Criteria andFileextLessThan(String value) {
            addCriterion("fileext <", value, "fileext");
            return (Criteria) this;
        }

        public Criteria andFileextLessThanOrEqualTo(String value) {
            addCriterion("fileext <=", value, "fileext");
            return (Criteria) this;
        }

        public Criteria andFileextLike(String value) {
            addCriterion("fileext like", value, "fileext");
            return (Criteria) this;
        }

        public Criteria andFileextNotLike(String value) {
            addCriterion("fileext not like", value, "fileext");
            return (Criteria) this;
        }

        public Criteria andFileextIn(List<String> values) {
            addCriterion("fileext in", values, "fileext");
            return (Criteria) this;
        }

        public Criteria andFileextNotIn(List<String> values) {
            addCriterion("fileext not in", values, "fileext");
            return (Criteria) this;
        }

        public Criteria andFileextBetween(String value1, String value2) {
            addCriterion("fileext between", value1, value2, "fileext");
            return (Criteria) this;
        }

        public Criteria andFileextNotBetween(String value1, String value2) {
            addCriterion("fileext not between", value1, value2, "fileext");
            return (Criteria) this;
        }

        public Criteria andMimeTypeIsNull() {
            addCriterion("mime_type is null");
            return (Criteria) this;
        }

        public Criteria andMimeTypeIsNotNull() {
            addCriterion("mime_type is not null");
            return (Criteria) this;
        }

        public Criteria andMimeTypeEqualTo(String value) {
            addCriterion("mime_type =", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeNotEqualTo(String value) {
            addCriterion("mime_type <>", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeGreaterThan(String value) {
            addCriterion("mime_type >", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("mime_type >=", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeLessThan(String value) {
            addCriterion("mime_type <", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeLessThanOrEqualTo(String value) {
            addCriterion("mime_type <=", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeLike(String value) {
            addCriterion("mime_type like", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeNotLike(String value) {
            addCriterion("mime_type not like", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeIn(List<String> values) {
            addCriterion("mime_type in", values, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeNotIn(List<String> values) {
            addCriterion("mime_type not in", values, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeBetween(String value1, String value2) {
            addCriterion("mime_type between", value1, value2, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeNotBetween(String value1, String value2) {
            addCriterion("mime_type not between", value1, value2, "mimeType");
            return (Criteria) this;
        }

        public Criteria andIdFolderIsNull() {
            addCriterion("id_folder is null");
            return (Criteria) this;
        }

        public Criteria andIdFolderIsNotNull() {
            addCriterion("id_folder is not null");
            return (Criteria) this;
        }

        public Criteria andIdFolderEqualTo(Byte value) {
            addCriterion("id_folder =", value, "idFolder");
            return (Criteria) this;
        }

        public Criteria andIdFolderNotEqualTo(Byte value) {
            addCriterion("id_folder <>", value, "idFolder");
            return (Criteria) this;
        }

        public Criteria andIdFolderGreaterThan(Byte value) {
            addCriterion("id_folder >", value, "idFolder");
            return (Criteria) this;
        }

        public Criteria andIdFolderGreaterThanOrEqualTo(Byte value) {
            addCriterion("id_folder >=", value, "idFolder");
            return (Criteria) this;
        }

        public Criteria andIdFolderLessThan(Byte value) {
            addCriterion("id_folder <", value, "idFolder");
            return (Criteria) this;
        }

        public Criteria andIdFolderLessThanOrEqualTo(Byte value) {
            addCriterion("id_folder <=", value, "idFolder");
            return (Criteria) this;
        }

        public Criteria andIdFolderIn(List<Byte> values) {
            addCriterion("id_folder in", values, "idFolder");
            return (Criteria) this;
        }

        public Criteria andIdFolderNotIn(List<Byte> values) {
            addCriterion("id_folder not in", values, "idFolder");
            return (Criteria) this;
        }

        public Criteria andIdFolderBetween(Byte value1, Byte value2) {
            addCriterion("id_folder between", value1, value2, "idFolder");
            return (Criteria) this;
        }

        public Criteria andIdFolderNotBetween(Byte value1, Byte value2) {
            addCriterion("id_folder not between", value1, value2, "idFolder");
            return (Criteria) this;
        }

        public Criteria andApprovedIsNull() {
            addCriterion("approved is null");
            return (Criteria) this;
        }

        public Criteria andApprovedIsNotNull() {
            addCriterion("approved is not null");
            return (Criteria) this;
        }

        public Criteria andApprovedEqualTo(Byte value) {
            addCriterion("approved =", value, "approved");
            return (Criteria) this;
        }

        public Criteria andApprovedNotEqualTo(Byte value) {
            addCriterion("approved <>", value, "approved");
            return (Criteria) this;
        }

        public Criteria andApprovedGreaterThan(Byte value) {
            addCriterion("approved >", value, "approved");
            return (Criteria) this;
        }

        public Criteria andApprovedGreaterThanOrEqualTo(Byte value) {
            addCriterion("approved >=", value, "approved");
            return (Criteria) this;
        }

        public Criteria andApprovedLessThan(Byte value) {
            addCriterion("approved <", value, "approved");
            return (Criteria) this;
        }

        public Criteria andApprovedLessThanOrEqualTo(Byte value) {
            addCriterion("approved <=", value, "approved");
            return (Criteria) this;
        }

        public Criteria andApprovedIn(List<Byte> values) {
            addCriterion("approved in", values, "approved");
            return (Criteria) this;
        }

        public Criteria andApprovedNotIn(List<Byte> values) {
            addCriterion("approved not in", values, "approved");
            return (Criteria) this;
        }

        public Criteria andApprovedBetween(Byte value1, Byte value2) {
            addCriterion("approved between", value1, value2, "approved");
            return (Criteria) this;
        }

        public Criteria andApprovedNotBetween(Byte value1, Byte value2) {
            addCriterion("approved not between", value1, value2, "approved");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table smf_1attachments
     *
     * @mbg.generated do_not_delete_during_merge Sun May 18 11:44:38 EDT 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table smf_1attachments
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}