package com.zfgc.zfgbb.migrator.smf.dbo;

public class SMFAttachmentsDb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1attachments.id_attach
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    private Integer idAttach;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1attachments.id_thumb
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    private Integer idThumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1attachments.id_msg
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    private Integer idMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1attachments.id_member
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    private Integer idMember;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1attachments.attachment_type
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    private Byte attachmentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1attachments.filename
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1attachments.size
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    private Integer size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1attachments.downloads
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    private Integer downloads;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1attachments.width
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    private Integer width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1attachments.height
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    private Integer height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1attachments.file_hash
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    private String fileHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1attachments.fileext
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    private String fileext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1attachments.mime_type
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    private String mimeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1attachments.id_folder
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    private Byte idFolder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1attachments.approved
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    private Byte approved;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1attachments.id_attach
     *
     * @return the value of smf_1attachments.id_attach
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public Integer getIdAttach() {
        return idAttach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1attachments.id_attach
     *
     * @param idAttach the value for smf_1attachments.id_attach
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public void setIdAttach(Integer idAttach) {
        this.idAttach = idAttach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1attachments.id_thumb
     *
     * @return the value of smf_1attachments.id_thumb
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public Integer getIdThumb() {
        return idThumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1attachments.id_thumb
     *
     * @param idThumb the value for smf_1attachments.id_thumb
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public void setIdThumb(Integer idThumb) {
        this.idThumb = idThumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1attachments.id_msg
     *
     * @return the value of smf_1attachments.id_msg
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public Integer getIdMsg() {
        return idMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1attachments.id_msg
     *
     * @param idMsg the value for smf_1attachments.id_msg
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public void setIdMsg(Integer idMsg) {
        this.idMsg = idMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1attachments.id_member
     *
     * @return the value of smf_1attachments.id_member
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public Integer getIdMember() {
        return idMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1attachments.id_member
     *
     * @param idMember the value for smf_1attachments.id_member
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public void setIdMember(Integer idMember) {
        this.idMember = idMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1attachments.attachment_type
     *
     * @return the value of smf_1attachments.attachment_type
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public Byte getAttachmentType() {
        return attachmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1attachments.attachment_type
     *
     * @param attachmentType the value for smf_1attachments.attachment_type
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public void setAttachmentType(Byte attachmentType) {
        this.attachmentType = attachmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1attachments.filename
     *
     * @return the value of smf_1attachments.filename
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1attachments.filename
     *
     * @param filename the value for smf_1attachments.filename
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1attachments.size
     *
     * @return the value of smf_1attachments.size
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1attachments.size
     *
     * @param size the value for smf_1attachments.size
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1attachments.downloads
     *
     * @return the value of smf_1attachments.downloads
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public Integer getDownloads() {
        return downloads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1attachments.downloads
     *
     * @param downloads the value for smf_1attachments.downloads
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public void setDownloads(Integer downloads) {
        this.downloads = downloads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1attachments.width
     *
     * @return the value of smf_1attachments.width
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1attachments.width
     *
     * @param width the value for smf_1attachments.width
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1attachments.height
     *
     * @return the value of smf_1attachments.height
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1attachments.height
     *
     * @param height the value for smf_1attachments.height
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1attachments.file_hash
     *
     * @return the value of smf_1attachments.file_hash
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public String getFileHash() {
        return fileHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1attachments.file_hash
     *
     * @param fileHash the value for smf_1attachments.file_hash
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public void setFileHash(String fileHash) {
        this.fileHash = fileHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1attachments.fileext
     *
     * @return the value of smf_1attachments.fileext
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public String getFileext() {
        return fileext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1attachments.fileext
     *
     * @param fileext the value for smf_1attachments.fileext
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public void setFileext(String fileext) {
        this.fileext = fileext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1attachments.mime_type
     *
     * @return the value of smf_1attachments.mime_type
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public String getMimeType() {
        return mimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1attachments.mime_type
     *
     * @param mimeType the value for smf_1attachments.mime_type
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1attachments.id_folder
     *
     * @return the value of smf_1attachments.id_folder
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public Byte getIdFolder() {
        return idFolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1attachments.id_folder
     *
     * @param idFolder the value for smf_1attachments.id_folder
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public void setIdFolder(Byte idFolder) {
        this.idFolder = idFolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1attachments.approved
     *
     * @return the value of smf_1attachments.approved
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public Byte getApproved() {
        return approved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1attachments.approved
     *
     * @param approved the value for smf_1attachments.approved
     *
     * @mbg.generated Sun May 18 11:44:38 EDT 2025
     */
    public void setApproved(Byte approved) {
        this.approved = approved;
    }
}