package com.zfgc.zfgbb.migrator.smf.dbo;

public class SMFBoardDbWithBLOBs extends SMFBoardDb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.description
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.redirect_target
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private String redirectTarget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.redirect_url
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private String redirectUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.description
     *
     * @return the value of smf_1boards.description
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.description
     *
     * @param description the value for smf_1boards.description
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.redirect_target
     *
     * @return the value of smf_1boards.redirect_target
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public String getRedirectTarget() {
        return redirectTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.redirect_target
     *
     * @param redirectTarget the value for smf_1boards.redirect_target
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setRedirectTarget(String redirectTarget) {
        this.redirectTarget = redirectTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.redirect_url
     *
     * @return the value of smf_1boards.redirect_url
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public String getRedirectUrl() {
        return redirectUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.redirect_url
     *
     * @param redirectUrl the value for smf_1boards.redirect_url
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setRedirectUrl(String redirectUrl) {
        this.redirectUrl = redirectUrl;
    }
}