package com.zfgc.zfgbb.migrator.smf.dbo;

public class SMFBoardDb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.id_board
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private Integer idBoard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.id_cat
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private Integer idCat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.child_level
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private Byte childLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.id_parent
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private Integer idParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.board_order
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private Short boardOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.id_last_msg
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private Integer idLastMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.id_msg_updated
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private Integer idMsgUpdated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.member_groups
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private String memberGroups;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.id_profile
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private Short idProfile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.name
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.num_topics
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private Integer numTopics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.num_posts
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private Integer numPosts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.count_posts
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private Byte countPosts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.id_theme
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private Byte idTheme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.override_theme
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private Byte overrideTheme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.countMoney
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private Byte countmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.is_redirect
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private Byte isRedirect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.redirect_clicks
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private Integer redirectClicks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.redirect_count_clicks
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private Byte redirectCountClicks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.redirect
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private String redirect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.unapproved_posts
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private Short unapprovedPosts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1boards.unapproved_topics
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    private Short unapprovedTopics;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.id_board
     *
     * @return the value of smf_1boards.id_board
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public Integer getIdBoard() {
        return idBoard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.id_board
     *
     * @param idBoard the value for smf_1boards.id_board
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setIdBoard(Integer idBoard) {
        this.idBoard = idBoard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.id_cat
     *
     * @return the value of smf_1boards.id_cat
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public Integer getIdCat() {
        return idCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.id_cat
     *
     * @param idCat the value for smf_1boards.id_cat
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setIdCat(Integer idCat) {
        this.idCat = idCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.child_level
     *
     * @return the value of smf_1boards.child_level
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public Byte getChildLevel() {
        return childLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.child_level
     *
     * @param childLevel the value for smf_1boards.child_level
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setChildLevel(Byte childLevel) {
        this.childLevel = childLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.id_parent
     *
     * @return the value of smf_1boards.id_parent
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public Integer getIdParent() {
        return idParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.id_parent
     *
     * @param idParent the value for smf_1boards.id_parent
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setIdParent(Integer idParent) {
        this.idParent = idParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.board_order
     *
     * @return the value of smf_1boards.board_order
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public Short getBoardOrder() {
        return boardOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.board_order
     *
     * @param boardOrder the value for smf_1boards.board_order
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setBoardOrder(Short boardOrder) {
        this.boardOrder = boardOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.id_last_msg
     *
     * @return the value of smf_1boards.id_last_msg
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public Integer getIdLastMsg() {
        return idLastMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.id_last_msg
     *
     * @param idLastMsg the value for smf_1boards.id_last_msg
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setIdLastMsg(Integer idLastMsg) {
        this.idLastMsg = idLastMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.id_msg_updated
     *
     * @return the value of smf_1boards.id_msg_updated
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public Integer getIdMsgUpdated() {
        return idMsgUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.id_msg_updated
     *
     * @param idMsgUpdated the value for smf_1boards.id_msg_updated
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setIdMsgUpdated(Integer idMsgUpdated) {
        this.idMsgUpdated = idMsgUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.member_groups
     *
     * @return the value of smf_1boards.member_groups
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public String getMemberGroups() {
        return memberGroups;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.member_groups
     *
     * @param memberGroups the value for smf_1boards.member_groups
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setMemberGroups(String memberGroups) {
        this.memberGroups = memberGroups;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.id_profile
     *
     * @return the value of smf_1boards.id_profile
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public Short getIdProfile() {
        return idProfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.id_profile
     *
     * @param idProfile the value for smf_1boards.id_profile
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setIdProfile(Short idProfile) {
        this.idProfile = idProfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.name
     *
     * @return the value of smf_1boards.name
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.name
     *
     * @param name the value for smf_1boards.name
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.num_topics
     *
     * @return the value of smf_1boards.num_topics
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public Integer getNumTopics() {
        return numTopics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.num_topics
     *
     * @param numTopics the value for smf_1boards.num_topics
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setNumTopics(Integer numTopics) {
        this.numTopics = numTopics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.num_posts
     *
     * @return the value of smf_1boards.num_posts
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public Integer getNumPosts() {
        return numPosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.num_posts
     *
     * @param numPosts the value for smf_1boards.num_posts
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setNumPosts(Integer numPosts) {
        this.numPosts = numPosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.count_posts
     *
     * @return the value of smf_1boards.count_posts
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public Byte getCountPosts() {
        return countPosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.count_posts
     *
     * @param countPosts the value for smf_1boards.count_posts
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setCountPosts(Byte countPosts) {
        this.countPosts = countPosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.id_theme
     *
     * @return the value of smf_1boards.id_theme
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public Byte getIdTheme() {
        return idTheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.id_theme
     *
     * @param idTheme the value for smf_1boards.id_theme
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setIdTheme(Byte idTheme) {
        this.idTheme = idTheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.override_theme
     *
     * @return the value of smf_1boards.override_theme
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public Byte getOverrideTheme() {
        return overrideTheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.override_theme
     *
     * @param overrideTheme the value for smf_1boards.override_theme
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setOverrideTheme(Byte overrideTheme) {
        this.overrideTheme = overrideTheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.countMoney
     *
     * @return the value of smf_1boards.countMoney
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public Byte getCountmoney() {
        return countmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.countMoney
     *
     * @param countmoney the value for smf_1boards.countMoney
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setCountmoney(Byte countmoney) {
        this.countmoney = countmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.is_redirect
     *
     * @return the value of smf_1boards.is_redirect
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public Byte getIsRedirect() {
        return isRedirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.is_redirect
     *
     * @param isRedirect the value for smf_1boards.is_redirect
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setIsRedirect(Byte isRedirect) {
        this.isRedirect = isRedirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.redirect_clicks
     *
     * @return the value of smf_1boards.redirect_clicks
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public Integer getRedirectClicks() {
        return redirectClicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.redirect_clicks
     *
     * @param redirectClicks the value for smf_1boards.redirect_clicks
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setRedirectClicks(Integer redirectClicks) {
        this.redirectClicks = redirectClicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.redirect_count_clicks
     *
     * @return the value of smf_1boards.redirect_count_clicks
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public Byte getRedirectCountClicks() {
        return redirectCountClicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.redirect_count_clicks
     *
     * @param redirectCountClicks the value for smf_1boards.redirect_count_clicks
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setRedirectCountClicks(Byte redirectCountClicks) {
        this.redirectCountClicks = redirectCountClicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.redirect
     *
     * @return the value of smf_1boards.redirect
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public String getRedirect() {
        return redirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.redirect
     *
     * @param redirect the value for smf_1boards.redirect
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setRedirect(String redirect) {
        this.redirect = redirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.unapproved_posts
     *
     * @return the value of smf_1boards.unapproved_posts
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public Short getUnapprovedPosts() {
        return unapprovedPosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.unapproved_posts
     *
     * @param unapprovedPosts the value for smf_1boards.unapproved_posts
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setUnapprovedPosts(Short unapprovedPosts) {
        this.unapprovedPosts = unapprovedPosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1boards.unapproved_topics
     *
     * @return the value of smf_1boards.unapproved_topics
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public Short getUnapprovedTopics() {
        return unapprovedTopics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1boards.unapproved_topics
     *
     * @param unapprovedTopics the value for smf_1boards.unapproved_topics
     *
     * @mbg.generated Mon Feb 10 20:02:57 EST 2025
     */
    public void setUnapprovedTopics(Short unapprovedTopics) {
        this.unapprovedTopics = unapprovedTopics;
    }
}