package com.zfgc.zfgbb.migrator.smf.dbo;

public class SMFCategoryDb {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1categories.id_cat
	 * @mbg.generated  Mon Feb 10 19:48:50 EST 2025
	 */
	private Integer idCat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1categories.cat_order
	 * @mbg.generated  Mon Feb 10 19:48:50 EST 2025
	 */
	private Byte catOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1categories.name
	 * @mbg.generated  Mon Feb 10 19:48:50 EST 2025
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1categories.can_collapse
	 * @mbg.generated  Mon Feb 10 19:48:50 EST 2025
	 */
	private Boolean canCollapse;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1categories.id_cat
	 * @return  the value of smf_1categories.id_cat
	 * @mbg.generated  Mon Feb 10 19:48:50 EST 2025
	 */
	public Integer getIdCat() {
		return idCat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1categories.id_cat
	 * @param idCat  the value for smf_1categories.id_cat
	 * @mbg.generated  Mon Feb 10 19:48:50 EST 2025
	 */
	public void setIdCat(Integer idCat) {
		this.idCat = idCat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1categories.cat_order
	 * @return  the value of smf_1categories.cat_order
	 * @mbg.generated  Mon Feb 10 19:48:50 EST 2025
	 */
	public Byte getCatOrder() {
		return catOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1categories.cat_order
	 * @param catOrder  the value for smf_1categories.cat_order
	 * @mbg.generated  Mon Feb 10 19:48:50 EST 2025
	 */
	public void setCatOrder(Byte catOrder) {
		this.catOrder = catOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1categories.name
	 * @return  the value of smf_1categories.name
	 * @mbg.generated  Mon Feb 10 19:48:50 EST 2025
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1categories.name
	 * @param name  the value for smf_1categories.name
	 * @mbg.generated  Mon Feb 10 19:48:50 EST 2025
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1categories.can_collapse
	 * @return  the value of smf_1categories.can_collapse
	 * @mbg.generated  Mon Feb 10 19:48:50 EST 2025
	 */
	public Boolean getCanCollapse() {
		return canCollapse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1categories.can_collapse
	 * @param canCollapse  the value for smf_1categories.can_collapse
	 * @mbg.generated  Mon Feb 10 19:48:50 EST 2025
	 */
	public void setCanCollapse(Boolean canCollapse) {
		this.canCollapse = canCollapse;
	}
}