package com.zfgc.zfgbb.migrator.smf.dbo;

public class SMFLogKarmaDbWithBLOBs extends SMFLogKarmaDb {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1log_karma.description
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1log_karma.link
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	private String link;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1log_karma.description
	 * @return  the value of smf_1log_karma.description
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1log_karma.description
	 * @param description  the value for smf_1log_karma.description
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1log_karma.link
	 * @return  the value of smf_1log_karma.link
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public String getLink() {
		return link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1log_karma.link
	 * @param link  the value for smf_1log_karma.link
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public void setLink(String link) {
		this.link = link;
	}
}