package com.zfgc.zfgbb.migrator.smf.dbo;

import java.util.ArrayList;
import java.util.List;

public class SMFLogKarmaDbExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public SMFLogKarmaDbExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdTargetIsNull() {
			addCriterion("id_target is null");
			return (Criteria) this;
		}

		public Criteria andIdTargetIsNotNull() {
			addCriterion("id_target is not null");
			return (Criteria) this;
		}

		public Criteria andIdTargetEqualTo(Integer value) {
			addCriterion("id_target =", value, "idTarget");
			return (Criteria) this;
		}

		public Criteria andIdTargetNotEqualTo(Integer value) {
			addCriterion("id_target <>", value, "idTarget");
			return (Criteria) this;
		}

		public Criteria andIdTargetGreaterThan(Integer value) {
			addCriterion("id_target >", value, "idTarget");
			return (Criteria) this;
		}

		public Criteria andIdTargetGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_target >=", value, "idTarget");
			return (Criteria) this;
		}

		public Criteria andIdTargetLessThan(Integer value) {
			addCriterion("id_target <", value, "idTarget");
			return (Criteria) this;
		}

		public Criteria andIdTargetLessThanOrEqualTo(Integer value) {
			addCriterion("id_target <=", value, "idTarget");
			return (Criteria) this;
		}

		public Criteria andIdTargetIn(List<Integer> values) {
			addCriterion("id_target in", values, "idTarget");
			return (Criteria) this;
		}

		public Criteria andIdTargetNotIn(List<Integer> values) {
			addCriterion("id_target not in", values, "idTarget");
			return (Criteria) this;
		}

		public Criteria andIdTargetBetween(Integer value1, Integer value2) {
			addCriterion("id_target between", value1, value2, "idTarget");
			return (Criteria) this;
		}

		public Criteria andIdTargetNotBetween(Integer value1, Integer value2) {
			addCriterion("id_target not between", value1, value2, "idTarget");
			return (Criteria) this;
		}

		public Criteria andIdExecutorIsNull() {
			addCriterion("id_executor is null");
			return (Criteria) this;
		}

		public Criteria andIdExecutorIsNotNull() {
			addCriterion("id_executor is not null");
			return (Criteria) this;
		}

		public Criteria andIdExecutorEqualTo(Integer value) {
			addCriterion("id_executor =", value, "idExecutor");
			return (Criteria) this;
		}

		public Criteria andIdExecutorNotEqualTo(Integer value) {
			addCriterion("id_executor <>", value, "idExecutor");
			return (Criteria) this;
		}

		public Criteria andIdExecutorGreaterThan(Integer value) {
			addCriterion("id_executor >", value, "idExecutor");
			return (Criteria) this;
		}

		public Criteria andIdExecutorGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_executor >=", value, "idExecutor");
			return (Criteria) this;
		}

		public Criteria andIdExecutorLessThan(Integer value) {
			addCriterion("id_executor <", value, "idExecutor");
			return (Criteria) this;
		}

		public Criteria andIdExecutorLessThanOrEqualTo(Integer value) {
			addCriterion("id_executor <=", value, "idExecutor");
			return (Criteria) this;
		}

		public Criteria andIdExecutorIn(List<Integer> values) {
			addCriterion("id_executor in", values, "idExecutor");
			return (Criteria) this;
		}

		public Criteria andIdExecutorNotIn(List<Integer> values) {
			addCriterion("id_executor not in", values, "idExecutor");
			return (Criteria) this;
		}

		public Criteria andIdExecutorBetween(Integer value1, Integer value2) {
			addCriterion("id_executor between", value1, value2, "idExecutor");
			return (Criteria) this;
		}

		public Criteria andIdExecutorNotBetween(Integer value1, Integer value2) {
			addCriterion("id_executor not between", value1, value2, "idExecutor");
			return (Criteria) this;
		}

		public Criteria andLogTimeIsNull() {
			addCriterion("log_time is null");
			return (Criteria) this;
		}

		public Criteria andLogTimeIsNotNull() {
			addCriterion("log_time is not null");
			return (Criteria) this;
		}

		public Criteria andLogTimeEqualTo(Integer value) {
			addCriterion("log_time =", value, "logTime");
			return (Criteria) this;
		}

		public Criteria andLogTimeNotEqualTo(Integer value) {
			addCriterion("log_time <>", value, "logTime");
			return (Criteria) this;
		}

		public Criteria andLogTimeGreaterThan(Integer value) {
			addCriterion("log_time >", value, "logTime");
			return (Criteria) this;
		}

		public Criteria andLogTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("log_time >=", value, "logTime");
			return (Criteria) this;
		}

		public Criteria andLogTimeLessThan(Integer value) {
			addCriterion("log_time <", value, "logTime");
			return (Criteria) this;
		}

		public Criteria andLogTimeLessThanOrEqualTo(Integer value) {
			addCriterion("log_time <=", value, "logTime");
			return (Criteria) this;
		}

		public Criteria andLogTimeIn(List<Integer> values) {
			addCriterion("log_time in", values, "logTime");
			return (Criteria) this;
		}

		public Criteria andLogTimeNotIn(List<Integer> values) {
			addCriterion("log_time not in", values, "logTime");
			return (Criteria) this;
		}

		public Criteria andLogTimeBetween(Integer value1, Integer value2) {
			addCriterion("log_time between", value1, value2, "logTime");
			return (Criteria) this;
		}

		public Criteria andLogTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("log_time not between", value1, value2, "logTime");
			return (Criteria) this;
		}

		public Criteria andActionIsNull() {
			addCriterion("action is null");
			return (Criteria) this;
		}

		public Criteria andActionIsNotNull() {
			addCriterion("action is not null");
			return (Criteria) this;
		}

		public Criteria andActionEqualTo(Integer value) {
			addCriterion("action =", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionNotEqualTo(Integer value) {
			addCriterion("action <>", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionGreaterThan(Integer value) {
			addCriterion("action >", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionGreaterThanOrEqualTo(Integer value) {
			addCriterion("action >=", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionLessThan(Integer value) {
			addCriterion("action <", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionLessThanOrEqualTo(Integer value) {
			addCriterion("action <=", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionIn(List<Integer> values) {
			addCriterion("action in", values, "action");
			return (Criteria) this;
		}

		public Criteria andActionNotIn(List<Integer> values) {
			addCriterion("action not in", values, "action");
			return (Criteria) this;
		}

		public Criteria andActionBetween(Integer value1, Integer value2) {
			addCriterion("action between", value1, value2, "action");
			return (Criteria) this;
		}

		public Criteria andActionNotBetween(Integer value1, Integer value2) {
			addCriterion("action not between", value1, value2, "action");
			return (Criteria) this;
		}

		public Criteria andIsReadIsNull() {
			addCriterion("is_read is null");
			return (Criteria) this;
		}

		public Criteria andIsReadIsNotNull() {
			addCriterion("is_read is not null");
			return (Criteria) this;
		}

		public Criteria andIsReadEqualTo(Short value) {
			addCriterion("is_read =", value, "isRead");
			return (Criteria) this;
		}

		public Criteria andIsReadNotEqualTo(Short value) {
			addCriterion("is_read <>", value, "isRead");
			return (Criteria) this;
		}

		public Criteria andIsReadGreaterThan(Short value) {
			addCriterion("is_read >", value, "isRead");
			return (Criteria) this;
		}

		public Criteria andIsReadGreaterThanOrEqualTo(Short value) {
			addCriterion("is_read >=", value, "isRead");
			return (Criteria) this;
		}

		public Criteria andIsReadLessThan(Short value) {
			addCriterion("is_read <", value, "isRead");
			return (Criteria) this;
		}

		public Criteria andIsReadLessThanOrEqualTo(Short value) {
			addCriterion("is_read <=", value, "isRead");
			return (Criteria) this;
		}

		public Criteria andIsReadIn(List<Short> values) {
			addCriterion("is_read in", values, "isRead");
			return (Criteria) this;
		}

		public Criteria andIsReadNotIn(List<Short> values) {
			addCriterion("is_read not in", values, "isRead");
			return (Criteria) this;
		}

		public Criteria andIsReadBetween(Short value1, Short value2) {
			addCriterion("is_read between", value1, value2, "isRead");
			return (Criteria) this;
		}

		public Criteria andIsReadNotBetween(Short value1, Short value2) {
			addCriterion("is_read not between", value1, value2, "isRead");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table smf_1log_karma
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table smf_1log_karma
     *
     * @mbg.generated do_not_delete_during_merge Sun Mar 29 15:25:09 EDT 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}