package com.zfgc.zfgbb.migrator.smf.dbo;

import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneOffset;

public class SMFLogKarmaDb {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1log_karma.id_target
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	private Integer idTarget;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1log_karma.id_executor
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	private Integer idExecutor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1log_karma.log_time
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	private Integer logTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1log_karma.action
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	private Integer action;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1log_karma.is_read
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	private Short isRead;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1log_karma.id_target
	 * @return  the value of smf_1log_karma.id_target
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public Integer getIdTarget() {
		return idTarget;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1log_karma.id_target
	 * @param idTarget  the value for smf_1log_karma.id_target
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public void setIdTarget(Integer idTarget) {
		this.idTarget = idTarget;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1log_karma.id_executor
	 * @return  the value of smf_1log_karma.id_executor
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public Integer getIdExecutor() {
		return idExecutor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1log_karma.id_executor
	 * @param idExecutor  the value for smf_1log_karma.id_executor
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public void setIdExecutor(Integer idExecutor) {
		this.idExecutor = idExecutor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1log_karma.log_time
	 * @return  the value of smf_1log_karma.log_time
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public Integer getLogTime() {
		return logTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1log_karma.log_time
	 * @param logTime  the value for smf_1log_karma.log_time
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public void setLogTime(Integer logTime) {
		this.logTime = logTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1log_karma.action
	 * @return  the value of smf_1log_karma.action
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public Integer getAction() {
		return action;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1log_karma.action
	 * @param action  the value for smf_1log_karma.action
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public void setAction(Integer action) {
		this.action = action;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1log_karma.is_read
	 * @return  the value of smf_1log_karma.is_read
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public Short getIsRead() {
		return isRead;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1log_karma.is_read
	 * @param isRead  the value for smf_1log_karma.is_read
	 * @mbg.generated  Sun Mar 29 15:46:43 EDT 2026
	 */
	public void setIsRead(Short isRead) {
		this.isRead = isRead;
	}

	public LocalDateTime getLogTimeAsTime() {
		if(this.getLogTime() == 0) {
			return null;
		}
		
		Long ts = Long.parseLong(this.getLogTime().toString() + "000");
		return LocalDateTime.ofInstant(Instant.ofEpochMilli(ts), ZoneOffset.UTC);
	}
}