package com.zfgc.zfgbb.migrator.smf.dbo;

import java.util.ArrayList;
import java.util.List;

public class SMFMessageHistoryDbExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	public SMFMessageHistoryDbExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdEditIsNull() {
			addCriterion("id_edit is null");
			return (Criteria) this;
		}

		public Criteria andIdEditIsNotNull() {
			addCriterion("id_edit is not null");
			return (Criteria) this;
		}

		public Criteria andIdEditEqualTo(Integer value) {
			addCriterion("id_edit =", value, "idEdit");
			return (Criteria) this;
		}

		public Criteria andIdEditNotEqualTo(Integer value) {
			addCriterion("id_edit <>", value, "idEdit");
			return (Criteria) this;
		}

		public Criteria andIdEditGreaterThan(Integer value) {
			addCriterion("id_edit >", value, "idEdit");
			return (Criteria) this;
		}

		public Criteria andIdEditGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_edit >=", value, "idEdit");
			return (Criteria) this;
		}

		public Criteria andIdEditLessThan(Integer value) {
			addCriterion("id_edit <", value, "idEdit");
			return (Criteria) this;
		}

		public Criteria andIdEditLessThanOrEqualTo(Integer value) {
			addCriterion("id_edit <=", value, "idEdit");
			return (Criteria) this;
		}

		public Criteria andIdEditIn(List<Integer> values) {
			addCriterion("id_edit in", values, "idEdit");
			return (Criteria) this;
		}

		public Criteria andIdEditNotIn(List<Integer> values) {
			addCriterion("id_edit not in", values, "idEdit");
			return (Criteria) this;
		}

		public Criteria andIdEditBetween(Integer value1, Integer value2) {
			addCriterion("id_edit between", value1, value2, "idEdit");
			return (Criteria) this;
		}

		public Criteria andIdEditNotBetween(Integer value1, Integer value2) {
			addCriterion("id_edit not between", value1, value2, "idEdit");
			return (Criteria) this;
		}

		public Criteria andIdMsgIsNull() {
			addCriterion("id_msg is null");
			return (Criteria) this;
		}

		public Criteria andIdMsgIsNotNull() {
			addCriterion("id_msg is not null");
			return (Criteria) this;
		}

		public Criteria andIdMsgEqualTo(Integer value) {
			addCriterion("id_msg =", value, "idMsg");
			return (Criteria) this;
		}

		public Criteria andIdMsgNotEqualTo(Integer value) {
			addCriterion("id_msg <>", value, "idMsg");
			return (Criteria) this;
		}

		public Criteria andIdMsgGreaterThan(Integer value) {
			addCriterion("id_msg >", value, "idMsg");
			return (Criteria) this;
		}

		public Criteria andIdMsgGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_msg >=", value, "idMsg");
			return (Criteria) this;
		}

		public Criteria andIdMsgLessThan(Integer value) {
			addCriterion("id_msg <", value, "idMsg");
			return (Criteria) this;
		}

		public Criteria andIdMsgLessThanOrEqualTo(Integer value) {
			addCriterion("id_msg <=", value, "idMsg");
			return (Criteria) this;
		}

		public Criteria andIdMsgIn(List<Integer> values) {
			addCriterion("id_msg in", values, "idMsg");
			return (Criteria) this;
		}

		public Criteria andIdMsgNotIn(List<Integer> values) {
			addCriterion("id_msg not in", values, "idMsg");
			return (Criteria) this;
		}

		public Criteria andIdMsgBetween(Integer value1, Integer value2) {
			addCriterion("id_msg between", value1, value2, "idMsg");
			return (Criteria) this;
		}

		public Criteria andIdMsgNotBetween(Integer value1, Integer value2) {
			addCriterion("id_msg not between", value1, value2, "idMsg");
			return (Criteria) this;
		}

		public Criteria andModifiedNameIsNull() {
			addCriterion("modified_name is null");
			return (Criteria) this;
		}

		public Criteria andModifiedNameIsNotNull() {
			addCriterion("modified_name is not null");
			return (Criteria) this;
		}

		public Criteria andModifiedNameEqualTo(String value) {
			addCriterion("modified_name =", value, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andModifiedNameNotEqualTo(String value) {
			addCriterion("modified_name <>", value, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andModifiedNameGreaterThan(String value) {
			addCriterion("modified_name >", value, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andModifiedNameGreaterThanOrEqualTo(String value) {
			addCriterion("modified_name >=", value, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andModifiedNameLessThan(String value) {
			addCriterion("modified_name <", value, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andModifiedNameLessThanOrEqualTo(String value) {
			addCriterion("modified_name <=", value, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andModifiedNameLike(String value) {
			addCriterion("modified_name like", value, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andModifiedNameNotLike(String value) {
			addCriterion("modified_name not like", value, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andModifiedNameIn(List<String> values) {
			addCriterion("modified_name in", values, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andModifiedNameNotIn(List<String> values) {
			addCriterion("modified_name not in", values, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andModifiedNameBetween(String value1, String value2) {
			addCriterion("modified_name between", value1, value2, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andModifiedNameNotBetween(String value1, String value2) {
			addCriterion("modified_name not between", value1, value2, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeIsNull() {
			addCriterion("modified_time is null");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeIsNotNull() {
			addCriterion("modified_time is not null");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeEqualTo(Integer value) {
			addCriterion("modified_time =", value, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeNotEqualTo(Integer value) {
			addCriterion("modified_time <>", value, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeGreaterThan(Integer value) {
			addCriterion("modified_time >", value, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("modified_time >=", value, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeLessThan(Integer value) {
			addCriterion("modified_time <", value, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeLessThanOrEqualTo(Integer value) {
			addCriterion("modified_time <=", value, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeIn(List<Integer> values) {
			addCriterion("modified_time in", values, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeNotIn(List<Integer> values) {
			addCriterion("modified_time not in", values, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeBetween(Integer value1, Integer value2) {
			addCriterion("modified_time between", value1, value2, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("modified_time not between", value1, value2, "modifiedTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table smf_1messages_history
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table smf_1messages_history
     *
     * @mbg.generated do_not_delete_during_merge Sun Feb 16 12:29:05 EST 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}