package com.zfgc.zfgbb.migrator.smf.dbo;

public class SMFMessageDb {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1messages.id_msg
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	private Integer idMsg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1messages.id_topic
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	private Integer idTopic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1messages.id_board
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	private Short idBoard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1messages.poster_time
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	private Integer posterTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1messages.id_member
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	private Integer idMember;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1messages.id_msg_modified
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	private Integer idMsgModified;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1messages.subject
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	private String subject;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1messages.poster_name
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	private String posterName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1messages.poster_email
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	private String posterEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1messages.poster_ip
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	private String posterIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1messages.smileys_enabled
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	private Byte smileysEnabled;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1messages.modified_time
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	private Integer modifiedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1messages.modified_name
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	private String modifiedName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1messages.icon
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	private String icon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1messages.approved
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	private Byte approved;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1messages.id_msg
	 * @return  the value of smf_1messages.id_msg
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public Integer getIdMsg() {
		return idMsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1messages.id_msg
	 * @param idMsg  the value for smf_1messages.id_msg
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public void setIdMsg(Integer idMsg) {
		this.idMsg = idMsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1messages.id_topic
	 * @return  the value of smf_1messages.id_topic
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public Integer getIdTopic() {
		return idTopic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1messages.id_topic
	 * @param idTopic  the value for smf_1messages.id_topic
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public void setIdTopic(Integer idTopic) {
		this.idTopic = idTopic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1messages.id_board
	 * @return  the value of smf_1messages.id_board
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public Short getIdBoard() {
		return idBoard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1messages.id_board
	 * @param idBoard  the value for smf_1messages.id_board
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public void setIdBoard(Short idBoard) {
		this.idBoard = idBoard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1messages.poster_time
	 * @return  the value of smf_1messages.poster_time
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public Integer getPosterTime() {
		return posterTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1messages.poster_time
	 * @param posterTime  the value for smf_1messages.poster_time
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public void setPosterTime(Integer posterTime) {
		this.posterTime = posterTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1messages.id_member
	 * @return  the value of smf_1messages.id_member
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public Integer getIdMember() {
		return idMember;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1messages.id_member
	 * @param idMember  the value for smf_1messages.id_member
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public void setIdMember(Integer idMember) {
		this.idMember = idMember;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1messages.id_msg_modified
	 * @return  the value of smf_1messages.id_msg_modified
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public Integer getIdMsgModified() {
		return idMsgModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1messages.id_msg_modified
	 * @param idMsgModified  the value for smf_1messages.id_msg_modified
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public void setIdMsgModified(Integer idMsgModified) {
		this.idMsgModified = idMsgModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1messages.subject
	 * @return  the value of smf_1messages.subject
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public String getSubject() {
		return subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1messages.subject
	 * @param subject  the value for smf_1messages.subject
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public void setSubject(String subject) {
		this.subject = subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1messages.poster_name
	 * @return  the value of smf_1messages.poster_name
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public String getPosterName() {
		return posterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1messages.poster_name
	 * @param posterName  the value for smf_1messages.poster_name
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public void setPosterName(String posterName) {
		this.posterName = posterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1messages.poster_email
	 * @return  the value of smf_1messages.poster_email
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public String getPosterEmail() {
		return posterEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1messages.poster_email
	 * @param posterEmail  the value for smf_1messages.poster_email
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public void setPosterEmail(String posterEmail) {
		this.posterEmail = posterEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1messages.poster_ip
	 * @return  the value of smf_1messages.poster_ip
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public String getPosterIp() {
		return posterIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1messages.poster_ip
	 * @param posterIp  the value for smf_1messages.poster_ip
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public void setPosterIp(String posterIp) {
		this.posterIp = posterIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1messages.smileys_enabled
	 * @return  the value of smf_1messages.smileys_enabled
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public Byte getSmileysEnabled() {
		return smileysEnabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1messages.smileys_enabled
	 * @param smileysEnabled  the value for smf_1messages.smileys_enabled
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public void setSmileysEnabled(Byte smileysEnabled) {
		this.smileysEnabled = smileysEnabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1messages.modified_time
	 * @return  the value of smf_1messages.modified_time
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public Integer getModifiedTime() {
		return modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1messages.modified_time
	 * @param modifiedTime  the value for smf_1messages.modified_time
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public void setModifiedTime(Integer modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1messages.modified_name
	 * @return  the value of smf_1messages.modified_name
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public String getModifiedName() {
		return modifiedName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1messages.modified_name
	 * @param modifiedName  the value for smf_1messages.modified_name
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public void setModifiedName(String modifiedName) {
		this.modifiedName = modifiedName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1messages.icon
	 * @return  the value of smf_1messages.icon
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1messages.icon
	 * @param icon  the value for smf_1messages.icon
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1messages.approved
	 * @return  the value of smf_1messages.approved
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public Byte getApproved() {
		return approved;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1messages.approved
	 * @param approved  the value for smf_1messages.approved
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public void setApproved(Byte approved) {
		this.approved = approved;
	}
}