package com.zfgc.zfgbb.migrator.smf.dbo;

import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneOffset;

public class SMFMessageHistoryDb {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1messages_history.id_edit
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	private Integer idEdit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1messages_history.id_msg
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	private Integer idMsg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1messages_history.modified_name
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	private String modifiedName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1messages_history.modified_time
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	private Integer modifiedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1messages_history.body
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	private String body;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1messages_history.id_edit
	 * @return  the value of smf_1messages_history.id_edit
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	public Integer getIdEdit() {
		return idEdit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1messages_history.id_edit
	 * @param idEdit  the value for smf_1messages_history.id_edit
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	public void setIdEdit(Integer idEdit) {
		this.idEdit = idEdit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1messages_history.id_msg
	 * @return  the value of smf_1messages_history.id_msg
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	public Integer getIdMsg() {
		return idMsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1messages_history.id_msg
	 * @param idMsg  the value for smf_1messages_history.id_msg
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	public void setIdMsg(Integer idMsg) {
		this.idMsg = idMsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1messages_history.modified_name
	 * @return  the value of smf_1messages_history.modified_name
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	public String getModifiedName() {
		return modifiedName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1messages_history.modified_name
	 * @param modifiedName  the value for smf_1messages_history.modified_name
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	public void setModifiedName(String modifiedName) {
		this.modifiedName = modifiedName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1messages_history.modified_time
	 * @return  the value of smf_1messages_history.modified_time
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	public Integer getModifiedTime() {
		return modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1messages_history.modified_time
	 * @param modifiedTime  the value for smf_1messages_history.modified_time
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	public void setModifiedTime(Integer modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1messages_history.body
	 * @return  the value of smf_1messages_history.body
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	public String getBody() {
		return body;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1messages_history.body
	 * @param body  the value for smf_1messages_history.body
	 * @mbg.generated  Sun Feb 16 18:03:13 EST 2025
	 */
	public void setBody(String body) {
		this.body = body;
	}
	
	public LocalDateTime getPostTimeAsTime() {
		Long ts = Long.parseLong(modifiedTime.toString() + "000");
		return LocalDateTime.ofInstant(Instant.ofEpochMilli(ts), ZoneOffset.UTC);
	}
	
	public LocalDateTime getUpdatedTimeAsTime() {
		if(this.getModifiedTime() == 0) {
			return null;
		}
		
		Long ts = Long.parseLong(this.getModifiedTime().toString() + "000");
		return LocalDateTime.ofInstant(Instant.ofEpochMilli(ts), ZoneOffset.UTC);
	}
}