package com.zfgc.zfgbb.migrator.smf.dbo;

import java.util.ArrayList;
import java.util.List;

public class SMFMessageDbExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public SMFMessageDbExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdMsgIsNull() {
			addCriterion("id_msg is null");
			return (Criteria) this;
		}

		public Criteria andIdMsgIsNotNull() {
			addCriterion("id_msg is not null");
			return (Criteria) this;
		}

		public Criteria andIdMsgEqualTo(Integer value) {
			addCriterion("id_msg =", value, "idMsg");
			return (Criteria) this;
		}

		public Criteria andIdMsgNotEqualTo(Integer value) {
			addCriterion("id_msg <>", value, "idMsg");
			return (Criteria) this;
		}

		public Criteria andIdMsgGreaterThan(Integer value) {
			addCriterion("id_msg >", value, "idMsg");
			return (Criteria) this;
		}

		public Criteria andIdMsgGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_msg >=", value, "idMsg");
			return (Criteria) this;
		}

		public Criteria andIdMsgLessThan(Integer value) {
			addCriterion("id_msg <", value, "idMsg");
			return (Criteria) this;
		}

		public Criteria andIdMsgLessThanOrEqualTo(Integer value) {
			addCriterion("id_msg <=", value, "idMsg");
			return (Criteria) this;
		}

		public Criteria andIdMsgIn(List<Integer> values) {
			addCriterion("id_msg in", values, "idMsg");
			return (Criteria) this;
		}

		public Criteria andIdMsgNotIn(List<Integer> values) {
			addCriterion("id_msg not in", values, "idMsg");
			return (Criteria) this;
		}

		public Criteria andIdMsgBetween(Integer value1, Integer value2) {
			addCriterion("id_msg between", value1, value2, "idMsg");
			return (Criteria) this;
		}

		public Criteria andIdMsgNotBetween(Integer value1, Integer value2) {
			addCriterion("id_msg not between", value1, value2, "idMsg");
			return (Criteria) this;
		}

		public Criteria andIdTopicIsNull() {
			addCriterion("id_topic is null");
			return (Criteria) this;
		}

		public Criteria andIdTopicIsNotNull() {
			addCriterion("id_topic is not null");
			return (Criteria) this;
		}

		public Criteria andIdTopicEqualTo(Integer value) {
			addCriterion("id_topic =", value, "idTopic");
			return (Criteria) this;
		}

		public Criteria andIdTopicNotEqualTo(Integer value) {
			addCriterion("id_topic <>", value, "idTopic");
			return (Criteria) this;
		}

		public Criteria andIdTopicGreaterThan(Integer value) {
			addCriterion("id_topic >", value, "idTopic");
			return (Criteria) this;
		}

		public Criteria andIdTopicGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_topic >=", value, "idTopic");
			return (Criteria) this;
		}

		public Criteria andIdTopicLessThan(Integer value) {
			addCriterion("id_topic <", value, "idTopic");
			return (Criteria) this;
		}

		public Criteria andIdTopicLessThanOrEqualTo(Integer value) {
			addCriterion("id_topic <=", value, "idTopic");
			return (Criteria) this;
		}

		public Criteria andIdTopicIn(List<Integer> values) {
			addCriterion("id_topic in", values, "idTopic");
			return (Criteria) this;
		}

		public Criteria andIdTopicNotIn(List<Integer> values) {
			addCriterion("id_topic not in", values, "idTopic");
			return (Criteria) this;
		}

		public Criteria andIdTopicBetween(Integer value1, Integer value2) {
			addCriterion("id_topic between", value1, value2, "idTopic");
			return (Criteria) this;
		}

		public Criteria andIdTopicNotBetween(Integer value1, Integer value2) {
			addCriterion("id_topic not between", value1, value2, "idTopic");
			return (Criteria) this;
		}

		public Criteria andIdBoardIsNull() {
			addCriterion("id_board is null");
			return (Criteria) this;
		}

		public Criteria andIdBoardIsNotNull() {
			addCriterion("id_board is not null");
			return (Criteria) this;
		}

		public Criteria andIdBoardEqualTo(Short value) {
			addCriterion("id_board =", value, "idBoard");
			return (Criteria) this;
		}

		public Criteria andIdBoardNotEqualTo(Short value) {
			addCriterion("id_board <>", value, "idBoard");
			return (Criteria) this;
		}

		public Criteria andIdBoardGreaterThan(Short value) {
			addCriterion("id_board >", value, "idBoard");
			return (Criteria) this;
		}

		public Criteria andIdBoardGreaterThanOrEqualTo(Short value) {
			addCriterion("id_board >=", value, "idBoard");
			return (Criteria) this;
		}

		public Criteria andIdBoardLessThan(Short value) {
			addCriterion("id_board <", value, "idBoard");
			return (Criteria) this;
		}

		public Criteria andIdBoardLessThanOrEqualTo(Short value) {
			addCriterion("id_board <=", value, "idBoard");
			return (Criteria) this;
		}

		public Criteria andIdBoardIn(List<Short> values) {
			addCriterion("id_board in", values, "idBoard");
			return (Criteria) this;
		}

		public Criteria andIdBoardNotIn(List<Short> values) {
			addCriterion("id_board not in", values, "idBoard");
			return (Criteria) this;
		}

		public Criteria andIdBoardBetween(Short value1, Short value2) {
			addCriterion("id_board between", value1, value2, "idBoard");
			return (Criteria) this;
		}

		public Criteria andIdBoardNotBetween(Short value1, Short value2) {
			addCriterion("id_board not between", value1, value2, "idBoard");
			return (Criteria) this;
		}

		public Criteria andPosterTimeIsNull() {
			addCriterion("poster_time is null");
			return (Criteria) this;
		}

		public Criteria andPosterTimeIsNotNull() {
			addCriterion("poster_time is not null");
			return (Criteria) this;
		}

		public Criteria andPosterTimeEqualTo(Integer value) {
			addCriterion("poster_time =", value, "posterTime");
			return (Criteria) this;
		}

		public Criteria andPosterTimeNotEqualTo(Integer value) {
			addCriterion("poster_time <>", value, "posterTime");
			return (Criteria) this;
		}

		public Criteria andPosterTimeGreaterThan(Integer value) {
			addCriterion("poster_time >", value, "posterTime");
			return (Criteria) this;
		}

		public Criteria andPosterTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("poster_time >=", value, "posterTime");
			return (Criteria) this;
		}

		public Criteria andPosterTimeLessThan(Integer value) {
			addCriterion("poster_time <", value, "posterTime");
			return (Criteria) this;
		}

		public Criteria andPosterTimeLessThanOrEqualTo(Integer value) {
			addCriterion("poster_time <=", value, "posterTime");
			return (Criteria) this;
		}

		public Criteria andPosterTimeIn(List<Integer> values) {
			addCriterion("poster_time in", values, "posterTime");
			return (Criteria) this;
		}

		public Criteria andPosterTimeNotIn(List<Integer> values) {
			addCriterion("poster_time not in", values, "posterTime");
			return (Criteria) this;
		}

		public Criteria andPosterTimeBetween(Integer value1, Integer value2) {
			addCriterion("poster_time between", value1, value2, "posterTime");
			return (Criteria) this;
		}

		public Criteria andPosterTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("poster_time not between", value1, value2, "posterTime");
			return (Criteria) this;
		}

		public Criteria andIdMemberIsNull() {
			addCriterion("id_member is null");
			return (Criteria) this;
		}

		public Criteria andIdMemberIsNotNull() {
			addCriterion("id_member is not null");
			return (Criteria) this;
		}

		public Criteria andIdMemberEqualTo(Integer value) {
			addCriterion("id_member =", value, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberNotEqualTo(Integer value) {
			addCriterion("id_member <>", value, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberGreaterThan(Integer value) {
			addCriterion("id_member >", value, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_member >=", value, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberLessThan(Integer value) {
			addCriterion("id_member <", value, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberLessThanOrEqualTo(Integer value) {
			addCriterion("id_member <=", value, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberIn(List<Integer> values) {
			addCriterion("id_member in", values, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberNotIn(List<Integer> values) {
			addCriterion("id_member not in", values, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberBetween(Integer value1, Integer value2) {
			addCriterion("id_member between", value1, value2, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberNotBetween(Integer value1, Integer value2) {
			addCriterion("id_member not between", value1, value2, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMsgModifiedIsNull() {
			addCriterion("id_msg_modified is null");
			return (Criteria) this;
		}

		public Criteria andIdMsgModifiedIsNotNull() {
			addCriterion("id_msg_modified is not null");
			return (Criteria) this;
		}

		public Criteria andIdMsgModifiedEqualTo(Integer value) {
			addCriterion("id_msg_modified =", value, "idMsgModified");
			return (Criteria) this;
		}

		public Criteria andIdMsgModifiedNotEqualTo(Integer value) {
			addCriterion("id_msg_modified <>", value, "idMsgModified");
			return (Criteria) this;
		}

		public Criteria andIdMsgModifiedGreaterThan(Integer value) {
			addCriterion("id_msg_modified >", value, "idMsgModified");
			return (Criteria) this;
		}

		public Criteria andIdMsgModifiedGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_msg_modified >=", value, "idMsgModified");
			return (Criteria) this;
		}

		public Criteria andIdMsgModifiedLessThan(Integer value) {
			addCriterion("id_msg_modified <", value, "idMsgModified");
			return (Criteria) this;
		}

		public Criteria andIdMsgModifiedLessThanOrEqualTo(Integer value) {
			addCriterion("id_msg_modified <=", value, "idMsgModified");
			return (Criteria) this;
		}

		public Criteria andIdMsgModifiedIn(List<Integer> values) {
			addCriterion("id_msg_modified in", values, "idMsgModified");
			return (Criteria) this;
		}

		public Criteria andIdMsgModifiedNotIn(List<Integer> values) {
			addCriterion("id_msg_modified not in", values, "idMsgModified");
			return (Criteria) this;
		}

		public Criteria andIdMsgModifiedBetween(Integer value1, Integer value2) {
			addCriterion("id_msg_modified between", value1, value2, "idMsgModified");
			return (Criteria) this;
		}

		public Criteria andIdMsgModifiedNotBetween(Integer value1, Integer value2) {
			addCriterion("id_msg_modified not between", value1, value2, "idMsgModified");
			return (Criteria) this;
		}

		public Criteria andSubjectIsNull() {
			addCriterion("subject is null");
			return (Criteria) this;
		}

		public Criteria andSubjectIsNotNull() {
			addCriterion("subject is not null");
			return (Criteria) this;
		}

		public Criteria andSubjectEqualTo(String value) {
			addCriterion("subject =", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotEqualTo(String value) {
			addCriterion("subject <>", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectGreaterThan(String value) {
			addCriterion("subject >", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectGreaterThanOrEqualTo(String value) {
			addCriterion("subject >=", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectLessThan(String value) {
			addCriterion("subject <", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectLessThanOrEqualTo(String value) {
			addCriterion("subject <=", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectLike(String value) {
			addCriterion("subject like", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotLike(String value) {
			addCriterion("subject not like", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectIn(List<String> values) {
			addCriterion("subject in", values, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotIn(List<String> values) {
			addCriterion("subject not in", values, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectBetween(String value1, String value2) {
			addCriterion("subject between", value1, value2, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotBetween(String value1, String value2) {
			addCriterion("subject not between", value1, value2, "subject");
			return (Criteria) this;
		}

		public Criteria andPosterNameIsNull() {
			addCriterion("poster_name is null");
			return (Criteria) this;
		}

		public Criteria andPosterNameIsNotNull() {
			addCriterion("poster_name is not null");
			return (Criteria) this;
		}

		public Criteria andPosterNameEqualTo(String value) {
			addCriterion("poster_name =", value, "posterName");
			return (Criteria) this;
		}

		public Criteria andPosterNameNotEqualTo(String value) {
			addCriterion("poster_name <>", value, "posterName");
			return (Criteria) this;
		}

		public Criteria andPosterNameGreaterThan(String value) {
			addCriterion("poster_name >", value, "posterName");
			return (Criteria) this;
		}

		public Criteria andPosterNameGreaterThanOrEqualTo(String value) {
			addCriterion("poster_name >=", value, "posterName");
			return (Criteria) this;
		}

		public Criteria andPosterNameLessThan(String value) {
			addCriterion("poster_name <", value, "posterName");
			return (Criteria) this;
		}

		public Criteria andPosterNameLessThanOrEqualTo(String value) {
			addCriterion("poster_name <=", value, "posterName");
			return (Criteria) this;
		}

		public Criteria andPosterNameLike(String value) {
			addCriterion("poster_name like", value, "posterName");
			return (Criteria) this;
		}

		public Criteria andPosterNameNotLike(String value) {
			addCriterion("poster_name not like", value, "posterName");
			return (Criteria) this;
		}

		public Criteria andPosterNameIn(List<String> values) {
			addCriterion("poster_name in", values, "posterName");
			return (Criteria) this;
		}

		public Criteria andPosterNameNotIn(List<String> values) {
			addCriterion("poster_name not in", values, "posterName");
			return (Criteria) this;
		}

		public Criteria andPosterNameBetween(String value1, String value2) {
			addCriterion("poster_name between", value1, value2, "posterName");
			return (Criteria) this;
		}

		public Criteria andPosterNameNotBetween(String value1, String value2) {
			addCriterion("poster_name not between", value1, value2, "posterName");
			return (Criteria) this;
		}

		public Criteria andPosterEmailIsNull() {
			addCriterion("poster_email is null");
			return (Criteria) this;
		}

		public Criteria andPosterEmailIsNotNull() {
			addCriterion("poster_email is not null");
			return (Criteria) this;
		}

		public Criteria andPosterEmailEqualTo(String value) {
			addCriterion("poster_email =", value, "posterEmail");
			return (Criteria) this;
		}

		public Criteria andPosterEmailNotEqualTo(String value) {
			addCriterion("poster_email <>", value, "posterEmail");
			return (Criteria) this;
		}

		public Criteria andPosterEmailGreaterThan(String value) {
			addCriterion("poster_email >", value, "posterEmail");
			return (Criteria) this;
		}

		public Criteria andPosterEmailGreaterThanOrEqualTo(String value) {
			addCriterion("poster_email >=", value, "posterEmail");
			return (Criteria) this;
		}

		public Criteria andPosterEmailLessThan(String value) {
			addCriterion("poster_email <", value, "posterEmail");
			return (Criteria) this;
		}

		public Criteria andPosterEmailLessThanOrEqualTo(String value) {
			addCriterion("poster_email <=", value, "posterEmail");
			return (Criteria) this;
		}

		public Criteria andPosterEmailLike(String value) {
			addCriterion("poster_email like", value, "posterEmail");
			return (Criteria) this;
		}

		public Criteria andPosterEmailNotLike(String value) {
			addCriterion("poster_email not like", value, "posterEmail");
			return (Criteria) this;
		}

		public Criteria andPosterEmailIn(List<String> values) {
			addCriterion("poster_email in", values, "posterEmail");
			return (Criteria) this;
		}

		public Criteria andPosterEmailNotIn(List<String> values) {
			addCriterion("poster_email not in", values, "posterEmail");
			return (Criteria) this;
		}

		public Criteria andPosterEmailBetween(String value1, String value2) {
			addCriterion("poster_email between", value1, value2, "posterEmail");
			return (Criteria) this;
		}

		public Criteria andPosterEmailNotBetween(String value1, String value2) {
			addCriterion("poster_email not between", value1, value2, "posterEmail");
			return (Criteria) this;
		}

		public Criteria andPosterIpIsNull() {
			addCriterion("poster_ip is null");
			return (Criteria) this;
		}

		public Criteria andPosterIpIsNotNull() {
			addCriterion("poster_ip is not null");
			return (Criteria) this;
		}

		public Criteria andPosterIpEqualTo(String value) {
			addCriterion("poster_ip =", value, "posterIp");
			return (Criteria) this;
		}

		public Criteria andPosterIpNotEqualTo(String value) {
			addCriterion("poster_ip <>", value, "posterIp");
			return (Criteria) this;
		}

		public Criteria andPosterIpGreaterThan(String value) {
			addCriterion("poster_ip >", value, "posterIp");
			return (Criteria) this;
		}

		public Criteria andPosterIpGreaterThanOrEqualTo(String value) {
			addCriterion("poster_ip >=", value, "posterIp");
			return (Criteria) this;
		}

		public Criteria andPosterIpLessThan(String value) {
			addCriterion("poster_ip <", value, "posterIp");
			return (Criteria) this;
		}

		public Criteria andPosterIpLessThanOrEqualTo(String value) {
			addCriterion("poster_ip <=", value, "posterIp");
			return (Criteria) this;
		}

		public Criteria andPosterIpLike(String value) {
			addCriterion("poster_ip like", value, "posterIp");
			return (Criteria) this;
		}

		public Criteria andPosterIpNotLike(String value) {
			addCriterion("poster_ip not like", value, "posterIp");
			return (Criteria) this;
		}

		public Criteria andPosterIpIn(List<String> values) {
			addCriterion("poster_ip in", values, "posterIp");
			return (Criteria) this;
		}

		public Criteria andPosterIpNotIn(List<String> values) {
			addCriterion("poster_ip not in", values, "posterIp");
			return (Criteria) this;
		}

		public Criteria andPosterIpBetween(String value1, String value2) {
			addCriterion("poster_ip between", value1, value2, "posterIp");
			return (Criteria) this;
		}

		public Criteria andPosterIpNotBetween(String value1, String value2) {
			addCriterion("poster_ip not between", value1, value2, "posterIp");
			return (Criteria) this;
		}

		public Criteria andSmileysEnabledIsNull() {
			addCriterion("smileys_enabled is null");
			return (Criteria) this;
		}

		public Criteria andSmileysEnabledIsNotNull() {
			addCriterion("smileys_enabled is not null");
			return (Criteria) this;
		}

		public Criteria andSmileysEnabledEqualTo(Byte value) {
			addCriterion("smileys_enabled =", value, "smileysEnabled");
			return (Criteria) this;
		}

		public Criteria andSmileysEnabledNotEqualTo(Byte value) {
			addCriterion("smileys_enabled <>", value, "smileysEnabled");
			return (Criteria) this;
		}

		public Criteria andSmileysEnabledGreaterThan(Byte value) {
			addCriterion("smileys_enabled >", value, "smileysEnabled");
			return (Criteria) this;
		}

		public Criteria andSmileysEnabledGreaterThanOrEqualTo(Byte value) {
			addCriterion("smileys_enabled >=", value, "smileysEnabled");
			return (Criteria) this;
		}

		public Criteria andSmileysEnabledLessThan(Byte value) {
			addCriterion("smileys_enabled <", value, "smileysEnabled");
			return (Criteria) this;
		}

		public Criteria andSmileysEnabledLessThanOrEqualTo(Byte value) {
			addCriterion("smileys_enabled <=", value, "smileysEnabled");
			return (Criteria) this;
		}

		public Criteria andSmileysEnabledIn(List<Byte> values) {
			addCriterion("smileys_enabled in", values, "smileysEnabled");
			return (Criteria) this;
		}

		public Criteria andSmileysEnabledNotIn(List<Byte> values) {
			addCriterion("smileys_enabled not in", values, "smileysEnabled");
			return (Criteria) this;
		}

		public Criteria andSmileysEnabledBetween(Byte value1, Byte value2) {
			addCriterion("smileys_enabled between", value1, value2, "smileysEnabled");
			return (Criteria) this;
		}

		public Criteria andSmileysEnabledNotBetween(Byte value1, Byte value2) {
			addCriterion("smileys_enabled not between", value1, value2, "smileysEnabled");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeIsNull() {
			addCriterion("modified_time is null");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeIsNotNull() {
			addCriterion("modified_time is not null");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeEqualTo(Integer value) {
			addCriterion("modified_time =", value, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeNotEqualTo(Integer value) {
			addCriterion("modified_time <>", value, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeGreaterThan(Integer value) {
			addCriterion("modified_time >", value, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("modified_time >=", value, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeLessThan(Integer value) {
			addCriterion("modified_time <", value, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeLessThanOrEqualTo(Integer value) {
			addCriterion("modified_time <=", value, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeIn(List<Integer> values) {
			addCriterion("modified_time in", values, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeNotIn(List<Integer> values) {
			addCriterion("modified_time not in", values, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeBetween(Integer value1, Integer value2) {
			addCriterion("modified_time between", value1, value2, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("modified_time not between", value1, value2, "modifiedTime");
			return (Criteria) this;
		}

		public Criteria andModifiedNameIsNull() {
			addCriterion("modified_name is null");
			return (Criteria) this;
		}

		public Criteria andModifiedNameIsNotNull() {
			addCriterion("modified_name is not null");
			return (Criteria) this;
		}

		public Criteria andModifiedNameEqualTo(String value) {
			addCriterion("modified_name =", value, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andModifiedNameNotEqualTo(String value) {
			addCriterion("modified_name <>", value, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andModifiedNameGreaterThan(String value) {
			addCriterion("modified_name >", value, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andModifiedNameGreaterThanOrEqualTo(String value) {
			addCriterion("modified_name >=", value, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andModifiedNameLessThan(String value) {
			addCriterion("modified_name <", value, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andModifiedNameLessThanOrEqualTo(String value) {
			addCriterion("modified_name <=", value, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andModifiedNameLike(String value) {
			addCriterion("modified_name like", value, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andModifiedNameNotLike(String value) {
			addCriterion("modified_name not like", value, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andModifiedNameIn(List<String> values) {
			addCriterion("modified_name in", values, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andModifiedNameNotIn(List<String> values) {
			addCriterion("modified_name not in", values, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andModifiedNameBetween(String value1, String value2) {
			addCriterion("modified_name between", value1, value2, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andModifiedNameNotBetween(String value1, String value2) {
			addCriterion("modified_name not between", value1, value2, "modifiedName");
			return (Criteria) this;
		}

		public Criteria andIconIsNull() {
			addCriterion("icon is null");
			return (Criteria) this;
		}

		public Criteria andIconIsNotNull() {
			addCriterion("icon is not null");
			return (Criteria) this;
		}

		public Criteria andIconEqualTo(String value) {
			addCriterion("icon =", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconNotEqualTo(String value) {
			addCriterion("icon <>", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconGreaterThan(String value) {
			addCriterion("icon >", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconGreaterThanOrEqualTo(String value) {
			addCriterion("icon >=", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconLessThan(String value) {
			addCriterion("icon <", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconLessThanOrEqualTo(String value) {
			addCriterion("icon <=", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconLike(String value) {
			addCriterion("icon like", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconNotLike(String value) {
			addCriterion("icon not like", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconIn(List<String> values) {
			addCriterion("icon in", values, "icon");
			return (Criteria) this;
		}

		public Criteria andIconNotIn(List<String> values) {
			addCriterion("icon not in", values, "icon");
			return (Criteria) this;
		}

		public Criteria andIconBetween(String value1, String value2) {
			addCriterion("icon between", value1, value2, "icon");
			return (Criteria) this;
		}

		public Criteria andIconNotBetween(String value1, String value2) {
			addCriterion("icon not between", value1, value2, "icon");
			return (Criteria) this;
		}

		public Criteria andApprovedIsNull() {
			addCriterion("approved is null");
			return (Criteria) this;
		}

		public Criteria andApprovedIsNotNull() {
			addCriterion("approved is not null");
			return (Criteria) this;
		}

		public Criteria andApprovedEqualTo(Byte value) {
			addCriterion("approved =", value, "approved");
			return (Criteria) this;
		}

		public Criteria andApprovedNotEqualTo(Byte value) {
			addCriterion("approved <>", value, "approved");
			return (Criteria) this;
		}

		public Criteria andApprovedGreaterThan(Byte value) {
			addCriterion("approved >", value, "approved");
			return (Criteria) this;
		}

		public Criteria andApprovedGreaterThanOrEqualTo(Byte value) {
			addCriterion("approved >=", value, "approved");
			return (Criteria) this;
		}

		public Criteria andApprovedLessThan(Byte value) {
			addCriterion("approved <", value, "approved");
			return (Criteria) this;
		}

		public Criteria andApprovedLessThanOrEqualTo(Byte value) {
			addCriterion("approved <=", value, "approved");
			return (Criteria) this;
		}

		public Criteria andApprovedIn(List<Byte> values) {
			addCriterion("approved in", values, "approved");
			return (Criteria) this;
		}

		public Criteria andApprovedNotIn(List<Byte> values) {
			addCriterion("approved not in", values, "approved");
			return (Criteria) this;
		}

		public Criteria andApprovedBetween(Byte value1, Byte value2) {
			addCriterion("approved between", value1, value2, "approved");
			return (Criteria) this;
		}

		public Criteria andApprovedNotBetween(Byte value1, Byte value2) {
			addCriterion("approved not between", value1, value2, "approved");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table smf_1messages
	 * @mbg.generated  Sun Feb 16 10:27:49 EST 2025
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table smf_1messages
     *
     * @mbg.generated do_not_delete_during_merge Mon Feb 10 22:58:27 EST 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}