package com.zfgc.zfgbb.migrator.smf.dbo;

public class SMFTopicDb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1topics.id_topic
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    private Integer idTopic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1topics.is_sticky
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    private Byte isSticky;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1topics.id_board
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    private Short idBoard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1topics.id_first_msg
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    private Integer idFirstMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1topics.id_last_msg
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    private Integer idLastMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1topics.id_member_started
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    private Integer idMemberStarted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1topics.id_member_updated
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    private Integer idMemberUpdated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1topics.id_poll
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    private Integer idPoll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1topics.num_replies
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    private Integer numReplies;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1topics.num_views
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    private Integer numViews;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1topics.locked
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    private Byte locked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1topics.unapproved_posts
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    private Short unapprovedPosts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1topics.approved
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    private Byte approved;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1topics.id_previous_board
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    private Short idPreviousBoard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smf_1topics.id_previous_topic
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    private Integer idPreviousTopic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1topics.id_topic
     *
     * @return the value of smf_1topics.id_topic
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public Integer getIdTopic() {
        return idTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1topics.id_topic
     *
     * @param idTopic the value for smf_1topics.id_topic
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public void setIdTopic(Integer idTopic) {
        this.idTopic = idTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1topics.is_sticky
     *
     * @return the value of smf_1topics.is_sticky
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public Byte getIsSticky() {
        return isSticky;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1topics.is_sticky
     *
     * @param isSticky the value for smf_1topics.is_sticky
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public void setIsSticky(Byte isSticky) {
        this.isSticky = isSticky;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1topics.id_board
     *
     * @return the value of smf_1topics.id_board
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public Short getIdBoard() {
        return idBoard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1topics.id_board
     *
     * @param idBoard the value for smf_1topics.id_board
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public void setIdBoard(Short idBoard) {
        this.idBoard = idBoard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1topics.id_first_msg
     *
     * @return the value of smf_1topics.id_first_msg
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public Integer getIdFirstMsg() {
        return idFirstMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1topics.id_first_msg
     *
     * @param idFirstMsg the value for smf_1topics.id_first_msg
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public void setIdFirstMsg(Integer idFirstMsg) {
        this.idFirstMsg = idFirstMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1topics.id_last_msg
     *
     * @return the value of smf_1topics.id_last_msg
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public Integer getIdLastMsg() {
        return idLastMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1topics.id_last_msg
     *
     * @param idLastMsg the value for smf_1topics.id_last_msg
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public void setIdLastMsg(Integer idLastMsg) {
        this.idLastMsg = idLastMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1topics.id_member_started
     *
     * @return the value of smf_1topics.id_member_started
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public Integer getIdMemberStarted() {
        return idMemberStarted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1topics.id_member_started
     *
     * @param idMemberStarted the value for smf_1topics.id_member_started
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public void setIdMemberStarted(Integer idMemberStarted) {
        this.idMemberStarted = idMemberStarted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1topics.id_member_updated
     *
     * @return the value of smf_1topics.id_member_updated
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public Integer getIdMemberUpdated() {
        return idMemberUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1topics.id_member_updated
     *
     * @param idMemberUpdated the value for smf_1topics.id_member_updated
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public void setIdMemberUpdated(Integer idMemberUpdated) {
        this.idMemberUpdated = idMemberUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1topics.id_poll
     *
     * @return the value of smf_1topics.id_poll
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public Integer getIdPoll() {
        return idPoll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1topics.id_poll
     *
     * @param idPoll the value for smf_1topics.id_poll
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public void setIdPoll(Integer idPoll) {
        this.idPoll = idPoll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1topics.num_replies
     *
     * @return the value of smf_1topics.num_replies
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public Integer getNumReplies() {
        return numReplies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1topics.num_replies
     *
     * @param numReplies the value for smf_1topics.num_replies
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public void setNumReplies(Integer numReplies) {
        this.numReplies = numReplies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1topics.num_views
     *
     * @return the value of smf_1topics.num_views
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public Integer getNumViews() {
        return numViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1topics.num_views
     *
     * @param numViews the value for smf_1topics.num_views
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public void setNumViews(Integer numViews) {
        this.numViews = numViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1topics.locked
     *
     * @return the value of smf_1topics.locked
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public Byte getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1topics.locked
     *
     * @param locked the value for smf_1topics.locked
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public void setLocked(Byte locked) {
        this.locked = locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1topics.unapproved_posts
     *
     * @return the value of smf_1topics.unapproved_posts
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public Short getUnapprovedPosts() {
        return unapprovedPosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1topics.unapproved_posts
     *
     * @param unapprovedPosts the value for smf_1topics.unapproved_posts
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public void setUnapprovedPosts(Short unapprovedPosts) {
        this.unapprovedPosts = unapprovedPosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1topics.approved
     *
     * @return the value of smf_1topics.approved
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public Byte getApproved() {
        return approved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1topics.approved
     *
     * @param approved the value for smf_1topics.approved
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public void setApproved(Byte approved) {
        this.approved = approved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1topics.id_previous_board
     *
     * @return the value of smf_1topics.id_previous_board
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public Short getIdPreviousBoard() {
        return idPreviousBoard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1topics.id_previous_board
     *
     * @param idPreviousBoard the value for smf_1topics.id_previous_board
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public void setIdPreviousBoard(Short idPreviousBoard) {
        this.idPreviousBoard = idPreviousBoard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smf_1topics.id_previous_topic
     *
     * @return the value of smf_1topics.id_previous_topic
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public Integer getIdPreviousTopic() {
        return idPreviousTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smf_1topics.id_previous_topic
     *
     * @param idPreviousTopic the value for smf_1topics.id_previous_topic
     *
     * @mbg.generated Mon Feb 10 22:51:30 EST 2025
     */
    public void setIdPreviousTopic(Integer idPreviousTopic) {
        this.idPreviousTopic = idPreviousTopic;
    }
}