create table zfgbb.gender_lkup (
	gender_id integer not null primary key generated by default as identity(sequence name seq_gender_id),
	code text not null,
	description text not null,
	seqno integer not null default 0,
	created_ts timestamp not null default current_timestamp,
	updated_ts timestamp not null default current_timestamp
);

create unique index idx_gender_lkup_code
on zfgbb.gender_lkup (upper(code));

create unique index idx_gender_lkup_seqno
on zfgbb.gender_lkup (seqno);

alter table zfgbb.user_bio_info
add column gender_id integer references zfgbb.gender_lkup;