create table user_contact_info(
	user_id integer not null primary key references zfgbb.user,
	email_address_id integer not null references zfgbb.email_address,
	allow_email_flag boolean not null default true,
	allow_pm_flag boolean not null default true,
	created_ts timestamp not null default current_timestamp,
	updated_ts timestamp not null default current_timestamp
);

create table contact_types_lookup(
	contact_type_id integer not null generated by default as identity primary key,
	description text not null,
	contact_type_code text not null,
	created_ts timestamp not null default current_timestamp,
	updated_ts timestamp not null default current_timestamp
);

create table user_contact_types(
	user_contact_types_id integer not null generated by default as identity primary key,
	user_id integer not null references zfgbb.user,
	contact_type_id integer references zfgbb.contact_types_lookup,
	contact_type_custom_title text,
	contact_type_custom_description text,
	created_ts timestamp not null default current_timestamp,
	updated_ts timestamp not null default current_timestamp
);