create table permission_group (
	permission_group_id integer not null generated by default as identity primary key,
	group_name text not null,
	description text,
	min_posts integer default -1,
	star_image text not null,
	parent_group integer references zfgbb.permission_group,
	created_ts timestamp not null default current_timestamp,
	updated_ts timestamp not null default current_timestamp
);

create table permission_group_assoc(
	permission_group_assoc_id integer not null generated by default as identity primary key,
	permission_group_id integer not null references zfgbb.permission_group,
	permission_id integer not null references zfgbb.permission,
	created_ts timestamp not null default current_timestamp,
	updated_ts timestamp not null default current_timestamp
);

create table user_permission_group_assoc(
	user_permission_group_assoc_id integer not null generated by default as identity primary key,
	permission_group_id integer not null references zfgbb.permission_group,
	user_id integer not null references zfgbb.user,
	created_ts timestamp not null default current_timestamp,
	updated_ts timestamp not null default current_timestamp
);