alter table zfgbb.user_refresh_token
	add column if not exists rotated_ts timestamptz;

alter table zfgbb.user_refresh_token
	add column family_id varchar(36),
	add column successor_id integer references zfgbb.user_refresh_token(user_refresh_token_id) on delete set null;

update zfgbb.user_refresh_token set family_id = gen_random_uuid()::text where family_id is null;

alter table zfgbb.user_refresh_token alter column family_id set not null;

create index idx_user_refresh_token_family_id on zfgbb.user_refresh_token (family_id);

alter table zfgbb.user_refresh_token
	add column revoked_ts timestamptz;

update zfgbb.user_refresh_token
set revoked_ts = coalesce(updated_ts, issued_ts)
where revoked_flag and rotated_ts is null;

alter table zfgbb."user" add column if not exists tokens_valid_after_ts timestamptz;

create unique index if not exists ux_user_sso_key on zfgbb."user" (sso_key);

insert into zfgbb."user" (user_id, sso_key, user_name, display_name, active_flag, failed_login_count)
select 0, '__deleted__', '__deleted__', '[deleted]', false, 0
where not exists (
	select 1 from zfgbb."user" where user_id = 0 or sso_key = '__deleted__'
)
on conflict do nothing;

create table if not exists zfgbb.account_deletion_audit (
	deletion_id integer not null primary key generated by default as identity (sequence name seq_account_deletion_audit_deletion_id),
	subject_user_id_snapshot integer not null,
	subject_pseudonym varchar(64) not null,
	mode varchar(16) not null,
	initiated_by varchar(16) not null,
	requested_ts timestamptz default current_timestamp not null,
	confirmed_ts timestamptz,
	executed_ts timestamptz,
	message_count integer,
	content_resource_count integer,
	created_ts timestamptz default current_timestamp not null,
	updated_ts timestamptz default current_timestamp not null
);

create type zfgbb.ui_theme as enum ('MIDNIGHT', 'KIKORI', 'GORON', 'SHEIK');

create table zfgbb.smiley_set (
	code text not null primary key,
	label text not null,
	ordinal integer not null default 0,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp
);

create table zfgbb.smiley (
	smiley_id integer not null generated by default as identity primary key,
	code text not null unique,
	name text not null,
	label text,
	ordinal integer not null default 0,
	hidden_flag boolean not null default false,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp
);

create table zfgbb.user_settings (
	user_id integer not null primary key references zfgbb.user,
	theme zfgbb.ui_theme,
	smiley_set text not null default 'TPLINK' references zfgbb.smiley_set(code),
	notify_announcements_flag boolean not null default false,
	notify_send_body_flag boolean not null default false,
	send_happy_birthday_flag boolean not null default false,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp
);

drop table zfgbb.user_notif_settings;

create table zfgbb.personal_message_conversation (
	personal_message_conversation_id integer not null generated by default as identity primary key,
	subject text,
	started_ts timestamptz,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp
);

create table zfgbb.personal_message (
	personal_message_id integer not null generated by default as identity primary key,
	personal_message_conversation_id integer not null references zfgbb.personal_message_conversation on delete cascade,
	sender_user_id integer references zfgbb."user" on delete set null,
	sender_name text,
	body text,
	sent_ts timestamptz,
	deleted_by_sender boolean not null default false,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp
);

create table zfgbb.personal_message_recipient (
	personal_message_recipient_id integer not null generated by default as identity primary key,
	personal_message_id integer not null references zfgbb.personal_message on delete cascade,
	recipient_user_id integer not null references zfgbb."user",
	bcc boolean not null default false,
	read_flag boolean not null default false,
	deleted_flag boolean not null default false,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	unique (personal_message_id, recipient_user_id)
);

create index idx_personal_message_conversation on zfgbb.personal_message (personal_message_conversation_id);
create index idx_personal_message_sender on zfgbb.personal_message (sender_user_id);
create index idx_personal_message_recipient on zfgbb.personal_message_recipient (recipient_user_id, deleted_flag);

create table zfgbb.notification_subscription (
	notification_subscription_id integer not null generated by default as identity primary key,
	user_id integer not null references zfgbb."user",
	thread_id integer references zfgbb.thread on delete cascade,
	board_id integer references zfgbb.board on delete cascade,
	last_notified_ts timestamptz,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	check (num_nonnulls(thread_id, board_id) = 1)
);

create unique index ux_notification_subscription_thread
	on zfgbb.notification_subscription (user_id, thread_id) where thread_id is not null;
create unique index ux_notification_subscription_board
	on zfgbb.notification_subscription (user_id, board_id) where board_id is not null;

create table zfgbb.user_warning (
	user_warning_id integer not null generated by default as identity primary key,
	user_id integer not null references zfgbb."user",
	issued_by_user_id integer references zfgbb."user" on delete set null,
	issued_by_name text,
	body text,
	points integer not null default 0,
	issued_ts timestamptz,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp
);

create index idx_user_warning_user on zfgbb.user_warning (user_id);

create table zfgbb.moderation_log (
	moderation_log_id integer not null generated by default as identity primary key,
	actor_user_id integer references zfgbb."user" on delete set null,
	action text not null,
	target_user_id integer references zfgbb."user" on delete set null,
	target_name text,
	board_id integer references zfgbb.board on delete set null,
	thread_id integer references zfgbb.thread on delete set null,
	message_id integer references zfgbb.message on delete set null,
	detail text,
	logged_ts timestamptz,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp
);

create index idx_moderation_log_logged_ts on zfgbb.moderation_log (logged_ts);
create index idx_moderation_log_target on zfgbb.moderation_log (target_user_id);
create index idx_moderation_log_actor on zfgbb.moderation_log (actor_user_id);

alter table zfgbb.permission_group
	add column color text;
