create table avatar (
	avatar_id integer not null generated by default as identity primary key,
	url text,
	user_id integer not null references zfgbb.user,
	active_flag boolean not null default false,
	created_ts timestamp not null default current_timestamp,
	updated_ts timestamp not null default current_timestamp
);

create unique index idx_avatar_user_id
on zfgbb.avatar (user_id);