create table zfgbb.reaction_type (
	reaction_type_id integer not null generated by default as identity primary key,
	code text not null unique,
	label text not null,
	icon text,
	points integer not null default 0,
	ordinal integer not null default 0
);

insert into zfgbb.reaction_type (code, label, icon, points, ordinal) values
	('LIKE', 'Like', 'thumbs-up', 1, 1),
	('HELPFUL', 'Helpful', 'wrench', 2, 2),
	('INSIGHTFUL', 'Insightful', 'lightbulb', 2, 3),
	('FUNNY', 'Funny', 'laugh', 0, 4),
	('DISLIKE', 'Dislike', 'thumbs-down', -1, 5);

create table zfgbb.reaction (
	reaction_id integer not null generated by default as identity primary key,
	reactable_type text not null,
	reactable_id integer not null,
	reactor_user_id integer references zfgbb.user on delete set null,
	reaction_type_id integer not null references zfgbb.reaction_type,
	comment text,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	migration_hash text,
	constraint reaction_target_type_chk check (reactable_type in ('MESSAGE', 'PROJECT', 'RESOURCE', 'WIKI_PAGE')),
	unique (reactable_type, reactable_id, reactor_user_id)
);

create index idx_reaction_target on zfgbb.reaction (reactable_type, reactable_id);
create index idx_reaction_reactor on zfgbb.reaction (reactor_user_id);
create index idx_reaction_type on zfgbb.reaction (reaction_type_id);
