create table if not exists zfgbb.account_deletion_request (
	account_deletion_request_id integer not null primary key generated by default as identity (sequence name seq_account_deletion_request_id),
	user_id integer not null,
	mode varchar(16) not null,
	status varchar(16) default 'PENDING' not null,
	token_sha256 varchar(64) not null,
	requested_ts timestamptz default current_timestamp not null,
	expires_ts timestamptz not null,
	confirmed_ts timestamptz,
	resend_count integer default 0 not null,
	last_sent_ts timestamptz,
	avatar_id_snapshot integer,
	purge_cursor varchar(64),
	recorded_blob_paths text,
	created_ts timestamptz default current_timestamp not null,
	updated_ts timestamptz default current_timestamp not null
);

create unique index if not exists ux_account_deletion_request_pending_user
on zfgbb.account_deletion_request (user_id)
where status = 'PENDING';

create index if not exists idx_account_deletion_request_token_sha256
on zfgbb.account_deletion_request (token_sha256);
