create type zfgbb.ui_theme as enum ('MIDNIGHT', 'KIKORI', 'GORON', 'SHEIK');

create table zfgbb.smiley_set (
	code text not null primary key,
	label text not null,
	ordinal integer not null default 0,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp
);

create table zfgbb.smiley (
	smiley_id integer not null generated by default as identity primary key,
	code text not null unique,
	name text not null,
	label text,
	ordinal integer not null default 0,
	hidden_flag boolean not null default false,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp
);

create table zfgbb.user_settings (
	user_id integer not null primary key references zfgbb.user on delete cascade,
	theme zfgbb.ui_theme,
	smiley_set text references zfgbb.smiley_set(code),
	notify_announcements_flag boolean not null default false,
	notify_send_body_flag boolean not null default false,
	send_happy_birthday_flag boolean not null default false,
	migration_hash text,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp
);

drop table zfgbb.user_notif_settings;
