create table zfgbb.user_refresh_token (
	user_refresh_token_id integer not null primary key generated by default as identity (sequence name seq_user_refresh_token_id),
	user_id integer not null references zfgbb.user on delete cascade,
	token_hash varchar(64) not null unique,
	issued_ts timestamptz default current_timestamp not null,
	expires_ts timestamptz not null,
	revoked_flag boolean default false not null,
	created_ts timestamptz default current_timestamp not null,
	updated_ts timestamptz default current_timestamp not null
);

create index idx_user_refresh_token_user_id
on zfgbb.user_refresh_token (user_id);
