create table zfgbb.personal_message_conversation (
	personal_message_conversation_id integer not null generated by default as identity primary key,
	subject text,
	started_ts timestamptz,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	migration_hash text
);

create table zfgbb.personal_message (
	personal_message_id integer not null generated by default as identity primary key,
	personal_message_conversation_id integer not null references zfgbb.personal_message_conversation on delete cascade,
	sender_user_id integer references zfgbb."user" on delete set null,
	sender_name text,
	body text,
	sent_ts timestamptz,
	deleted_by_sender boolean not null default false,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	migration_hash text
);

create table zfgbb.personal_message_recipient (
	personal_message_recipient_id integer not null generated by default as identity primary key,
	personal_message_id integer not null references zfgbb.personal_message on delete cascade,
	recipient_user_id integer not null references zfgbb."user" on delete cascade,
	bcc boolean not null default false,
	read_flag boolean not null default false,
	deleted_flag boolean not null default false,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	migration_hash text,
	unique (personal_message_id, recipient_user_id)
);

create index idx_personal_message_conversation on zfgbb.personal_message (personal_message_conversation_id);
create index idx_personal_message_sender on zfgbb.personal_message (sender_user_id);
create index idx_personal_message_recipient on zfgbb.personal_message_recipient (recipient_user_id, deleted_flag);

create table zfgbb.notification_subscription (
	notification_subscription_id integer not null generated by default as identity primary key,
	user_id integer not null references zfgbb."user" on delete cascade,
	thread_id integer references zfgbb.thread on delete cascade,
	board_id integer references zfgbb.board on delete cascade,
	last_notified_ts timestamptz,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	migration_hash text,
	check (num_nonnulls(thread_id, board_id) = 1)
);

create unique index ux_notification_subscription_thread
	on zfgbb.notification_subscription (user_id, thread_id) where thread_id is not null;
create unique index ux_notification_subscription_board
	on zfgbb.notification_subscription (user_id, board_id) where board_id is not null;

create table zfgbb.user_warning (
	user_warning_id integer not null generated by default as identity primary key,
	user_id integer not null references zfgbb."user" on delete cascade,
	issued_by_user_id integer references zfgbb."user" on delete set null,
	issued_by_name text,
	body text,
	points integer not null default 0,
	issued_ts timestamptz,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	migration_hash text
);

create index idx_user_warning_user on zfgbb.user_warning (user_id);

create table zfgbb.moderation_log (
	moderation_log_id integer not null generated by default as identity primary key,
	actor_user_id integer references zfgbb."user" on delete set null,
	action text not null,
	target_user_id integer references zfgbb."user" on delete set null,
	target_name text,
	board_id integer references zfgbb.board on delete set null,
	thread_id integer references zfgbb.thread on delete set null,
	message_id integer references zfgbb.message on delete set null,
	detail text,
	logged_ts timestamptz,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	migration_hash text
);

create index idx_moderation_log_logged_ts on zfgbb.moderation_log (logged_ts);
create index idx_moderation_log_target on zfgbb.moderation_log (target_user_id);
create index idx_moderation_log_actor on zfgbb.moderation_log (actor_user_id);

alter table zfgbb.permission_group
	add column color text,
	add column migration_hash text;

alter table zfgbb.user_permission_group_assoc
	add column migration_hash text;
