create table zfgbb.karma (
	karma_id integer not null generated by default as identity  (sequence name sequence_karma) primary key,
	commenting_user_id integer not null references zfgbb.user,
	is_positive boolean not null,
	description text,
	message_id integer not null references zfgbb.message,
	CREATED_TS TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATED_TS TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	migration_id text
);