create table permission_group (
	permission_group_id integer not null generated by default as identity primary key,
	group_name text not null,
	description text,
	min_posts integer default -1,
	star_image text not null,
	parent_group integer references zfgbb.permission_group,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp
);

create table permission_group_assoc(
	permission_group_assoc_id integer not null generated by default as identity primary key,
	permission_group_id integer not null references zfgbb.permission_group on delete cascade,
	permission_id integer not null references zfgbb.permission on delete cascade,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	migration_hash text,
	unique (permission_group_id, permission_id)
);

create table user_permission_group_assoc(
	user_permission_group_assoc_id integer not null generated by default as identity primary key,
	permission_group_id integer not null references zfgbb.permission_group on delete cascade,
	user_id integer not null references zfgbb.user on delete cascade,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	unique (permission_group_id, user_id)
);

create index idx_permission_group_assoc_permission on zfgbb.permission_group_assoc (permission_id);
create index idx_user_permission_group_assoc_user on zfgbb.user_permission_group_assoc (user_id);