create table zfgbb.project_status (
	code text not null primary key,
	label text not null,
	ordinal integer not null default 0
);

insert into zfgbb.project_status (code, label, ordinal) values
	('CONCEPT', 'Concept', 1),
	('WIP', 'Work in Progress', 2),
	('COMPLETE', 'Complete', 3),
	('SCRAPPED', 'Scrapped', 4);

create table zfgbb.resource_type (
	code text not null primary key,
	label text not null,
	ordinal integer not null default 0
);

insert into zfgbb.resource_type (code, label, ordinal) values
	('GRAPHICS', 'Graphics', 1),
	('AUDIO', 'Audio', 2),
	('CODE', 'Code', 3),
	('OTHER', 'Other', 4);

create table zfgbb.wiki_revision_status (
	code text not null primary key,
	label text not null,
	ordinal integer not null default 0
);

insert into zfgbb.wiki_revision_status (code, label, ordinal) values
	('PENDING', 'Pending', 1),
	('APPROVED', 'Approved', 2),
	('REJECTED', 'Rejected', 3);

create table zfgbb.content_format (
	code text not null primary key,
	label text not null,
	ordinal integer not null default 0
);

insert into zfgbb.content_format (code, label, ordinal) values
	('BBCODE', 'BBCode', 1),
	('MARKDOWN', 'Markdown', 2),
	('HTML', 'HTML', 3);

create table zfgbb.content_template_scope (
	code text not null primary key,
	label text not null,
	ordinal integer not null default 0
);

insert into zfgbb.content_template_scope (code, label, ordinal) values
	('ALL', 'All', 1),
	('WIKI', 'Wiki', 2),
	('FORUM', 'Forum', 3);

create table zfgbb.content_collection_kind (
	code text not null primary key,
	label text not null,
	ordinal integer not null default 0
);

insert into zfgbb.content_collection_kind (code, label, ordinal) values
	('COLLECTION', 'Collection', 1),
	('EVENT', 'Event', 2),
	('FEATURE', 'Feature', 3),
	('AWARD', 'Award', 4);

create table zfgbb.wiki_page (
	wiki_page_id integer not null generated by default as identity primary key,
	namespace text not null default 'MAIN',
	title text not null,
	slug text not null,
	redirect_to text,
	created_user_id integer references zfgbb.user on delete set null,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	migration_hash text,
	content_resource_id integer references zfgbb.content_resource,
	thread_id integer references zfgbb.thread on delete set null,
	unique (namespace, slug)
);

create index idx_wiki_page_slug on zfgbb.wiki_page (slug);

create table zfgbb.wiki_page_revision (
	wiki_page_revision_id integer not null generated by default as identity primary key,
	wiki_page_id integer not null references zfgbb.wiki_page,
	content text not null,
	content_format text not null default 'BBCODE' references zfgbb.content_format(code),
	summary text,
	author_user_id integer references zfgbb.user on delete set null,
	current_flag boolean not null default false,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	migration_hash text,
	authored_ts timestamptz,
	author_name text,
	content_size integer not null default 0,
	status text not null default 'PENDING' references zfgbb.wiki_revision_status(code)
);

create index idx_wiki_page_revision_page on zfgbb.wiki_page_revision (wiki_page_id);
create index idx_wiki_page_revision_status on zfgbb.wiki_page_revision (status) where status = 'PENDING';
create unique index ux_wiki_page_revision_current on zfgbb.wiki_page_revision (wiki_page_id) where current_flag;

create table zfgbb.wiki_page_category (
	wiki_page_category_id serial primary key,
	wiki_page_id integer not null references zfgbb.wiki_page on delete cascade,
	category_name varchar(255) not null,
	unique (wiki_page_id, category_name)
);

create index idx_wiki_page_category_name on zfgbb.wiki_page_category (category_name);

create table zfgbb.team (
	team_id serial primary key,
	name varchar(255) not null,
	description text,
	created_user_id integer references zfgbb.user on delete set null,
	created_ts timestamptz not null default current_timestamp,
	migration_hash varchar(64)
);

create table zfgbb.team_member (
	team_member_id serial primary key,
	team_id integer not null references zfgbb.team on delete cascade,
	user_id integer not null references zfgbb.user on delete cascade,
	member_role varchar(80),
	unique (team_id, user_id)
);

create table zfgbb.content_entity (
	content_entity_id integer not null generated by default as identity primary key,
	entity_type text not null,
	title text not null,
	slug text not null,
	summary text,
	wiki_page_id integer references zfgbb.wiki_page,
	thread_id integer references zfgbb.thread on delete set null,
	preview_content_resource_id integer references zfgbb.content_resource,
	created_user_id integer references zfgbb.user on delete set null,
	view_count integer not null default 0,
	download_count integer not null default 0,
	rating real,
	vote_count integer,
	author_name varchar(80),
	published_ts timestamptz,
	last_updated_ts timestamptz,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	migration_hash text,
	constraint content_entity_type_chk check (entity_type in ('PROJECT', 'RESOURCE')),
	unique (entity_type, slug)
);

create index idx_content_entity_slug on zfgbb.content_entity (slug);
create index idx_content_entity_type on zfgbb.content_entity (entity_type);
create index idx_content_entity_thread on zfgbb.content_entity (thread_id);
create index idx_content_entity_wiki_page on zfgbb.content_entity (wiki_page_id);

create table zfgbb.project (
	content_entity_id integer not null primary key references zfgbb.content_entity on delete cascade,
	status text not null default 'WIP' references zfgbb.project_status(code),
	progress smallint not null default 0,
	language text,
	requirements text,
	team_id integer references zfgbb.team
);

create table zfgbb.resource (
	content_entity_id integer not null primary key references zfgbb.content_entity on delete cascade,
	resource_type text references zfgbb.resource_type(code),
	download_content_resource_id integer references zfgbb.content_resource,
	download_url text,
	file_size bigint
);

create view zfgbb.project_view as
	select e.content_entity_id, e.title, e.slug, e.summary, e.wiki_page_id, e.thread_id,
	       e.preview_content_resource_id, e.created_user_id, e.view_count, e.download_count,
	       e.rating, e.vote_count, e.published_ts, e.last_updated_ts, e.created_ts, e.updated_ts,
	       e.migration_hash, e.author_name, p.status, p.progress, p.language, p.requirements, p.team_id
	from zfgbb.content_entity e
	join zfgbb.project p on p.content_entity_id = e.content_entity_id
	where e.entity_type = 'PROJECT';

create view zfgbb.resource_view as
	select e.content_entity_id, e.title, e.slug, e.summary, e.wiki_page_id, e.thread_id,
	       e.preview_content_resource_id, e.created_user_id, e.view_count, e.download_count,
	       e.rating, e.vote_count, e.published_ts, e.last_updated_ts, e.created_ts, e.updated_ts,
	       e.migration_hash, e.author_name, r.resource_type, r.download_content_resource_id, r.download_url, r.file_size
	from zfgbb.content_entity e
	join zfgbb.resource r on r.content_entity_id = e.content_entity_id
	where e.entity_type = 'RESOURCE';

create table zfgbb.project_screenshot (
	project_screenshot_id integer not null generated by default as identity primary key,
	content_entity_id integer not null references zfgbb.content_entity on delete cascade,
	content_resource_id integer references zfgbb.content_resource,
	caption text,
	ordinal integer not null default 0,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	migration_hash text
);

create index idx_project_screenshot_entity on zfgbb.project_screenshot (content_entity_id);

create table zfgbb.project_download (
	project_download_id integer not null generated by default as identity primary key,
	content_entity_id integer not null references zfgbb.content_entity on delete cascade,
	label text,
	url text,
	content_resource_id integer references zfgbb.content_resource,
	file_size bigint,
	ordinal integer not null default 0,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	migration_hash text,
	published_ts timestamptz
);

create index idx_project_download_entity on zfgbb.project_download (content_entity_id);

create table zfgbb.tag (
	tag_id serial primary key,
	name varchar(255) not null unique,
	migration_hash varchar(64)
);

create table zfgbb.project_tag (
	project_tag_id serial primary key,
	content_entity_id integer not null references zfgbb.content_entity on delete cascade,
	tag_id integer not null references zfgbb.tag,
	unique (content_entity_id, tag_id)
);

create table zfgbb.project_news (
	project_news_id serial primary key,
	content_entity_id integer not null references zfgbb.content_entity on delete cascade,
	thread_id integer references zfgbb.thread on delete set null,
	subject varchar(255),
	body text,
	author_user_id integer references zfgbb.user on delete set null,
	author_name varchar(80),
	published_ts timestamptz,
	migration_hash varchar(64)
);

create table zfgbb.content_collection (
	content_collection_id integer not null generated by default as identity primary key,
	code text not null unique,
	title text not null,
	description text,
	kind text not null default 'COLLECTION' references zfgbb.content_collection_kind(code),
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	migration_hash text
);

create table zfgbb.content_collection_item (
	content_collection_item_id integer not null generated by default as identity primary key,
	content_collection_id integer not null references zfgbb.content_collection,
	content_entity_id integer not null references zfgbb.content_entity on delete cascade,
	ordinal integer not null default 0,
	awarded_ts timestamptz,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	migration_hash text,
	unique (content_collection_id, content_entity_id)
);

create index idx_collection_item_collection on zfgbb.content_collection_item (content_collection_id);

create table zfgbb.migration_conflict (
	migration_conflict_id serial primary key,
	entity_type text not null,
	entity_id integer,
	field_name text not null,
	candidates text not null,
	status text not null default 'OPEN',
	resolved_source_type text,
	resolved_value text,
	resolved_by_user_id integer references zfgbb.user on delete set null,
	resolved_ts timestamptz,
	created_ts timestamptz not null default now(),
	updated_ts timestamptz
);

create unique index ux_migration_conflict_entity_field
	on zfgbb.migration_conflict (entity_type, entity_id, field_name);

create table zfgbb.content_template (
	content_template_id integer not null generated by default as identity primary key,
	code text not null,
	content_format text not null default 'BBCODE' references zfgbb.content_format(code),
	scope text not null default 'ALL' references zfgbb.content_template_scope(code),
	source text,
	body text not null,
	wiki_page_id integer references zfgbb.wiki_page,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	unique (code, content_format)
);

create index idx_content_template_code on zfgbb.content_template (code);

create extension if not exists pg_trgm with schema public;

create index idx_thread_name_trgm
	on zfgbb.thread using gin (thread_name gin_trgm_ops);

create index idx_message_text_trgm
	on zfgbb.message_history using gin (message_text gin_trgm_ops)
	where current_flag;

create index idx_content_entity_title_trgm
	on zfgbb.content_entity using gin (title gin_trgm_ops);

create index idx_wiki_page_title_trgm
	on zfgbb.wiki_page using gin (title gin_trgm_ops);

create index idx_content_entity_created_user on zfgbb.content_entity (created_user_id);
create index idx_content_collection_item_entity on zfgbb.content_collection_item (content_entity_id);
create index idx_project_team on zfgbb.project (team_id);
create index idx_project_news_entity on zfgbb.project_news (content_entity_id);
create index idx_wiki_page_created_user on zfgbb.wiki_page (created_user_id);
create index idx_wiki_page_revision_author on zfgbb.wiki_page_revision (author_user_id);
create index idx_team_member_user on zfgbb.team_member (user_id);
