create table zfgbb.wiki_revision_status (
	code text not null primary key,
	label text not null,
	ordinal integer not null default 0
);

insert into zfgbb.wiki_revision_status (code, label, ordinal) values
	('PENDING', 'Pending', 1),
	('APPROVED', 'Approved', 2),
	('REJECTED', 'Rejected', 3);

create table zfgbb.content_template_scope (
	code text not null primary key,
	label text not null,
	ordinal integer not null default 0
);

insert into zfgbb.content_template_scope (code, label, ordinal) values
	('ALL', 'All', 1),
	('WIKI', 'Wiki', 2),
	('FORUM', 'Forum', 3),
	('PROJECT', 'Project', 4),
	('RESOURCE', 'Resource', 5),
	('SIGNATURE', 'Signature', 6);

do $$
declare
	unrepresented text;
begin
	select string_agg(surface, ', ') into unrepresented
	from unnest(array['ALL', 'WIKI', 'FORUM', 'PROJECT', 'RESOURCE', 'SIGNATURE']) as surface
	where surface not in (select code from zfgbb.content_template_scope);
	if unrepresented is not null then
		raise exception 'ContentScope declares % which the scope lookup does not, so a template row could '
			'never store it and parseScope would read it back as the ALL wildcard', unrepresented;
	end if;
end $$;

create table zfgbb.wiki_namespace (
	name text primary key,
	case_mode text not null default 'FIRST_LETTER' check (case_mode in ('FIRST_LETTER', 'CASE_SENSITIVE')),
	system_managed boolean not null default false,
	edit_permission_code text,
	engine_role text,
	unique (name)
);

create unique index ux_wiki_namespace_name_ci on zfgbb.wiki_namespace(lower(name));
create unique index ux_wiki_namespace_engine_role on zfgbb.wiki_namespace(engine_role) where engine_role is not null;

insert into zfgbb.wiki_namespace(name, system_managed, edit_permission_code, engine_role) values
	('MAIN', false, null, 'MAIN'),
	('Template', false, 'ZFGC_WIKI_MODERATOR', 'TEMPLATE'),
	('Category', false, null, 'CATEGORY'),
	('File', false, null, 'FILE'),
	('User', false, null, 'USER'),
	('Talk', false, null, 'TALK'),
	('Special', true, null, 'SPECIAL'),
	('MediaWiki', false, 'ZFGC_SITE_ADMIN', 'MEDIAWIKI'),
	('Project', true, null, null),
	('Resource', true, null, null),
	('Site', false, 'ZFGC_WIKI_MODERATOR', null),
	('Help', false, null, 'HELP');

create table zfgbb.wiki_namespace_alias (
	alias text primary key,
	namespace_name text not null references zfgbb.wiki_namespace(name) on update cascade on delete cascade
);

create unique index ux_wiki_namespace_alias_ci on zfgbb.wiki_namespace_alias(lower(alias));

insert into zfgbb.wiki_namespace_alias(alias, namespace_name) values ('Image', 'File');

create table zfgbb.wiki_page (
	wiki_page_id integer not null generated by default as identity primary key,
	namespace text not null default 'MAIN',
	title text not null,
	slug text not null,
	redirect_to text,
	created_user_id integer references zfgbb.user on delete set null,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	content_resource_id integer references zfgbb.content_resource,
	thread_id integer references zfgbb.thread on delete set null,
	canonical_title_key text,
	unique (namespace, slug)
);

create index idx_wiki_page_slug on zfgbb.wiki_page (slug);
create index idx_wiki_page_created_user on zfgbb.wiki_page (created_user_id);
create index idx_wiki_page_namespace_title on zfgbb.wiki_page(namespace, title);
create index idx_wiki_page_title_trgm on zfgbb.wiki_page using gin (title gin_trgm_ops);
create unique index ux_wiki_page_mediawiki_title on zfgbb.wiki_page (canonical_title_key) where canonical_title_key is not null;

create table zfgbb.wiki_page_revision (
	wiki_page_revision_id integer not null generated by default as identity primary key,
	wiki_page_id integer not null references zfgbb.wiki_page,
	content text not null,
	content_format text not null default 'BBCODE' references zfgbb.content_format(code),
	summary text,
	author_user_id integer references zfgbb.user on delete set null,
	current_flag boolean not null default false,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	authored_ts timestamptz,
	author_name text,
	content_size integer not null default 0,
	status text not null default 'PENDING' references zfgbb.wiki_revision_status(code)
);

create index idx_wiki_page_revision_page on zfgbb.wiki_page_revision (wiki_page_id);
create index idx_wiki_page_revision_status on zfgbb.wiki_page_revision (status) where status = 'PENDING';
create index idx_wiki_page_revision_author on zfgbb.wiki_page_revision (author_user_id);
create unique index ux_wiki_page_revision_current on zfgbb.wiki_page_revision (wiki_page_id) where current_flag;

create index idx_wiki_page_revision_content_trgm
	on zfgbb.wiki_page_revision using gin (content gin_trgm_ops)
	where current_flag;

create table zfgbb.wiki_page_category (
	wiki_page_category_id serial primary key,
	wiki_page_id integer not null references zfgbb.wiki_page on delete cascade,
	category_name varchar(255) not null,
	unique (wiki_page_id, category_name)
);

create index idx_wiki_page_category_name on zfgbb.wiki_page_category (category_name);

create table zfgbb.migration_conflict (
	migration_conflict_id serial primary key,
	entity_type text not null,
	entity_id integer,
	field_name text not null,
	candidates text not null,
	status text not null default 'OPEN',
	resolved_source_type text,
	resolved_value text,
	resolved_by_user_id integer references zfgbb.user on delete set null,
	resolved_ts timestamptz,
	created_ts timestamptz not null default now(),
	updated_ts timestamptz
);

create unique index ux_migration_conflict_entity_field
	on zfgbb.migration_conflict (entity_type, entity_id, field_name);

create table zfgbb.content_template (
	content_template_id integer not null generated by default as identity primary key,
	code text not null,
	content_format text not null default 'BBCODE' references zfgbb.content_format(code),
	scope text not null default 'ALL' references zfgbb.content_template_scope(code),
	source text,
	body text not null,
	wiki_page_id integer references zfgbb.wiki_page,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	source_code text
);

create index idx_content_template_code on zfgbb.content_template (code);
create unique index ux_content_template_wiki_page_format
	on zfgbb.content_template (wiki_page_id, content_format) where wiki_page_id is not null;
create unique index ux_content_template_system_code_format
	on zfgbb.content_template (code, content_format) where wiki_page_id is null;

create table zfgbb.wiki_system_template_page (
	wiki_page_id integer primary key references zfgbb.wiki_page on delete cascade,
	code text not null,
	source_code text
);

create table zfgbb.wiki_import_namespace (
	source_namespace_id integer primary key,
	namespace_name text not null,
	created_ts timestamptz not null default now(),
	updated_ts timestamptz not null default now()
);

create unique index ux_wiki_import_namespace_name_ci
	on zfgbb.wiki_import_namespace(lower(namespace_name));

insert into zfgbb.wiki_import_namespace(source_namespace_id, namespace_name) values
	(0, 'MAIN'),
	(1, 'Talk'),
	(2, 'User'),
	(3, 'User_talk'),
	(4, 'Meta'),
	(5, 'Meta_talk'),
	(6, 'File'),
	(7, 'File_talk'),
	(8, 'MediaWiki'),
	(9, 'MediaWiki_talk'),
	(10, 'Template'),
	(11, 'Template_talk'),
	(12, 'Help'),
	(13, 'Help_talk'),
	(14, 'Category'),
	(15, 'Category_talk');

create or replace function zfgbb.canonical_template_code(p_code text)
returns text language sql stable strict as $$
	select case when coalesce((select case_mode from zfgbb.wiki_namespace where engine_role = 'TEMPLATE'),
			'FIRST_LETTER') = 'CASE_SENSITIVE'
		then normalize(regexp_replace(replace(trim(p_code), '_', ' '), '\s+', ' ', 'g'), NFC)
		else upper(left(normalize(regexp_replace(replace(trim(p_code), '_', ' '), '\s+', ' ', 'g'), NFC), 1)) ||
			substring(normalize(regexp_replace(replace(trim(p_code), '_', ' '), '\s+', ' ', 'g'), NFC) from 2) end
$$;

create or replace function zfgbb.wiki_title_key(p_namespace text, p_title text, p_case_mode text default 'FIRST_LETTER')
returns text language sql immutable strict as $$
	select lower(coalesce(nullif(trim(p_namespace), ''), 'MAIN')) || ':' ||
		case when p_case_mode = 'CASE_SENSITIVE' then '' else
		upper(left(normalize(regexp_replace(replace(trim(p_title), '_', ' '), '\s+', ' ', 'g'), NFC), 1)) end ||
		case when p_case_mode = 'CASE_SENSITIVE' then
		normalize(regexp_replace(replace(trim(p_title), '_', ' '), '\s+', ' ', 'g'), NFC) else
		substring(normalize(regexp_replace(replace(trim(p_title), '_', ' '), '\s+', ' ', 'g'), NFC) from 2)
		end
$$;

create or replace function zfgbb.set_wiki_canonical_title_key()
returns trigger language plpgsql as $$
declare mode text; candidate text;
begin
	select case_mode into mode from zfgbb.wiki_namespace where lower(name) = lower(new.namespace);
	candidate := zfgbb.wiki_title_key(new.namespace, new.title, coalesce(mode, 'FIRST_LETTER'));
	if exists (select 1 from zfgbb.wiki_page p
			where p.wiki_page_id <> coalesce(new.wiki_page_id, -1)
				and lower(p.namespace) = lower(new.namespace)
				and zfgbb.wiki_title_key(p.namespace, p.title, coalesce(mode, 'FIRST_LETTER')) = candidate) then
		if tg_op = 'UPDATE' and old.canonical_title_key is null then
			new.canonical_title_key := null; -- preserve a recorded legacy conflict
			return new;
		end if;
		raise exception 'Wiki title conflicts with an existing canonical title: %', candidate;
	end if;
	new.canonical_title_key := candidate;
	return new;
end $$;

create trigger wiki_page_canonical_title_key before insert or update of namespace, title
	on zfgbb.wiki_page for each row execute function zfgbb.set_wiki_canonical_title_key();

create or replace function zfgbb.guard_wiki_namespace_change() returns trigger language plpgsql as $$
declare page_conflicts text;
begin
	if tg_op = 'UPDATE' and (old.name is distinct from new.name or old.case_mode is distinct from new.case_mode)
		and exists (select 1 from zfgbb.wiki_page where lower(namespace) = lower(old.name)) then
		if old.engine_role is distinct from 'TEMPLATE' or old.name is distinct from new.name then
			raise exception 'Cannot change namespace name/case mode while pages exist in namespace %', old.name;
		end if;
	end if;
	if tg_op = 'UPDATE' and old.engine_role = 'TEMPLATE' and old.case_mode is distinct from new.case_mode then
		if exists (select 1 from (select case when new.case_mode='CASE_SENSITIVE' then source_code
			else upper(left(source_code,1)) || substring(source_code from 2) end code, content_format
			from zfgbb.content_template where wiki_page_id is null) x group by code, content_format having count(*) > 1) then
			raise exception 'Cannot change Template case mode: system template codes would collide';
		end if;
		update zfgbb.content_template set code = case when new.case_mode='CASE_SENSITIVE' then source_code
			else upper(left(source_code,1)) || substring(source_code from 2) end where wiki_page_id is null;
		update zfgbb.wiki_system_template_page set code = case when new.case_mode='CASE_SENSITIVE' then source_code
			else upper(left(source_code,1)) || substring(source_code from 2) end;
		select string_agg(ids, '; ' order by candidate) into page_conflicts from (
			select zfgbb.wiki_title_key(namespace,title,new.case_mode) candidate,
				string_agg(wiki_page_id::text || ':' || slug, ', ' order by wiki_page_id) ids
			from zfgbb.wiki_page where lower(namespace) = lower(new.name)
			group by zfgbb.wiki_title_key(namespace,title,new.case_mode) having count(*) > 1
		) collisions;
		if page_conflicts is not null then
			raise exception 'Cannot change Template case mode; page title collisions: %', page_conflicts;
		end if;
		update zfgbb.wiki_page set canonical_title_key = zfgbb.wiki_title_key(namespace,title,new.case_mode)
		where lower(namespace) = lower(new.name);
	end if;
	if exists (select 1 from zfgbb.wiki_namespace_alias a where lower(a.alias) = lower(new.name)) then
		raise exception 'Wiki namespace name conflicts with alias case-insensitively: %', new.name;
	end if;
	return new;
end $$;

create trigger wiki_namespace_change_guard before insert or update on zfgbb.wiki_namespace
	for each row execute function zfgbb.guard_wiki_namespace_change();

create or replace function zfgbb.guard_wiki_namespace_alias()
returns trigger language plpgsql as $$ begin
	if exists (select 1 from zfgbb.wiki_namespace n where lower(n.name)=lower(new.alias)) then
		raise exception 'Wiki namespace alias conflicts with namespace name case-insensitively: %', new.alias;
	end if;
	return new;
end $$;

create trigger wiki_namespace_alias_guard before insert or update on zfgbb.wiki_namespace_alias
	for each row execute function zfgbb.guard_wiki_namespace_alias();

create or replace function zfgbb.clear_wiki_system_template_marker()
returns trigger language plpgsql as $$ begin
	if tg_table_name = 'content_template' then
		if new.wiki_page_id is not null then
			delete from zfgbb.wiki_system_template_page where wiki_page_id = new.wiki_page_id;
		end if;
	else
		delete from zfgbb.wiki_system_template_page where wiki_page_id = new.wiki_page_id;
	end if;
	return new;
end $$;

create trigger content_template_clear_system_marker after insert or update of wiki_page_id
	on zfgbb.content_template for each row execute function zfgbb.clear_wiki_system_template_marker();

create trigger wiki_page_clear_system_marker after update of namespace, title
	on zfgbb.wiki_page for each row execute function zfgbb.clear_wiki_system_template_marker();
