create table zfgbb.award (
	award_id integer not null generated by default as identity primary key,
	code text not null unique,
	name text not null,
	description text,
	icon text,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp
);

insert into zfgbb.award (code, name, description, icon) values
	('FEATURED_PROJECT', 'Featured Project', 'Recognized for an outstanding fan game or project.', 'trophy'),
	('RESOURCE_STAR', 'Resource Star', 'For a resource or tutorial that helped the community.', 'star'),
	('GOOD_EGG', 'Good Egg', 'A consistently helpful and welcoming community member.', 'heart');

create table zfgbb.user_award (
	user_award_id integer not null generated by default as identity primary key,
	award_id integer not null references zfgbb.award,
	user_id integer not null references zfgbb."user" on delete cascade,
	content_entity_id integer references zfgbb.content_entity on delete set null,
	granted_by_user_id integer references zfgbb."user" on delete set null,
	reason text,
	granted_ts timestamptz not null default current_timestamp,
	created_ts timestamptz not null default current_timestamp,
	updated_ts timestamptz not null default current_timestamp,
	migration_hash text
);

create index idx_user_award_user on zfgbb.user_award (user_id);
create index idx_user_award_content on zfgbb.user_award (content_entity_id);
create index idx_user_award_award on zfgbb.user_award (award_id);
