create table zfgbb.user_poll_choice (
	user_poll_choice_id integer not null primary key generated by default as identity(sequence name sequence_user_poll_choice),
	poll_question_id integer not null references zfgbb.poll_question,
	user_id integer not null references zfgbb.user,
	created_ts timestamp default current_timestamp,
	updated_ts timestamp default current_timestamp
);