alter table zfgbb.poll
drop column max_votes,
add column max_votes integer,
add column migration_hash text,
add column answer_text text,
alter column expire_time drop not null;

create table zfgbb.poll_choice (
	poll_choice_id integer not null primary key generated by default as identity(sequence name seq_poll_choice),
	poll_id integer not null references zfgbb.poll,
	choice_text text not null,
	active_flag boolean not null default false,
	votes integer not null default 0,
	migration_hash text,
	seqno integer not null default 0,
	created_ts timestamp not null default current_timestamp,
	updated_ts timestamp not null default current_timestamp
);


alter table zfgbb.user_poll_choice
drop column poll_question_id,
add column poll_choice_id integer references zfgbb.poll_choice,
add column migration_hash text;

drop table zfgbb.poll_question;

