create table file_attachments (
	file_attachment_id integer not null generated by default as identity primary key,
	message_id integer not null references zfgbb.message,
	filename text not null,
	checksum text not null,
	file_ext text not null,
	mime_type text not null,
	active_flag boolean not null default false,
	created_ts timestamp not null default current_timestamp,
	updated_ts timestamp not null default current_timestamp
);
